### ISSUE TITLE
Sometimes staticfilecache:cache:flushcache does not flush the typo3 frontend cache (Boostmode)

### ISSUE THREAD

**Issue by glucka** [lochmueller/staticfilecache#100]
## Bug Report

**Current Behavior**
After run the staticfilecache:cache:flushcache, 
staticfilecache:cache:runcacheboostqueue do not generate filecache files in typo3temp/tx_staticfilecache
If i clear the frontend cache in typo3 it works again.

**Expected behavior/output**
Staticfilecache:cache:flushcache should clear the typo3 frontend cache too.

**Environment**
- TYPO3 version(s): 8.7.12
- staticfilecache version: 6.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Unix/Linux

**Comment by lochmueller** [comment]
Thanks for the report @glucka 
Fixed in the commit and will be part of the next release.

**Comment by lochmueller** [comment]
Done. Version 6.1.1 is released ;)

**Comment by glucka** [comment]
Vielen Vielen Dank Tim!!

**Comment by glucka** [comment]
Es hat leider nicht geholfen.
Ich muss immer manuell das FE Cache leeren von der betroffene Seite in BE sonns werden nicht neue file-s generiert. ```runcacheboostqueue``` lauft schön ab.. result 200 aber passiert nichts.
Es sieht so aus das flushcache leert nicht den FE cache...oder löst eine bestimmte hook nicht aus?

**Comment by glucka** [comment]
clearCacheCmd kommt leider als lösung nicht in frage weil die seite hat über 3700 Seiten.. das verlangsamt das BE extrem

**Comment by lochmueller** [comment]
Aber die Gruppe passt ja, oder? https://github.com/lochmueller/staticfilecache/commit/6dff4292d060d3fe6629e1de6496483224c77728#diff-b77c664e699ab841e96f9327b39a552aR67

Kannst du nach dem "runcacheboostqueue" mal schauen was noch da ist, was zu dem fehler führen kann (cf_page, cf_pagesection)?

**Comment by lochmueller** [comment]
Add some documentation related to this problem:
https://github.com/lochmueller/staticfilecache/blob/master/Documentation/KnownProblems/Index.rst#caching-framework-with-none-db-backends

It is a problem of the core and not of the staticfilecache extension
