### ISSUE TITLE
static file cacheview every time actual

### ISSUE THREAD

**Issue by hoezaykut** [lochmueller/staticfilecache#101]
How can I always keep the static file cache fresh (every 24 hours) ?

maybee with a crawler ? 
![backend-info-statischer datei cache](https://user-images.githubusercontent.com/12664793/46794944-35940580-cd49-11e8-8fbc-bfe567a29e7a.jpg)

**Comment by hoezaykut** [comment]
> 
> 
> How can I always keep the static file cache fresh (every 24 hours) ?
> 
> maybee with a crawler ?
> ![backend-info-statischer datei cache](https://user-images.githubusercontent.com/12664793/46794944-35940580-cd49-11e8-8fbc-bfe567a29e7a.jpg)

**Comment by lochmueller** [comment]
Hey @hoezaykut 
Please ask questions in the Slack Channel #ext-staticfilecache  (next time)
The issue tracker is only for development (bugs/features).
Regards,
Tim
