### ISSUE TITLE
static file cacheview every time actual

### ISSUE THREAD

**Issue by hoezaykut** [lochmueller/staticfilecache#102]
## Bug Report

**Current Behavior**
How can I always keep the static file cache fresh (every 24 hours) ?

maybee with a crawler ?

**Expected behavior/output**

**Environment**
- TYPO3 version(s): [e.g. 8.7.19]
- staticfilecache version: [e.g. 6.1.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Linux]

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by lochmueller** [comment]
Hey @hoezaykut 
It makes no snese to drop the cache every 24 hours (why?). But if there is a use case -> please send me more information. I would add some documentation to the extension.

External crawler could ONLY fill the cache. It is NOT possible for a external process to invalidate the cache. So you have to check your cache-timeouts in your installation and work with something like clearCacheAtMidnight oder the extension configuration "sendCacheControlHeaderRedirectAfterCacheTimeout". EXT:staticfilecache respect all you cache timeout settings of your TYPO3 installation

Regards,
Tim

**Comment by lochmueller** [comment]
Did this information solve your problems?

**Comment by lochmueller** [comment]
I will close this issue. For further bugs/features feel free to create new issues. Please use TYPO3 Slack #ext-staticfilecache for genral questsions next time.

Regards,
Tim
