### ISSUE TITLE
[QUESTION]: What could be the cause of the error 'User or group is set'.

### ISSUE THREAD

**Issue by nitsan-technologies** [lochmueller/staticfilecache#11]
Hello,

I am using the TYPO3 8.7.3 with this extension.
I have setup a page with force generation of static cache, but I am getting this error in the backend module that is 'User or group is set'.

May I know the cause of this error?
So I can check my setup and try to solve it.

Thanks!

**Comment by lochmueller** [comment]
There are only three rules, that could be ignored in the "force cache mode":
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/ForceStaticCache.php#L25
This Rule is not part of it:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoUserOrGroupSet.php#L15
because we cannot check the user login in the htacess file, so it is not possible to cache user based outputs.

Furthermore it is not recommended to use the "force static file cache" checkbox in the page properties at all. It is more usefull to fix the errors/plugins/extensions, if there are problems that are fixable (FE user management is not possible).

I will close this issue.

Regards,
Tim

**Comment by nitsan-technologies** [comment]
Thanks for your answer.

OK, I got your point.
![screenshot](https://user-images.githubusercontent.com/2622317/28778442-c07c9224-75ee-11e7-83bd-370114529d9c.png)


But we have a powermail form in all the pages, and we are getting error from it (please see attachment).
Is there any way to workaround with it?

Second one is, we have set the config.no_cache=0 at all possible places but still the error 'config.no_cache is set to true' is showing. Is there any other possibilities?

Can you please help us?

**Comment by MichaelNussbaumerGOWEST** [comment]
Powermail is an uncached plugin, so you cannot use a static file cache if you have it on your site. We had the same issue with formhandler. I solved it by loading the form via ajax. There is no solution for this without changing of either the powermail integration (load it via ajax for example) or the extension itself.

**Comment by lochmueller** [comment]
Perhaps you could cache the extension output, if the form target is not the same page (e.g. put the target on one central page). Than you could cache the forms one the other content pages.

This will speed up the rendering even without StaticFileCache... ;)

Regards,
Tim

**Comment by nitsan-technologies** [comment]
@lochmueller   
Thanks for the message,
I have managed the powermail form with ajax submission and removing the actions from the non- caching section which doesn't make any side effect to us.

But, the site has config.no_cache = 0 at all possible places but still the errors are showing. Please check the screenshot below.
![screenshot1](https://user-images.githubusercontent.com/2622317/28810240-3f5f5020-7678-11e7-99d1-490ab2fa3bca.png)

I can't get the cause of this errors. Now all 3 extension errors are gone without using force static file generation of page.
Can you please help us?

Thanks in advance.

**Comment by lochmueller** [comment]
@nitsan-technologies Please first check all other messages. "config.no_cache" could be the result of one of the other problems. If config.no_cache is true is the single message in the log, than you have to check it. Please take care, that you call the page without a active BE session.

**Comment by int-digital** [comment]
@nitsan-technologies if it's not too late: after updating RealURL from 2.2.0 to 2.3.1 the caching works fine and the message "config.no_cache ist true" is gone.

**Comment by lochmueller** [comment]
@int-digital Thanks for the information. I add a short notice to the current documentation: https://github.com/lochmueller/staticfilecache/commit/f7c8a6e7a224c2420f5258a88eaf30418e7db733
