### ISSUE TITLE
All Caches deleted when editing content

### ISSUE THREAD

**Issue by mibe-dt** [lochmueller/staticfilecache#110]
## Bug Report

**Current Behavior**
Staticfilecache of every page is deleted when editing content of a page. Only without bootsmode.

**Expected behavior/output**
Cache files of other pages should persist when editing content.

**Environment**
- TYPO3 version(s): 8.7.20
- staticfilecache version: 6.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian Jessie/Apache, PHP: 7.2.12

**Comment by lochmueller** [comment]
Hey @mibe-dt 
This is the regular process. If you DO NOT use the "boost mode" all cache entries are dropped, everytime the Caching-Framwork delete the cache of the pages or single pages. If you don't want this situation you have to use the boost mode.

Or do you mean you work on page A and the cache of page A+B is dropped? Then you caching rules in the backend are wrong or you change the page (and not the content)? Page changes drop many cache entries, because this effects menus that are part of many pages...

Regards,
Tim

**Comment by mibe-dt** [comment]
Hi Tim,

If I work on content of page A, all cache entries are dropped from all existing pages A, B, C and so on.
My configuration is:
```
'staticfilecache' => 'a:19:{
s:23:"clearCacheForAllDomains";s:1:"1";
s:27:"enableStaticFileCompression";s:1:"0";
s:23:"showGenerationSignature";s:1:"1";
s:9:"fileTypes";s:7:"xml,rss";
s:8:"strftime";s:14:"%d-%m-%y %H:%M";
s:11:"recreateURI";s:1:"0";
s:9:"boostMode";s:1:"0";
s:18:"backendDisplayMode";s:4:"both";
s:20:"disableInDevelopment";s:1:"0";
s:20:"htaccessTemplateName";s:61:"EXT:staticfilecache/Resources/Private/Templates/Htaccess.html";
s:13:"saveCacheHook";s:17:"InsertPageIncache";
s:22:"sendCacheControlHeader";s:1:"1";
s:47:"sendCacheControlHeaderRedirectAfterCacheTimeout";s:1:"0";
s:16:"sendTypo3Headers";s:1:"0";
s:15:"cacheTagsEnable";s:1:"0";
s:19:"cacheTagsHeaderName";s:12:"X-Cache-Tags";
s:19:"sendHttp2PushEnable";s:1:"0";
s:27:"sendHttp2PushFileExtensions";s:6:"css,js";
s:22:"sendHttp2PushFileLimit";s:2:"10";
},
```

**Comment by lochmueller** [comment]
Do you check, if this is a miss configuration of TYPO3. Becuase StaticFileCache is used the CachingFramework and drop only pages related to the TYPO3 commands. So perhaps TYPO3 fire "clear all caches"? I think there is a miss configuration like "clearCacheCmd = all" in your page?

**Comment by lochmueller** [comment]
OK. I close this issue. If you have some more details, that StaticFileCache delete all information without the right hook, please send me some Feedback.

Note: https://docs.typo3.org/typo3cms/TSconfigReference/PageTsconfig/TceMain.html#clearcachecmd ClearCacheCmd is PageTSConfig. I suggest to use Info -> PageTSConfig module to check if ClearCacheCmd is used. It is also possible that you use extensions that drop the caches via Datahandler hooks in the backend.

Regards,
Tim
