### ISSUE TITLE
On pages with option tx_staticfilecache_cache_force static files are generated before css/js file links are replaced by scriptmerger merged links

### ISSUE THREAD

**Issue by djangones** [lochmueller/staticfilecache#111]
## Bug Report

**Current Behavior**
On pages with active option tx_staticfilecache_cache_force the static cache files are generated before all css/js file links in the document are replaced by the corresponding third party plugin scriptmerger merged css/js file links.
This only happens on pages where tx_staticfilecache_cache_force option is activated. On pages that are cacheable by default the scriptmerger-replacement happens before the static file is generated.

**Expected behavior/output**
The static cache files should be generated from the file version where the scriptmerger replacements have been done already.

**Environment**
- TYPO3 version(s): 8.7.22
- staticfilecache version: 6.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by lochmueller** [comment]
Hmm.... "Force Static File Cache" has many Side effects, because there are plugins/CE on the page that are explicit configured as "non cachable" and StaticFileCache" cache the files nevertheless. I recommend to check, why you have to use "force Static File Cache" at all....?!

**Comment by djangones** [comment]
Thank you for your answer! Yes, I know the various reasons why certain pages cannot be cached by default, but there are always plugins that don't use the possible caching mechanisms, or there are dynamic pages with such plugins that change very rarely and where it is better to cache the page statically for performance reasons.  That's why I find the option to force static caching a ver good enhancement! So far I have had good experiences with this, but now I have noticed that the scriptmerger-replacements are obviously not executed before the static file is created when the force option is activated. Possibly only a question of the order in which the hooks are processed. But obviously only, if the force option is activated, because on the other pages the replacements are executed before the static cache file is generated...

**Comment by lochmueller** [comment]
Hey @djangones Static File Cache have also the option to you a "later" hook. But please keep in mind... this potential result in more mutal reactions. Keep also in mind, that plugin that create "non-Cacheable URLs are different than cachable URLs (cHash!!). So I suggest to ask the plugin developer do build on top of the core cache options (like a cache flasg in the FlexForm etc.).

I close the issue, because I have no influence on external Hook processes (Scriptmeger) in connection with "Force statif file Cache".

**Comment by djangones** [comment]
I played around with saveCacheHook-options and noticed that the scriptmerger links in the generated static files are replaced correctly.
In the info module, however, there is no longer any indication that anything has been cached. In addition, the `@{expires}` variable in htacces-template is set to 1970, so you will be redirected directly to /index.php and the cache file will never be delivered.
I hope my explanations are understandable for you?

**Comment by lochmueller** [comment]
Hey @djangones this is strage. Because "expires" is defined as "(new DateTimeService())->getCurrentTime() + $lifetime" in PHP so it could not lower than "now"?!? Could you run some debugging...?! Regards, Tim

**Comment by djangones** [comment]
I took another closer look at it and found out that the date is not 1970 after all, but assumes a very strange value (19700101130000). This is probably due to the fact that the value of $lifetime is somehow negative (-1547418236).
I looked briefly into the code of HtaccessService.php and would say that this is because the configuration variable 'htaccessTimeout' is not set anywhere and thus is undefined. The alternatively used value $lifetime, which will be passed to the write() function, could be negative because no entry has been created in the cache table (cf_staticfilecache)...

**Comment by lochmueller** [comment]
Hmm... strage. The "htaccessTimeout" could be set via TypoScript. Do you check the "getRealLifetime" function in "docroot/typo3conf/ext/staticfilecache/Classes/Cache/AbstractBackend.php" ?!?! Is the negative value created in this method?
Regards, Tim

**Comment by djangones** [comment]
Ich werde das bei nächster Gelegenheit genauer anschauen, allerdings bleibt die Frage, warum nichts in die Cache-Tabelle geschrieben wird, obwohl die statischen Dateien erstellt werden. Ich würde vermuten, dass der Ursprung für die fehlerhafte Berechnung dort liegen könnte...

**Comment by djangones** [comment]
I will take a closer look at this at the next opportunity, but the question remains why nothing is written to the cache table even though the static files are created. I would suspect that the source of the incorrect calculation could be there...

**Comment by lochmueller** [comment]
Do you check, if the insert to the cache table is executed. Perhaps it is a simple problem like "unsigned" table fields and the "negative lifetime" is the problem. I will try to rebuild this in the next days...

**Comment by lochmueller** [comment]
Hmm... I double check the problem of the negative getRealLifetime result, but do not found the problem. It seams that it is explicit set to a nagative value. I do not want to change the check in getRealLifetime to "0 >= $lifetime || $lifetime > $this->maximumLifetime" becaus it looks wrong to force a positive value.... so please to check you settings and debug the problem in your instance. If there are any new information feel free to create a new issue, if it is a staticfilecache bug. Regards, Tim
