### ISSUE TITLE
Typo3 9.5.x compatibility - staticfilecache breaks routeEnhancers

### ISSUE THREAD

**Issue by M4rt1n17** [lochmueller/staticfilecache#114]
## Bug Report

**Current Behavior**
since I'm using a routeEnhancer (which is working) staticfilecache breaks the functionality of it. And throws Error --> https://pastebin.com/NW3ix8hk

**Expected behavior/output**

**Environment**
- TYPO3 version: 9.5.3
- staticfilecache version: 6.1.1 and 6.1.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian Stretch, Apache, PHP 7.3.1

**Additional context**
How to reproduce:
1.) use Typo3 v9.5.3
2.) install staticfilecache v6.1.1 or v6.1.2
3.) setup a routeEnhancer 
3.1) open /typo3conf/sites/[site_id]/config.yaml
3.2) paste:
```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: ''
    map:
      sitemap.xml: 1533906435
```
This will route /sitemap.xml to the type "1533906435" which is basically the sitemap of the sysext "seo"
So this will redirect "/sitemap.xml" to "/?type=1533906435" without changing the URL.
4.) Clear all Caches
5.) Flush TYPO3 and PHP Cache
6.) open anonym Tab
7.) go to your page
7.1) verify its working, pls also reload!
8.) go to /sitemap.xml
8.1) verify its working!
8.2) reload!
9) verify its not working anymore...
9.1) at v6.1.1 its instat not working anymore
9.2) at v6.1.2 all other pages (beside the sitemap.xml) are nopt working anymore

This just happens as soon as you do step 4.) and 5.

I dont know how to solve that and dont even know why this is happening, but maybe because of it is a .xml file and staticfilecache wants to serve it cached but routeEnhancer wants to redirect to /?type=1533906435

Hope that helps and makes it possible to fix this, as for now staticfilecache is not completely Typo3 9.5 compatible

**Comment by lochmueller** [comment]
Hey @M4rt1n17 
Do you use "force Static file cache" (field: tx_staticfilecache_cache_force or via hook: isForceCacheUri)? This option will break many things (!!!!) I suggest to make the page cachable without using the "force Static file cach" option.
Regards,
Tim

**Comment by M4rt1n17** [comment]
True that fixed that issue.
But that actually shows another problem/bug, but I will create another Issue for that
