### ISSUE TITLE
Real stealth Cache with handler

### ISSUE THREAD

**Issue by M4rt1n17** [lochmueller/staticfilecache#121]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When a page gets edited the Cache of the page should automaticaly get cleared, but it would be much more awesome if the Cache gets rebuilded and after the new Cache got generated the old cache should be cleared so everytime a user calls the site a cached page will get delivered. As this take max 1-2 sec to generate a page the user get a max 2 sec old page

**Describe the solution you'd like**
Cache should never get cleared it should get rebuilded. Eveen if all Caches gets deleted!

**Describe alternatives you've considered**
Well there is no alternative here

**Teachability, Documentation, Adoption, Migration Strategy**
Make a handler which controlls all the cached pages.
When we clear all caches he declares all the pages as "revalidate" or "outdated" and begins generating new caches.
Everytime the Cachehandler geenrates a new Cache for a page he clears the old cache and uses the new one.

This is real stealth cache because every time a user hits the Site he will get a cached answer. But also the cache is pretty up to date because if you make some changes it takes maximum up to 2 sec to have the change life.

Also it could be possible to define a max lifetime of the Cache. When the cache reaches his Lifetime he get regenerated aswell.

ATM if you change anything the first user have to wait pretty long untill he gets a answer from the Server (max 2 sec hich is to long) even if you visit your site 20 min after the change you will have to wait 2 sec because you are the first visitor. To prevent this this Cache handler would be awesome! Also a automatic Cache refresher  (with max lifetime) is awesome!

**Comment by lochmueller** [comment]
Nice idea ;) It is already part of the extension. You can active the "Boost Mode" in the extension manager and create a scheduler task (every minute). In "Boost Mode" the cache is never cleared and a queue is build up on every "clear cache operation". The Scheduler task recall the pages and update the cache entries..... so not the same implementation, but the same result 👍 I close this issue...

**Comment by lochmueller** [comment]
@M4rt1n17 this is wrong. The mechanism add only the selected pages to the queue, that are triggered throw the Caching framework. That means: If you hit "clear FE cache" in the backend (should never be used in general), all caches are rebuild. If you change a text on one page, only the cache of the single page is cached. StaticFileCache respect the TYPO3 caching strategy (like clearCacheCmd etc.). Regards, Tim
