### ISSUE TITLE
Page option "Cache page as static file" seems to have no effect

### ISSUE THREAD

**Issue by Moongazer** [lochmueller/staticfilecache#123]
## Bug Report

**Current Behavior**
I have a plugin to show random content on one page, so I deactivated the checkbox "Cache page as static file" on that page. But still the same content appears all the time. If I clear the frontend-cache for that page, TYPO3 picks a new random element correctly and renders the page once. All next reloads coming from the cache again, **so it seems this option has no effect**.
For testing this I run the frontend in a different browser, also force-reload or clearing the history in that browser does not help (and because of the speed my guess is that staticfilecache is still serve this page)

**Expected behavior**
After disabling the page option "Cache page as static file", TYPO3 should always render the page from scratch, picking always a new  random element (Or taking the page from its own cache and only re-render the "dynamic area" where my plugin is located. I'm not sure how the TYPO3 cache exactly behaves, but as far as I remember this is how it works without the staticfilecache extension).

**Environment**
- TYPO3 version: 9.5.4
- staticfilecache version: 6.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Ubuntu 18
- PHP: 7.2
- Browser (Backend): Firefox
- Browser (Frontend): Chrome

**Additional context**
Usually I try to be be as helpful as I can tracking down issues and how they can be fixed, but everything related with caching systems is an art for its own with so many things you have to have in mind (server side, headers, browser side, ...), so I not even tried ;-) I think you guys are way more deeper in this matter. Respect and thanks for that!

**Comment by lochmueller** [comment]
Hey @Moongazer 
please check if a static file is generated in ```typo3temp/tx_staticfilecache/your-speaking-path.html```. The behavior ```After disabling the page option "Cache page as static file", TYPO3 should always render the page from scratch``` is wrong. If the elements on the page are cachable, TYPO3 will cache the elements, even there is no static file cache. The checkbox disable only th Static file cache and not all caches on the page.

I supposes that you use the "random function" in a cachable object in TYPO3 and this is StaticFileCache problem.

Regards,
Tim

**Comment by Moongazer** [comment]
Hi, thank you for the fast response. Yea that is exactly what I ment with "Or taking the page from its own cache and only re-render the 'dynamic area' ...". I took a closer look again and think you are right with your guess that my random function is a cachable object (because it behaves like I described above also if I disable your extension). Thanks for pointing to it!

And another good point: I checked for `typo3temp/tx_staticfilecache/` but there is not such a folder, so **the extension is not active yet at all** (I tried with other pages without my random function)! But its installed in the extension manager, and I cleared the TYPO3 cache as well (frontend and backend). Is there anything else to do (except the .htacces config)?

**Comment by lochmueller** [comment]
I close the issue, because the problem do not exists. 

Please check that you call the pages, without active session/cookie. .htaccess file is only for delivery and not for generation. First you have to take care, that the StaticFileCache create static files, then you can check you htaccess setup. For generation problems check the "Info -> StaticFileCache" module.
Please check the documentation for more details: https://github.com/lochmueller/staticfilecache/tree/master/Documentation

**Comment by Moongazer** [comment]
OK I tracked down the issue, is has to do with sys_domain records. Will open a new issue with proper description how to reproduce.
