### ISSUE TITLE
The extension doesn't work if no sys_domain record is created

### ISSUE THREAD

**Issue by Moongazer** [lochmueller/staticfilecache#124]
## Bug Report

Since TYPO3 v9 I use the new Site module, so there is no need any more to create sys_domain records in the root page. The CoreApiReference says 

> "For those coming from earlier TYPO3 versions: With site handling, you do not need sys_domain records anymore"

If no domain record is created, the Info module for StaticFileCache shows for any page the message `static cache disabled on domain: mydomain.localhost`. After I created a sys_domain record for `mydomain.localhost`, the extension starts working like expected (`tx_staticfilecache` folder is created and the Info module shows green checkmarks for visited pages).

**Possible Solution**
If this is the expected behaviour, the manual should say, that adding a domain record is a configuration requirement. Or (probably better solution if future versions will work with the new Site module) somehow add the `tx_staticfilecache_cache` option there somewhere.

**Environment**
- TYPO3 version: 9.5.4
- staticfilecache version: 6.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Ubuntu 18
- PHP: 7.2
- Browser (Backend): Firefox
- Browser (Frontend): Chrome

**Comment by Moongazer** [comment]
I think this issue is patched already, but it was not in my release 6.1.0. If I apply the patch from https://github.com/lochmueller/staticfilecache/commit/7712336e802af1e488606d0e1fea8048ba611949 manually, it works also like expected without domain record. Sorry & closed.
PS: When can we expect a new release?^^

**Comment by lochmueller** [comment]
Hey @Moongazer ,
Note: https://github.com/lochmueller/staticfilecache/commit/7712336e802af1e488606d0e1fea8048ba611949
Under the title of the page, are the tags (releases) that are after this commit.
Also please keep in mind, there is a "Show x newer tags" link on the https://github.com/lochmueller/staticfilecache/releases on Github above the last "promoted" release. The current reelase is 6.1.2

Have fun with the extension...

Rgeards,
Tim

**Comment by Moongazer** [comment]
Oh gosh... I've never seen somewhere that tag releases can be ahead of "normal" releases. Sorry for all that reporting than
