### ISSUE TITLE
Add response header if and only if page is served from static file cache

### ISSUE THREAD

**Issue by Moongazer** [lochmueller/staticfilecache#125]
## Feature Request
To verify that the setup and configuration is correct, it would be very helpful if we can detect on browser side if a file is served from the static file cache. Therefore I'd recommend a response header like `X-Cache: Static File` or so, probably set in the .htaccess config.

**Comment by Patta** [comment]
@moongazer just enable the showGenerationSignature option for testing or use a custom htaccess template (htaccessTemplateName).

**Comment by lochmueller** [comment]
@Patta You are right. But a Signatur, that is format independent (e.g. json) would be cool. I will add this to the default htaccess file (switchable)...

**Comment by Moongazer** [comment]
@Patta Also as I was debugging, lets say I had to reload the page 50 times, so if I always have to look into the source code for the signature, it would make 100 clicks plus scrolling down the page each time... Just not very convenient^^
