### ISSUE TITLE
Table cf_staticfilecache_tags have many double entries

### ISSUE THREAD

**Issue by glucka** [lochmueller/staticfilecache#130]
I tried to use the typo3 garbage collection task, but did not help.

**Comment by lochmueller** [comment]
Hey @glucka 
The Typo3DatabaseBackend->collectGarbage remove the tags only, if there is no valid relation to still valid entries in the DB.
Do you check the cache tag relation, if the cache entry is still valid? "collectGarbage" remove only "old" cache entries...
Regards,
Tim

**Comment by glucka** [comment]
Hi,
Yes the cache entry is still valid, but i do not understand why exist the same entry so many times.
This table have now 94000 entrys :)

**Comment by lochmueller** [comment]
Hey @glucka 
this is not part of the StaticFileCache Extension. The StaticFileCache Backend uses the Core default Typo3DatabaseBackend that handle tag entries in that way. If there are two entries with the Tag "test", the result are two tag entries with the same value. So... this is core default handling.
I close this issue.. if I understood you wrong, feel free to reopen the issue.
Regards,
Tim
