### ISSUE TITLE
Feature: More technical information in the Backend

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/staticfilecache#134]
## Feature Request

**Describe the solution you'd like**
Display more technical information in the backend. E.g.
- Current size of the BoostQueue (active and inactive items) incl. note for scheduler tasks
- Configuration notes related to the FileGenerator
- Perhaps multiple "Tabs" for a better structure of the information

**Comment by glucka** [comment]
+1 Current size of the BoostQueue (active and inactive items) incl. note for scheduler tasks

**Comment by Patta** [comment]
A better view of child pages would be great. Currently only the direct childs are displayed. A direct view of the tree with cached pages on the root level would be great.
