### ISSUE TITLE
Call to undefined function brotli_compress()

### ISSUE THREAD

**Issue by CarstenHager** [lochmueller/staticfilecache#140]
Hallo Tim,

ich erhalte manchmal folgende Fehlermeldung:

<img width="1252" alt="Screenshot 2019-04-03 06 49 44" src="https://user-images.githubusercontent.com/5907780/55453847-dcad7780-55dd-11e9-8fe9-03a54cebe55b.png">

Wenn ich die gleiche Seite danach nochmal lade klappt es.
Ich nutze den aktuellen Master. Meine htaccess hab ich wie in #139 beschrieben angepasst.

Mein Englisch ist nicht so gut, deswegen auf Deutsch.. Sorry

**Comment by lochmueller** [comment]
Hey @CarstenHager 
das PHP muss mit Brotli support kompiliert sein. Geht somit nicht auf jedem Server.
Ich werde mal eine Prüfung und ein error log ergänzen, sodass man die Fehlermeldung nicht sieht, wenn man es einschaltet, der Server aber nicht kann.
Grüße,
Tim

**Comment by lochmueller** [comment]
Hey @CarstenHager ,
fixed in current master. Now: If Brotli is enabled via configuration, but not available by server configuration a error is logged and no exception is thrown.
Regards,
Tim
