### ISSUE TITLE
HTTP/2 Push: Style URIs added twice

### ISSUE THREAD

**Issue by infabo** [lochmueller/staticfilecache#141]
## Bug Report

**Current Behavior**

Content of `.htaccess` of cache-entry folder:

```html
Header add Link "</path/to/mystylesheet.css>; rel=preload; as=style"

Header add Link "</path/to/mystylesheet.css>; rel=preload; as=style"
```

This is due to https://github.com/filamentgroup/loadCSS

```html
<link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="path/to/mystylesheet.css"></noscript>
```

**Expected behavior/output**

Only one unique entry.

**Environment**
- TYPO3 version(s): 8.7.24
- staticfilecache version: 8.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**

make paths unique e.g. `array_unique`

**Additional context**
Add any other context about the problem here

**Comment by lochmueller** [comment]
Thanks. Added the `array_unique` in the mapping of the HTTP2 push headers abstraction
