### ISSUE TITLE
Uncaught TYPO3 Exception in Backend Module 

### ISSUE THREAD

**Issue by Patta** [lochmueller/staticfilecache#144]
## Bug Report

**Current Behavior**
Uncaught TYPO3 Exception when the backend module is opened.

```
Argument 1 passed to TYPO3\CMS\Fluid\ViewHelpers\Be\Widget\PaginateViewHelper::render() must implement interface TYPO3\CMS\Extbase\Persistence\QueryResultInterface, array given

TypeError thrown in file
...\web\typo3\sysext\fluid\Classes\ViewHelpers\Be\Widget\PaginateViewHelper.php in line 69.
```

**Expected behavior/output**
Backend module view.

**Environment**
- TYPO3 version(s): 8.7.24
- staticfilecache version: 8.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Win10, Linux

**Comment by lochmueller** [comment]
Should be fixed in current master. Please check the change of https://github.com/lochmueller/staticfilecache/blob/master/Classes/ViewHelpers/Be/Widget/PaginateViewHelper.php

**Comment by infabo** [comment]
Hotfix release!

**Comment by lochmueller** [comment]
Hey @infabo 
pushed  8.0.2 a few seconds ago.
Regards,
Tim
