### ISSUE TITLE
ScriptHttpPush matches too much

### ISSUE THREAD

**Issue by infabo** [lochmueller/staticfilecache#145]
## Bug Report

**Current Behavior**
`ScriptHttpPush` matches e.g. `gtm.js`.

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 8.7.24
- staticfilecache version: 8.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
Do not match `.js` files inside `<script>`. Maybe restrict the regex to `href` attributes?

**Additional context**

```html
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XYZ');</script>
```

**Comment by lochmueller** [comment]
Already created a test case for this bug:
https://github.com/lochmueller/staticfilecache/commit/ece94eafbed604756adf5c3e99a0090663a41015
