### ISSUE TITLE
Offline functions

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/staticfilecache#146]
## Feature Request

Integrate Offline Application Caches for more speedup and/or complete offline pages

**Describe the solution you'd like**
New service for resource fetching. New configuration for fallback konfiguration and new mechanism to add the Manifest information

**Teachability, Documentation, Adoption, Migration Strategy**
Website Informations:
- https://t3n.de/news/html5-websites-offline-nutzen-372444/amp/

**Comment by M4rt1n17** [comment]
Habe die Funktion verwendet, jedoch sagt mit Google PageSpeed Insights und Lighthouse dass es nicht funktioniert. 

Fehler:
`Failures: No manifest was fetched.`
`No usable web app manifest found on page.`

Offline Funktion (`Cache Offline (Manifest)`) ist jedoch im Backend unter Einstellungen aktiviert.

Muss ich bei dieser Funktion noch weiteres beachten?

**Comment by lochmueller** [comment]
This function ist not done yet. Will be part of the next major release...

**Comment by M4rt1n17** [comment]
Major release means 9.0 or 8.2/8.3?

**Comment by lochmueller** [comment]
Hey @M4rt1n17 
Will be 9.0 👍

**Comment by Patta** [comment]
Hey @lochmüller, are you shure the t3n source is state of the art? What about the progressive web app stuff? Or do i miss something.

https://docs.pwabuilder.com/
https://www.pwabuilder.com
https://developers.google.com/web/tools/workbox/
https://developers.google.com/web/progressive-web-apps

**Comment by lochmueller** [comment]
PWA is one step further (and I think not the core of StaticFileCache). This "offline functions" feature in StaticFileCache will only generate application manifest files to use the browser application cache to create pages for offline-reading. This should not replace a PWA application. Or do you have more in your head related to a PWA cache integration?

**Comment by Patta** [comment]
ok, sounds good. if i have more ideas for this section, i will file a feature request. big up so far!

**Comment by MartinH0** [comment]
May I ask if the Manifest is already working?#
If so, is there any docu?
Would love to test it.

**Comment by lochmueller** [comment]
Hey @MartinH0 
No... there is not working integration yet. Will be part of StaticFileCache v10 perhaps :)
Regards,
Tim

**Comment by lochmueller** [comment]
I invest a huge amount of time and the topic is very complicated (parser, changeing markup, ....). I dropped this issue! So this is NOT implemented. If there are users who want this feature, fell free to prototyp this function... perhaps the StaticFileCache is als "to late" in the middleware and it is much easier to collection images, css and JS before?!?! Feel free to send pull requests...
