### ISSUE TITLE
TYPO3 8.7 compatibility

### ISSUE THREAD

**Issue by MrMooky** [lochmueller/staticfilecache#15]
Hej there,

unfortunately, the original extension in the TER is not yet 8.7 compatible. I was hoping your fork was, but the backend module does not.

Are you planning on supporting 8.7 fully?

**Comment by lochmueller** [comment]
Hey @MrMooky 
there is no TER version of EXT:staticfilecache. There is only EXT:nc_staticfilecache (with "nc_") in TER.
The new Static File Cache extension (Extension key "staticfilecache") is fully compatible with TYPO3 8.x. Current version is: https://github.com/lochmueller/staticfilecache/releases/tag/5.1.3

I suggest to install the extension via composer (!!!).
Regards,
Tim
