### ISSUE TITLE
PHP warning in backend log

### ISSUE THREAD

**Issue by Patta** [lochmueller/staticfilecache#152]
## Bug Report

**Current Behavior**
The error
`Core: Error handler (BE): PHP Warning: count(): Parameter must be an array or an object that implements Countable in <REMOVED>/private/typo3conf/ext/staticfilecache/Classes/Controller/BackendController.php line 129`
is shown in backend log.

**Expected behavior/output**
No warning in the backend log.

**Environment**
- TYPO3 version(s): 8.7.25 (with helhum/typo3-secure-web)
- staticfilecache version: 8.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux
- PHP version: 7.3.5

**Possible Solution**
#88 

**Additional context**
none

**Comment by lochmueller** [comment]
Fixed in current master.
