### ISSUE TITLE
conflicts with sitemap in 8.1.0 and TYPO3 9.5.6

### ISSUE THREAD

**Issue by bibusdax** [lochmueller/staticfilecache#154]
## Bug Report

**Current Behavior**
For Version 8.1.0 the following url seem to be the same and thus it overwrites the index.html with the sitemap:
https://www.bibusmenos.pl/?type=1533906435
https://www.bibusmenos.pl/

It was quite a nasty surprise to find that about 20% of our root pages were all of a sudden the sitemaps instead of the root page.

**Expected behavior/output**
I expect that URL parameters are included/reflected somehow when creating index.html index.gz index.br

**Environment**
- TYPO3 version(s): 9.5.6 including our own patches
- staticfilecache version: 8.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: CentOS 7 with latest updates

**Possible Solution**
As a temporary solution, I disabled static file cache for all our root pages.
I expect that either static file cache does not cache pages with URL parameters at all or does cache them differently depending on parameters (maybe make that even configurable).

**Additional context**

**Comment by lochmueller** [comment]
`I expect that either static file cache does not cache pages with URL parameters` that should be the case: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/ValidUri.php#L30

 Strange... I will check this in the next days.

**Comment by lochmueller** [comment]
Also the htaccess check the params `RewriteCond %{QUERY_STRING} ^$`.

**Comment by bibusdax** [comment]
Dear Tim,

I checked htaccess and it has that parameter.
In fact when I upgraded to 8.1.0 I replaced the whole section for the static file cache with your reference.

Thank you very much for reverting back to me and have a nice day.
Best regards,

Patrick

**Comment by lochmueller** [comment]
Hey @bibusdax 
I added test cases related to your test case and the extension would not cache a call like this: https://www.bibusmenos.pl/?type=1533906435
Perhaps there are other errors in the configuration? Is there another URI that result in the sitemap.
Please check the test cases and feel free to add more information to this ticket or create a new one if there are more information...
Regards,
Tim
