### ISSUE TITLE
Credentials for protected Domains 

### ISSUE THREAD

**Issue by robsonrobi** [lochmueller/staticfilecache#155]
## Feature Request

I really like your extension. Ist would be cool to provide some credentials when curling in boost-Mode, to her that Extension working on a dev server.

Thank you!

**Comment by lochmueller** [comment]
Good point... I will switch to TYPO3 Core RequestFactory and allow options
https://api.typo3.org/typo3cms/8/html/_request_factory_8php_source.html#l00026

**Comment by robsonrobi** [comment]
In runSingleRequest inside ClientService you can already pass options if you want:
`

            $response = $client->get($url,   [
                'headers' => [
                    'Authorization' => 'Basic ' . base64_encode('user:passwords'),
                ],
            ]);
`

**Comment by lochmueller** [comment]
You are right. But the TYPO3 internal HTTP options are missing in my case. So I will switch to the core API and allow options.

**Comment by robsonrobi** [comment]
@lochmueller : Great ! I am having trouble getting the signal to work. whenever i connect to the signal and process the params the command does not finish. May be you can have a quick look?


$signalSlotDispatcher->connect(
    \SFC\Staticfilecache\Service\ClientService::class,
    'SFC\Staticfilecache\Service\ClientService::getCallableClient',
    \MY\EXT\Signals\HttpClient::class,
    'getCallableClient'
);

`
  \MY\EXT\Signals\HttpClient:


    public function getCallableClient($params) {
        $params['headers']['Authorization'] = 'Basic ' . base64_encode('user:pwd');
        return $params;
    }
`

**Comment by lochmueller** [comment]
Looks ok for me. Do you check the code in the getCallableClient method?

Small note: I will rename the Slot in the next release: https://github.com/lochmueller/staticfilecache/commit/864e3741510c3b043625c55931710097babafbe4 The method is "getCallableClient" and not "SFC\Staticfilecache\Service\ClientService::getCallableClient" in the feature.

**Comment by robsonrobi** [comment]
You can use __FUNCTION__ instead of __METHOD__. 

I will check my function again. Of i do not modify $params, just return Rehm there schould be the same behaviour as before...

**Comment by robsonrobi** [comment]
@lochmueller : Finally i got it working. The strange behaviour was, that i needed two arguments in the function call.

public function getCallableClient($sfcValues, $coreValues) {
       
        $sfcValues['headers']['Authorization'] = 'Basic ' . base64_encode('user:password');
        $params = [
            'sfc' => $sfcValues,
            'core' => $coreValues
        ];
        return $params;
    }

I wondered, why it needed to arguments, because you are dispatching only one array ($params)
