### ISSUE TITLE
No cache-refresh when using startime and endtime of content elements

### ISSUE THREAD

**Issue by robsonrobi** [lochmueller/staticfilecache#156]
## Bug Report

**Current Behavior**
When i have content elements that have set an enndtime for the visibility, running staticfilecache:boostQueueRun does not re-curl the page. Neither the cache-header has a specific time because the page has an element that should reduce the max-age.

**Expected behavior/output**
Setting an endtime on a content_element should change the max-age cache or invalidate in a way the user gets the fresh page afer the content element has expired.

**Environment**
- TYPO3 version(s): [8.7.25]
- staticfilecache version: [8.1.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes, no]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Possible Solution**
Maybe using endtime and starttime for a content-element needs to put an entry into tx_staticfilecache_queue. So the scheduler can refetch the page in boost mode? By the way, the page_uid in that table is for every entry 0?

**Additional context**
---

**Comment by lochmueller** [comment]
I think it is a wrong configuration of your instance. But I will check this. The function "get_cache_timeout" that is used by StaticFileCache should respect start- and endtimes, because the internal function "calculatePageCacheTimeout" (incl. "getFirstTimeValueForRecord") respect this. I will run some tests.

Test-Case:
At 16:00: If there is a content element with a start time "16:15" the cache time should be 15 minutes only.
At 16:00: If there is a content element with a end time "16:15" the cache time should be 15 minutes only.

**Comment by robsonrobi** [comment]
Okay. I just see,i have APCU enabled,may be here is a problem? I am looking forward to hear from you, resulting in the fastest TYPO3 page ever.😉

By the way, do you see any chance to get it to work with nginx? I think, because of the missing ability to put nested config files nginx will not work,Right?

**Comment by lochmueller** [comment]
There is a nginx configuration: https://github.com/lochmueller/staticfilecache/blob/master/Documentation/Configuration/Nginx.rst Please double check the config. I think the port is missing in the path at the moment.

**Comment by robsonrobi** [comment]
You are right, for content elements it is working. Using for example the News Plugin where news objects have an endtime, the Max-Age is not calculated. May be you can implement a signal to check for plugins objects that may have to be recognized? 

And i think we need also starttime to be respected?

**Comment by lochmueller** [comment]
hey @robsonrobi 
that should not be part of the StaticFileCache extension.
I added a small note to the documentation https://github.com/lochmueller/staticfilecache/commit/7de75e3749775008cf4ca40e98f8027c5af1868a / https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#cache

There are missing caching configurations in your TYPO3 installation. Please use config.cache and tags to control the cache in the right way. StaticFileCache is only a "addon" on top of the TYPO3 cache. The TYPO3 Cache have to have clean configuration.

This TYPO3 configuration respect the starttime and endtime: https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#cache

Regards,
Tim

**Comment by robsonrobi** [comment]
Hi @lochmueller. I think, i really missed the cache config. Thanks for mention that. And i am really excited about your reation time. Big thumbs up!

Greetings Robert

**Comment by robsonrobi** [comment]
@lochmueller : Sorry for disturbing you so often. I got everything together now. But i am facing one last problem. I have an importer script, that modifies tx_news objects and sometimes tt_content elements. Is there a way to inform the staticfilecache to put the pages, that hold these objects to the boost queue?

Greetings Robert

**Comment by lochmueller** [comment]
Hey @robsonrobi 
You don't control StaticFileCache by yourself. Just delete the caches of the related pages via caching framework. StaticFileCache will add the Boost Queue items then. I fyou use the DataHandler for the Import-Process TYPO3 will handle even the clear cache process.

"Sorry for disturbing you so often." -> No problem. Feel free to support the development (e.g. with documentation related to the caching topics or financial ;))

Regards,
Tim
