### ISSUE TITLE
RuntimeException Could not create directory 

### ISSUE THREAD

**Issue by christophlehmann** [lochmueller/staticfilecache#158]
## Bug Report

**Current Behavior**

On a bigger site we sometimes get `RuntimeException: Could not create directory` triggered by `mkdir_deep` in https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/StaticFileBackend.php#L67. This is an ugly race condition, but the solution is simple.

**Expected behavior/output**

I expect not to get a 500er while storing data in a cache.

**Possible Solution**

```php
try {
    create dir
    create cache file
} catch this exception {
    silently return
}
```

**Comment by lochmueller** [comment]
Thanks for the note. Fixed in current master. I replace the silent return with error logging.... 👍

**Comment by christophlehmann** [comment]
Looks good, thank you!
