### ISSUE TITLE
random subpage index.html etc. in root of site (TYPO3 9.5.7-patched)

### ISSUE THREAD

**Issue by bibusdax** [lochmueller/staticfilecache#159]
## Bug Report

**Current Behavior**
Random subpages suddenly appear instead of the root page of a site.
With staticfilecache 8.2.0 we have the issue that with a certain probability the index.html of a subpage is written in the root folder of the site causing a subpage instead of the startpage being shown.

**Expected behavior/output**
I expect that the static files of a subpage are strictly written only in the folder of that subpage and that there is a verification making sure not to accidentally write it into the root folder.

**Environment**
- TYPO3 version(s): 9.5.7 with our own patches
- staticfilecache version: 8.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Centos 7.2

**Possible Solution**
I disabled static filecache for the root pages, but that did not help.
Currently I have a bash script checking the root folders and removing index.* every minute.

**Additional context**
I assume that some race condition causes the staticfilecache to forget the path for the static files.
And then it writes them into the root folder of a domain.

**Comment by lochmueller** [comment]
Hey @bibusdax 
sounds strange. That means there are Requests without a Path in the Request URI and TYPO3 handle that as subpage, but staticfilecache as homepage? Do you have a reverse proxy in use? Do you have some more debugging information?
Regards,
Tim

**Comment by bibusdax** [comment]
Dear Tim,
We have a system with about 50 sites in a singly TYPO3 system and with about 35'000 visible pages and about 70'000 pages in the database.
The race condition seems to have weird effects, so I had cases where all of a sudden on a subpage the menu was wrong. But the major problem was that the rootpage index.html, etc. since 8.2.0 was overwritten by some random subpages content.
As we have about 7'000 visitors on our pages in summary and as this randomly happened after several days, that race condition which causes the problem might happen with a chance of 1:5000 to cause problems.
And since our Upgrade to 9LTS (9.5.7 with patches actually) we are fighting several issues of the TYPO3 core in combination with the DKD Solr extensions and some of our own extensions.
So it would just be great, if you could add a safety check in your code. Maybe optionally so that we can enable it in our installation. (e.g. don't cache if empty path segment).
If you want, I can give you access to our system or to a clone thereof.

Thank you very much for your quick reply and best regards,

Patrick

**Comment by lochmueller** [comment]
Hey Patrick,
but how could StaticFileCache decide between a "valid homepage call" and a "invalid missing path call"? I only get the REQUEST_URI and build the cache name based on this. I think there are missing configurtions in your system or strange reverse proxy configurations. I will add some debug logger to the code of the next version. Then you can enable the logging framework to check why this problem exists. But I need some more tecnical (! e.g. logs, click paths, request informations) information to solve the problem.
Regards,
Tim

**Comment by bibusdax** [comment]
Dear Tim,

We do not have a reverse proxy.
We do use Apache on CentOS 7. (I think it is 2.4.7 with some security patches).
Is there no option to check, if the path segment is of zero length ?
We only have this issue since 8.2.0 but we also recently upgraded our TYPO3 from 9.5.6-patched to 9.5.7-patched.
So it is very possible that there are bugs originating from the TYPO3 core itself.
For me some sanity check which just verifies that https://[domain]/ won’t be written, but https://[domain]/[path/<https://[domain]/%5bpath/>] would be saved.

Thank you very much again for your very fast reply.

Best regards,

Patrick Daxboeck
IT-Consultant Web
Certified Web Project Manager

BIBUS HOLDING AG
Allmendstrasse 26
8320 Fehraltorf
Switzerland
Direct   +41 44 877 50 34
Mobile  +41 76 331 00 31
E-Mail   dax@bibus.ch
Internet www.bibus-holding.ch



Von: Tim [mailto:notifications@github.com]
Gesendet: Montag, 27. Mai 2019 08:50
An: lochmueller/staticfilecache
Cc: Daxboeck Patrick; Mention
Betreff: Re: [lochmueller/staticfilecache] random subpage index.html etc. in root of site (TYPO3 9.5.7-patched) (#159)


Hey Patrick,
but how could StaticFileCache decide between a "valid homepage call" and a "invalid missing path call"? I only get the REQUEST_URI and build the cache name based on this. I think there are missing configurtions in your system or strange reverse proxy configurations. I will add some debug logger to the code of the next version. Then you can enable the logging framework to check why this problem exists. But I need some more tecnical (! e.g. logs, click paths, request informations) information to solve the problem.
Regards,
Tim

**Comment by bibusdax** [comment]
Dear Tim,

I have a suspicion.

Case 1:
How will staticfilecache behave if the “default” language of a page is disabled, but the translated versions are enabled ?
Case 2:
How will staticfilecache behave if the superior page is disabled ?
Case 3:
How will staticfilecache behave if the “default” language of the superior page is disabled, but the translated version is enabled ?
Case 4:
How will it behave if the superior page is disabled, but has the same path segment as another enabled page ?

Best regards,

Patrick

Von: Tim [mailto:notifications@github.com]
Gesendet: Montag, 27. Mai 2019 08:50
An: lochmueller/staticfilecache
Cc: Daxboeck Patrick; Mention
Betreff: Re: [lochmueller/staticfilecache] random subpage index.html etc. in root of site (TYPO3 9.5.7-patched) (#159)


Hey Patrick,
but how could StaticFileCache decide between a "valid homepage call" and a "invalid missing path call"? I only get the REQUEST_URI and build the cache name based on this. I think there are missing configurtions in your system or strange reverse proxy configurations. I will add some debug logger to the code of the next version. Then you can enable the logging framework to check why this problem exists. But I need some more tecnical (! e.g. logs, click paths, request informations) information to solve the problem.
Regards,
Tim

**Comment by lochmueller** [comment]
Related to your questsions:

`Is there no option to check, if the path segment is of zero length ?` Yes... I could check this. But if the path is empty it is still a valid URL and also a valid cache entry for the homepage. If I check "path length = 0" the homepage is not cachable anymore?!

`How will staticfilecache behave if the “default” language of a page is disabled, but the translated versions are enabled?` -> `How will staticfilecache behave if the superior page is disabled ?` -> `How will staticfilecache behave if the “default” language of the superior page is disabled, but the translated version is enabled ?` All the same answer: TSFE handle the selection of the enable/disable option because we check it on the TSFE model: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/PageCacheable.php#L28

`How will it behave if the superior page is disabled, but has the same path segment as another enabled page ?` That means there are two pages with the same URL (independent of the caching options)? This case should not exists!

Regards,
Tim

**Comment by bibusdax** [comment]
Dear Tim,

I understand your first objection and we disabled the cache on our root pages to intercept and delete the index.html which were generated there.
As this problem may be specific to our installation, maybe you could just give me a hint how to patch it this way and for now I would just use that patch until we have identified the source of the problem.

About the two pages with the same URL, I agree that this should not be the case, but we had this issue with the old RealURL (I am so glad that we don’t need it anymore !) and when I made the import there were a few cases with either empty or twice the same URL on disabled pages.
Maybe I just should do a database operation to find those doubles and eliminate them, probably the best option.

Anyway thank you very much again for your fast reply.
Will you be at the T3CON in TheHague ?

Best regards,

Patrick


Von: Tim [mailto:notifications@github.com]
Gesendet: Montag, 27. Mai 2019 10:54
An: lochmueller/staticfilecache
Cc: Daxboeck Patrick; Mention
Betreff: Re: [lochmueller/staticfilecache] random subpage index.html etc. in root of site (TYPO3 9.5.7-patched) (#159)


Related to your questsions:

Is there no option to check, if the path segment is of zero length ? Yes... I could check this. But if the path is empty it is still a valid URL and also a valid cache entry for the homepage. If I check "path length = 0" the homepage is not cachable anymore?!

How will staticfilecache behave if the “default” language of a page is disabled, but the translated versions are enabled? -> How will staticfilecache behave if the superior page is disabled ? -> How will staticfilecache behave if the “default” language of the superior page is disabled, but the translated version is enabled ? All the same answer: TSFE handle the selection of the enable/disable option because we check it on the TSFE model: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/PageCacheable.php#L28

How will it behave if the superior page is disabled, but has the same path segment as another enabled page ? That means there are two pages with the same URL (independent of the caching options)? This case should not exists!

Regards,
Tim

**Comment by lochmueller** [comment]
```As this problem may be specific to our installation, maybe you could just give me a hint how to patch it this way and for now I would just use that patch until we have identified the source of the problem.```
You could add a own Rule to the cache, that check this: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Configuration.php#L138 You can register the Rule in your own extension and check the path. So you don't need to patch the extension you can write your own EXT incl. the single rule.
I am not at the T3CON... next event is T3DD and perhaps T3CampHH.
Regards,
Tim

**Comment by bibusdax** [comment]
Dear Tim,

I just had another issue which is connected to the static file cache and probably to the main issue I have.

I have the plugin tx_news on https://www.bibus-sindby.dk/news/seneste-nyheder/

With static file cache enabled, the following happens: I can in the left column select pages, but I am not able to reach page 1 (which goes without the “page/1/” path segment) as that page is always overwritten with the most recently called other subpage.
e.g. If I call https://www.bibus-sindby.dk/news/seneste-nyheder/page/3/ then https://www.bibus-sindby.dk/news/seneste-nyheder/ shows that content.
If I call https://www.bibus-sindby.dk/news/seneste-nyheder/page/21/, then https://www.bibus-sindby.dk/news/seneste-nyheder/ shows that content.
This is a behaviour since the 8.2 upgrade (maybe since 8.1).

with static file cache disabled, this behaviour stops and https://www.bibus-sindby.dk/news/seneste-nyheder/ correctly shows what would be https://www.bibus-sindby.dk/news/seneste-nyheder/page/1/

For me this looks as if:

-          The static file is correctly being written to https/www.bibus-sindby.dk/443/news/seneste-nyheder/page/1/

-          but then also to https/www.bibus-sindby.dk/443/news/seneste-nyheder (one level up)

-          as if the cache files are written twice, once correctly and for some weird reason once somewhere else.

Best regards,

Patrick



Von: Tim [mailto:notifications@github.com]
Gesendet: Montag, 27. Mai 2019 15:45
An: lochmueller/staticfilecache
Cc: Daxboeck Patrick; Mention
Betreff: Re: [lochmueller/staticfilecache] random subpage index.html etc. in root of site (TYPO3 9.5.7-patched) (#159)


As this problem may be specific to our installation, maybe you could just give me a hint how to patch it this way and for now I would just use that patch until we have identified the source of the problem.
You could add a own Rule to the cache, that check this: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Configuration.php#L138 You can register the Rule in your own extension and check the path. So you don't need to patch the extension you can write your own EXT incl. the single rule.
I am not at the T3CON... next event is T3DD and perhaps T3CampHH.
Regards,
Tim

**Comment by lochmueller** [comment]
Hey Patrick,

please delete the (complete) cache. Call the page and run some debugging (!!!) StaticFileCache will not create two cache entries in one request (!!!). I think there are some configuration issues (e.g. language menus, AJAX calls, canonnical tags) that call the page twice.

I will add some debug informationn via logging framework in the next days/weeks.

Regards,
Tim

**Comment by bibusdax** [comment]
Dear Tim,

Did you ever combine staticfilecache with Yoast-SEO for TYPO3 CMS ?
Btw. I did completely clear all caches yesterday, but that did not help.

Today I will do some testing on a fresh clone. Your last e-mail hints towards a collision with Yoast-SEO. The other extension which could collide is DKD-SOLR for TYPO3.

Thank you very much for your feedbacks and best regards,

Patrick

Von: Tim [mailto:notifications@github.com]
Gesendet: Montag, 27. Mai 2019 17:09
An: lochmueller/staticfilecache
Cc: Daxboeck Patrick; Mention
Betreff: Re: [lochmueller/staticfilecache] random subpage index.html etc. in root of site (TYPO3 9.5.7-patched) (#159)


Hey Patrick,

please delete the (complete) cache. Call the page and run some debugging (!!!) StaticFileCache will not create two cache entries in one request (!!!). I think there are some configuration issues (e.g. language menus, AJAX calls, canonnical tags) that call the page twice.

I will add some debug informationn via logging framework in the next days/weeks.

Regards,
Tim

**Comment by bibusdax** [comment]
Dear Tim,

I cloned our live system to perform a series of tests.

1. Removing Yoast: problem persisting.
2. Removing DKD-Solr extensions: problem persisting.
3. Removing "seo" from 9LTS: problem persisting.
4. Removing "div2007": problem persisting.
5. Removing staticfilecache completely and installing 7.1.1: problem gone.
6. Removing staticfilecache completely and changing to 8.0.2: problem gone.
7. Removing staticfilecache completely and changing to 8.1.0: problem gone.
8. Removing staticfilecache completely and changing to 8.2.0: problem gone.
9. Installing DKD-Solr: problem gone.
10. Installing "seo" and Yoast: problem gone.
11. clearing all caches, dumping autoload, etc.: problem still gone.

Now I am cloning again to refine these steps and see, what solves the issue and eventually what causes it.

Indeed 8.2.0 itself does not cause the issue.
I will try to narrow it down. with more tests.

**Comment by lochmueller** [comment]
I saw that yost call the frontend. Perhaps a new Rule is usefull:
```<?php

/**
 * No invalid headers.
 */

declare(strict_types=1);

namespace SFC\Staticfilecache\Cache\Rule;

use TYPO3\CMS\Core\Utility\StringUtility;
use TYPO3\CMS\Extbase\Utility\DebuggerUtility;
use TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController;

/**
 * No invalid headers.
 */
class NoInvalidHeader extends AbstractRule
{
    /**
     * No invalid headers.
     *
     * @param TypoScriptFrontendController $frontendController
     * @param string $uri
     * @param array $explanation
     * @param bool $skipProcessing
     */
    public function checkRule(TypoScriptFrontendController $frontendController, string $uri, array &$explanation, bool &$skipProcessing)
    {
        $headers = getallheaders();
        $invalidHeaders = [
            // Yoast extension
            'X-Yoast-Page-Request',
        ];

        foreach ($invalidHeaders as $header) {
            if (in_array($header, array_keys($headers))) {
                $skipProcessing = true;

                return;
            }
        }
    }
}
```

**Comment by bibusdax** [comment]
Dear Tim,

Next series after a fresh recloning:
1. clearing all caches, dumping autoload, etc: problem persisting.
Note: it did not clear the files in the tx_staticfilecache folder !
2. repeating it, clearing the cached files manually: problem persisting.
3. removing staticfilecache completely, clearing everything, reinstall staticfilecache: problem gone.
4. editing and saving testcase pages: problelm still gone.

**Comment by bibusdax** [comment]
Dear Tim,

finally the following is to note:
If there is a new version of staticfilecache, the extension should be uninstalled, updated, reinstalled.

I also added your new Rule in the code. Thank you very much !
Interestingly uncached pages now render almost twice as fast even if they are still slow.

Thank you very much and best regards,

Patrick Daxboeck

**Comment by MartinH0** [comment]
> Dear Tim,
> 
> finally the following is to note:
> If there is a new version of staticfilecache, the extension should be uninstalled, updated, reinstalled.
> 
> I also added your new Rule in the code. Thank you very much !
> Interestingly uncached pages now render almost twice as fast even if they are still slow.
> 
> Thank you very much and best regards,
> 
> Patrick Daxboeck

I also had a problem back in version 6 with staticfilecache and just clearing the `tx_staticfilecache` folder did the trick. Even if I before tried to `Flush TYPO3 and PHP Cache` and `Remove Temporary Assets`.

I'm now clearing the `tx_staticfilecache` folder every time I update/upgrade it.

**Comment by bibusdax** [comment]
Dear MartinH0,

clearing tx_staticfilecache did not solve that very problem.
Also my problem currently is that I have about 70'000 pages in our TYPO3 CMS and to rebuild all the tx_staticfilecache takes several days over all our subsidiaries subsites.
So I prefer to avoid that.
I have realized that also uncached pages are very slow when they are rendered the first time which does not help with that large amount of pages, too.
So I will dig into the code to see, whether some stuff can be more parallelized in the background, e.g. the various compressions of the index.html files.
Here it would be a benefit, if that is done in separate background processes.
My goal is to bring down the initial page rendering of uncached pages to max 5 seconds.

**Comment by bibusdax** [comment]
clearing all caches and everything during an update is necessary.
I will close this issue now.

**Comment by lochmueller** [comment]
There is already a "uninstall" Hook that run some cleanups: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Hook/UninstallProcess.php But I don't know if there are any "update" hooks in the core. I will check this...
