### ISSUE TITLE
Undefined Constant

### ISSUE THREAD

**Issue by contemas-tschmidt** [lochmueller/staticfilecache#160]
Hi,

there seems to be a "Steuerzeichen" before the 0 
see Notepad++ ANSI encodeing

![2019-05-24_10h58_13](https://user-images.githubusercontent.com/14309291/58316138-2c0c6900-7e13-11e9-931d-ba449d764c14.png)
![2019-05-24_10h58_48](https://user-images.githubusercontent.com/14309291/58316139-2c0c6900-7e13-11e9-9f08-a7d0d9b3da3d.png)
![2019-05-24_11h00_26](https://user-images.githubusercontent.com/14309291/58316140-2ca4ff80-7e13-11e9-92ec-0442e5e599ab.png)

**Comment by lochmueller** [comment]
Thanks for the hint. Fix will be part of the next version.
