### ISSUE TITLE
Unicode Characters (Chinese, Thai, Cyrillic in path segment)

### ISSUE THREAD

**Issue by bibusdax** [lochmueller/staticfilecache#161]
## Bug Report

**Current Behavior**
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1170251401: Could not create directory "/var/www/clients/client1/web1/web/typo3temp/tx_staticfilecache/https/www.bibus.ua/443/ru/novosti/poslednie-novosti/poslednie-novosti/%%D0%%BE%%D0%%B1%%D0%%BD%%D0%%BE%%D0%%B2%%D0%%BB%%D0%%B5%%D0%%BD%%D0%%BD%%D1%%8B%%D0%%B5-%%D0%%BA%%D0%%BE%%D0%%BC%%D0%%BF%%D0%%BB%%D0%%B5%%D0%%BA%%D1%%82%%D1%%8B-%%D0%%B4%%D0%%B8%%D0%%B0%%D1%%84%%D1%%80%%D0%%B0%%D0%%B3%%D0%%BC-%%D0%%B8-%%D0%%BA%%D0%%BB%%D0%%B0%%D0%%BF%%D0%%B0%%D0%%BD%%D0%%BE%%D0%%B2-%%D0%%B4%%D0%%BB%%D1%%8F-%%D0%%BD%%D0%%B0%%D1%%81%%D0%%BE%%D1%%81%%D0%%BE%%D0%%B2-yamada-%%D0%%B4%%D0%%BE%%D1%%81%%D1%%82%%D1%%83%%D0%%BF%%D0%%BD%%D1%%8B-%%D0%%B4%%D0%%BB%%D1%%8F-%%D0%%B7%%D0%%B0%%D0%%BA%%D0%%B0%%D0%%B7%%D0%%B0/page/7/"! | RuntimeException thrown in file /var/www/clients/client1/web1/web/typo3_src-9.5.7-patched/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 2172. Requested URL: https://www.bibus.ua/ru/novosti/poslednie-novosti/poslednie-novosti/%%D0%%BE%%D0%%B1%%D0%%BD%%D0%%BE%%D0%%B2%%D0%%BB%%D0%%B5%%D0%%BD%%D0%%BD%%D1%%8B%%D0%%B5-%%D0%%BA%%D0%%BE%%D0%%BC%%D0%%BF%%D0%%BB%%D0%%B5%%D0%%BA%%D1%%82%%D1%%8B-%%D0%%B4%%D0%%B8%%D0%%B0%%D1%%84%%D1%%80%%D0%%B0%%D0%%B3%%D0%%BC-%%D0%%B8-%%D0%%BA%%D0%%BB%%D0%%B0%%D0%%BF%%D0%%B0%%D0%%BD%%D0%%BE%%D0%%B2-%%D0%%B4%%D0%%BB%%D1%%8F-%%D0%%BD%%D0%%B0%%D1%%81%%D0%%BE%%D1%%81%%D0%%BE%%D0%%B2-yamada-%%D0%%B4%%D0%%BE%%D1%%81%%D1%%82%%D1%%83%%D0%%BF%%D0%%BD%%D1%%8B-%%D0%%B4%%D0%%BB%%D1%%8F-%%D0%%B7%%D0%%B0%%D0%%BA%%D0%%B0%%D0%%B7%%D0%%B0/page/7/ 

**Expected behavior/output**
I would expect it to create a folder which either has "mapped" ASCII-Characters or works with Unicode Characters in the filessystem.

**Environment**
- TYPO3 version(s): 9.5.7-patched
- staticfilecache version: 8.2.0 (with additional Rule)
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Centos 7

**Possible Solution**
make sure that the path goes through PHP rawurldecode()

**Additional context**
-

**Comment by bibusdax** [comment]
diff -Naur /var/www/backup.bibusmail.com/web/typo3conf/ext/staticfilecache/Classes/StaticFileCache.php staticfilecache/Classes/StaticFileCache.php
--- /var/www/backup.bibusmail.com/web/typo3conf/ext/staticfilecache/Classes/StaticFileCache.php 2019-05-15 07:44:50.000000000 +0200
+++ staticfilecache/Classes/StaticFileCache.php 2019-05-29 13:34:12.081494212 +0200
@@ -152,7 +152,7 @@
             }

             // create cache entry
-            $this->cache->set($uri, $content, $cacheTags, $timeOutSeconds);
+            $this->cache->set(rawurldecode($uri), $content, $cacheTags, $timeOutSeconds);
         }

         // Signal: Post process (no matter whether content was cached statically)
@@ -185,7 +185,7 @@
      */
     protected function hasValidCacheEntry($uri): bool
     {
-        $entry = $this->cache->get($uri);
+        $entry = $this->cache->get(rawurldecode($uri));

         return false !== $entry &&
             empty($entry['explanation']) &&

**Comment by bibusdax** [comment]
diff -Naur /var/www/backup.bibusmail.com/web/typo3conf/ext/staticfilecache/Classes/Service/UriService.php staticfilecache/Classes/Service/UriService.php
--- /var/www/backup.bibusmail.com/web/typo3conf/ext/staticfilecache/Classes/Service/UriService.php	2019-05-15 07:44:50.000000000 +0200
+++ staticfilecache/Classes/Service/UriService.php	2019-05-29 14:18:17.388461380 +0200
@@ -36,12 +36,12 @@
             $uri = $this->recreateUriPath($uri);
         }
 
-        $uri = ($isHttp ? 'http://' : 'https://') . \mb_strtolower(GeneralUtility::getIndpEnv('HTTP_HOST')) . '/' . \ltrim($uri, '/');
+        $uri = ($isHttp ? 'http://' : 'https://') . \mb_strtolower(GeneralUtility::getIndpEnv('HTTP_HOST')) . '/' . \ltrim(rawurldecode($uri), '/');
 
         try {
             $idnaConverter = GeneralUtility::makeInstance(IdnaConvert::class);
 
-            return $idnaConverter->encode($uri);
+            return $idnaConverter->encode(rawurldecode($uri));
         } catch (\InvalidArgumentException $exception) {
             // The URI is already in puny code (no logging needed)
             return $uri;
@@ -67,7 +67,7 @@
         if (null === ObjectAccess::getProperty($uriBuilder, 'contentObject', true)) {
             // there are situations without a valid contentObject in the URI builder
             // prevent this situation by return the original request URI
-            return $uri;
+            return rawurldecode($uri);
         }
         $url = $uriBuilder->reset()
             ->setAddQueryString(true)
diff -Naur /var/www/backup.bibusmail.com/web/typo3conf/ext/staticfilecache/Classes/StaticFileCache.php staticfilecache/Classes/StaticFileCache.php
--- /var/www/backup.bibusmail.com/web/typo3conf/ext/staticfilecache/Classes/StaticFileCache.php	2019-05-15 07:44:50.000000000 +0200
+++ staticfilecache/Classes/StaticFileCache.php	2019-05-29 14:15:51.917891808 +0200
@@ -75,7 +75,7 @@
     {
         $isStaticCached = false;
 
-        $uri = GeneralUtility::makeInstance(UriService::class)->getUri();
+        $uri = rawurldecode(GeneralUtility::makeInstance(UriService::class)->getUri());
 
         // Signal: Initialize variables before starting the processing.
         $preProcessArguments = [
@@ -83,7 +83,7 @@
             'uri' => $uri,
         ];
         $preProcessArguments = $this->dispatch('preProcess', $preProcessArguments);
-        $uri = $preProcessArguments['uri'];
+        $uri = rawurldecode($preProcessArguments['uri']);
 
         // cache rules
         $ruleArguments = [
@@ -141,7 +141,7 @@
                 );
                 $content = $contentArguments['content'];
                 $timeOutSeconds = $contentArguments['timeOutSeconds'];
-                $uri = $contentArguments['uri'];
+                $uri = rawurldecode($contentArguments['uri']);
                 $isStaticCached = true;
 
                 $tagService->send();
@@ -152,7 +152,7 @@
             }
 
             // create cache entry
-            $this->cache->set($uri, $content, $cacheTags, $timeOutSeconds);
+            $this->cache->set(rawurldecode($uri), $content, $cacheTags, $timeOutSeconds);
         }
 
         // Signal: Post process (no matter whether content was cached statically)
@@ -185,7 +185,7 @@
      */
     protected function hasValidCacheEntry($uri): bool
     {
-        $entry = $this->cache->get($uri);
+        $entry = $this->cache->get(rawurldecode($uri));
 
         return false !== $entry &&
             empty($entry['explanation']) &&

**Comment by bibusdax** [comment]
Dear Tim,

the diff-file above is overkill, but fortunately you can cascade rawurldecode() without problems.
And on my sites the problem with Unicode-URLs is solved now.

Best regards,

Patrick

**Comment by lochmueller** [comment]
Hey @bibusdax
this are "many places". Could you check if the logic could be centralize and configurable?
Regards,
Tim

**Comment by bibusdax** [comment]
Dear Tim,

I modified Classes/StaticFileCache.php and Classes/Service/UriService.php

UriService.php:
getUri()
- make sure that the returned $uri has passed through rawurldecode()
- here the part return $idnaConverter->encode(rawurldecode($uri)); is very important. This makes sure that there is no double encode, which was the original problem I faced.
recreateUriPath($uri)
- here the instance of rawurldecode may be unnecessary.

StaticFileCache.php:
insertPageInCache($pObj, $timeOuttime)
- first rawurldecode() is unnecessary as getUri() already returns decoded uri.
- second rawurldecode() is unnecessary, too.
- same goes for the third rawurldecode().
- fourth one is important: $this->cache->set(rawurldecode($uri), $content, $cacheTags, $timeOutSeconds); // this will cause the cache to be written to a clean filename in Punycode.
hasValidCacheEntry($uri)
- this one is important: $entry=$this->cache->get(rawurldecode($uri));

Summary:
The rawurldecode() function is very important in general.
Some browsers deliver the pure URL in Unicode and some browsers already deliver an encoded version.
In consequence when the encode function is being called, there are cases of double encode. (encode should not be cascaded !)
If every URI is passed through rawurldecode(), that case can be avoided.
With rawurldecode() before the actuall writes and reads of the cache, the foldernames are in Punycode which works with least issues as the filesystem can be ASCII, UTF-8, WIN1252 or whatever.

Best regards,

Patrick

**Comment by lochmueller** [comment]
Hey @bibusdax 
Could you send me a pull request for the changes?
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @bibusdax ,
fixed in the next release. V10 are based on the Middleware and Serverrequest. The URI in the request is normalized. So the only location that need a "rawurldecode" call is the generation of the cache file name. So I add a option "rawurldecodeCacheFileName" that trigger the "rawurldecode" in the path generation.
Regards,
Tim
