### ISSUE TITLE
[FEATURE] Priority in Queue

### ISSUE THREAD

**Issue by bernhardberger** [lochmueller/staticfilecache#162]
As we have a few sites with several thousand pages it would be nice if it was possible to prioritize pages in the Queue. 

Could be a simple dropdown or numeric text field in the `pages` table / form, priority gets written into the queue on generation and sorted by priority in the queue runner.

I think it would be a good way to improve effectiveness for cache regeneration. What do you think about it?

**Comment by cheindl** [comment]
I agree: we also have some use cases, where we would like to refresh pages in a specific order, to ensure important pages get up-to-date renderings quicker than others (even if they have same cache lifetime).

**Comment by lochmueller** [comment]
First steps are in git. Function will be part of the next release...

**Comment by lochmueller** [comment]
Hey guys... is part of the current master and will be in the 9.x release.
