### ISSUE TITLE
Collision of /index.html with /?type=1533906435 (sitemap)

### ISSUE THREAD

**Issue by bibusdax** [lochmueller/staticfilecache#166]
## Bug Report

**Current Behavior**
When I clear the caches and then call e.g. www.bibus.de and then www.bibus.de/sitemap.xml
(which calls https://www.bibus.de/?type=1533906435)
I get an error message as the index.html[.gz|.br] are overwritten somehow with the sitemap
The error appears in Mozilla Firefox and not in Google Chrome.

**Expected behavior/output**
I expect the pagetype to be intercepted and not written as index.html

**Environment**
- TYPO3 version(s): 9.5.7 with patches
- staticfilecache version: 8.2.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: CentOS

**Possible Solution**
I am checking whether I can adjust the config.yaml of the domain to avoid this issue

**Additional context**
avoid type parameter to overwrite index.html

**Comment by bibusdax** [comment]
I found a solution via .htaccess

#Sitemap
RewriteEngine On
RewriteCond %{QUERY_STRING} type=1533906435
RewriteCond %{QUERY_STRING} !no_cache=1
RewriteRule ^(.*)$ $1/?no_cache=1&%{QUERY_STRING} [R,L=301]

RewriteRule ^sitemap\.xml$ /?no_cache=1&type=1533906435 [R,L]
RewriteRule ^(.*)/sitemap\.xml$ /$1/?no_cache=1&type=1533906435 [R,L]

**Comment by lochmueller** [comment]
Hey @bibusdax ,
problem will solved with this changes: https://github.com/lochmueller/staticfilecache/commit/d29cfa5cdf4d8e8c707a7b0d0671fa5025f5e8e8
In the next release every URL get a folder incl. a "index" file with the content. So there is no difference between "html" and "xml" output. This should solve the problem of conflicts and there is no "index.html" anymore for a XML file.
Regards,
Tim
