### ISSUE TITLE
Add possibility to setup the scheduler task in TYPO3 version 8

### ISSUE THREAD

**Issue by clausharup** [lochmueller/staticfilecache#168]
It is not possible to add i.e. RemoveExpiredPages Command in the scheduler in TYPO3 v. 8 - it was possible in the previous version this brillant extension :-)

**Comment by lochmueller** [comment]
I will readd the old scheduler tasks again: https://github.com/lochmueller/staticfilecache/commit/45221fab2e39798807df3efe6eea2064e92f9c2e
