### ISSUE TITLE
Page saving takes sometimes an hour

### ISSUE THREAD

**Issue by webfacer** [lochmueller/staticfilecache#173]
Hi,
i have an issue where we activate the boost mode and enabled the queue how described in the docs. But when "Boos Mode" is enabled it slows down the performance of the Pagesaving and i do not now why.
What i can say if one page is saved it save a bunch of items in the queue. The queue has then more than 1000 items to execute instetad of one page and some coentent elements.

does we forgot to set something or does the boos queue has a bug?

**Comment by lochmueller** [comment]
Hey @webfacer 
sounds strange. 1.000 items are not many. The queue add all items that are triggerd via the cache hooks of TYPO3. That means, if you use e.g. `clearCacheCmd = all` (please: do not use this!!!) the cache of the complete webpage is cleared on every save. But adding the items to the queue is very fast (that is the reason, why we use the queue), but please keep in mind, that all the TYPO3 caches are also truncated.
At the moment this are only speculation or a feeling :-/ ... do you run some debugging or do you have a call-graph of the save process (blackfire.io, cachegrind)?
Regards,
Tim

**Comment by lochmueller** [comment]
More information in Slack.
