### ISSUE TITLE
Support for different content-types

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/staticfilecache#176]
## Feature Request

e.g. the static route to "robots.txt" is renderd with "text/plain", but if StaticFileCache is deliverd the type is "text/html".

Workarround: config.tx_staticfilecache.disableCache = 1 for the single typeNum

**Comment by Nemo64** [comment]
This already kind-of™ works.

I have set `fileTypes` to an empty string and set `sendTypo3Headers` to `1`.
Now your extension creates a structure like `/sitemap.xml/index.html.gz` with a htaccess file containing `Header set Content-Type "application/xml;charset=utf-8"`. This works fine.

**Comment by lochmueller** [comment]
Hey @Nemo64 
I add this feature for the new Middleware Handling... if the extension switch completly to Middleware in the future... such features/functions are much more simple to handle.

**Comment by Nemo64** [comment]
I'm not sure I like complete middleware handling.
The performance boost currently comes from php not being involved at all.
If this cache runs in php, why even have it at all over the normal typo3 cache? (yes you still save one database connection, i know)

**Comment by lochmueller** [comment]
Yes. I talked about the generation process. At the moment it is a TSFE Hook. But in the new Middleware stack it is much smarter because we can support other extensions/features easily (like http Reponse header support). It still generate a static file and the file is called without PHP.

Note: Do not mix it up with the "Fallback Middleware". This middleware deliver the cache, if the file exists and the .htaccess don't redirect in the right way.
