### ISSUE TITLE
Info module broken?

### ISSUE THREAD

**Issue by Nemo64** [lochmueller/staticfilecache#18]
If I access the info module in the typo3 backend, i get a fluid error.
![bildschirmfoto 2017-08-23 um 15 34 31](https://user-images.githubusercontent.com/1749936/29618481-91871282-8818-11e7-99f6-e163c1e6cfad.png)

**Comment by lochmueller** [comment]
Hey @Nemo64 
which TYPO3 version and which StaticFileCache version?
Regards, Tim

**Comment by Nemo64** [comment]
Ok, so basically, the c namespace isn't defined. A definition like `{namespace c=TYPO3\CMS\Core\ViewHelpers}` fixes that. I'm currently busy but i'll see if i can make a pull request.

Typo3 Version 8.7.4
Static file cache 5.1.3
Both just installed.

**Comment by lochmueller** [comment]
Fixed... i switch to "core". This is registerd in the default configuration for the ViewHelper of the core Extension. Thanks for reporting...
![bildschirmfoto 2017-08-23 um 15 46 11](https://user-images.githubusercontent.com/3907126/29619036-33c14e5e-881a-11e7-8dd7-65d634665998.png)

**Comment by lochmueller** [comment]
And released: https://github.com/lochmueller/staticfilecache/releases/tag/5.1.4
