### ISSUE TITLE
Using staticfilecache togehter with helhum/typo3-secure-web

### ISSUE THREAD

**Issue by einpraegsam** [lochmueller/staticfilecache#180]
If I try to use staticfilecache together with helhum/typo3-secure-web there is a small problem.
Because html files are stored in typo3temp/tx_staticfilecache/ and because typo3-secure-web only symlinks private/typo3temp/assets/ to public/typo3temp/assets/ for security reasons the HTML-files are not deliverable via .htaccess. (Note documentRoot is public/ and not private/).

Did you already use your extension with helhum/typo3-secure-web? Any hints how to configure staticfilecache for this szenario?

In my eyes there are 3 possibilities:
- HTML files should be stored in typo3temp/assets/
- typo3temp/tx_staticfilecache/ should be symlinked form secure web
- or the .htaccess configuration can be changed that html files are used from ../private/typo3temp/tx_staticfilecache/ (feels like the best solution)

Newest TYPO3 8.7, staticfilecache 9.0.0 and latest typo3-secure-web

**Comment by lochmueller** [comment]
Hey @einpraegsam 
do you try https://github.com/lochmueller/staticfilecache/blob/master/ext_conf_template.txt#L40 by setting it to `typo3temp/assets/tx_staticfilecache/` and adapt the .htaccess file?
Regards,
Tim

**Comment by einpraegsam** [comment]
Thx, I did not saw this setting. Are absolute paths or paths with ../ possible?
Would be `../private/typo3temp/tx_staticfilecache/`

**Comment by lochmueller** [comment]
Hm... I don't try this ;) But should work... 👍

**Comment by einpraegsam** [comment]
Now we modified the deployment to set another symlink. Another possibility would be to set the typo3temp/assets/anyfolder - that would work.
Thx

**Comment by lochmueller** [comment]
Yes... I reopen the issue as notice for a FAQ entry for the docs ;)
