### ISSUE TITLE
Slowdown on saving a Page

### ISSUE THREAD

**Issue by webfacer** [lochmueller/staticfilecache#183]
I have an issue when i save an Article or a Content Element it takes several times (up to one minute) until it is finished.

When running `/usr/bin/php /var/www/html/typo3/sysext/core/bin/typo3 staticfilecache:boostQueueRun` it calls more than once this method every minute. Its oki because it is setted to every minute but, this command shouldn´t stack i think. If i look at htop every minute one more command of `/usr/bin/php /var/www/html/typo3/sysext/core/bin/typo3 staticfilecache:boostQueueRun`is called. shouldn´t it check if it is already running.

sorry for my english please tell if something is unclear.

**Comment by lochmueller** [comment]
Solved via Slack.
