### ISSUE TITLE
[Question] about "Boost mode"

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#185]
When I activate Boost mode, will this automatically implement/activate the cronjob which will add all the old pages to the queue, or do I have to do this manually?
Does the extension "scheduler" (german "Planer") have to be installed?

Just curious as there is just mentioned "there is a scheduler task"
![static_cache](https://user-images.githubusercontent.com/17692860/65808773-d536e780-e196-11e9-9e5e-f00668f25fe5.PNG)

Best regards,
Martin

**Comment by lochmueller** [comment]
Hey @MartinH0 
You have to install the core extension scheduler. Based on TYPO3 and StaticFileCache version you find the StaticFileCache Tasks in the "Extbase CommandController" or in the "Symfony Commands" task as subtasks. Please configure the scheduler itself with crontab an your server. You have to do this process manually.
Does this solve this problem?
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @MartinH0 I close this issue... if there are more questions or feedback for a "more clear description/documentation" Feel free to reopen the issue or get in contact with me via Slack. Regards, Tim
