### ISSUE TITLE
Weird random bug

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#186]
## Bug Report

**Current Behavior**
I have 2 TYPO3 v9 installations.
One runs on SFC v6.1.2, the other on v10.0.0-dev (also tested it on v9.0.0)

## **v9.0.0 & v10.0.0-dev**
When I open the dev console in Chrome and reload my page immediately after it  loaded and do this about 5-10 times I notice that sometimes the responsetime is not about 30ms its more about 170-250ms which is much more. And noticable in the frontend.

I also doublechecked my htaccess but its fine.

## **v6.1.2**
Here, no matter how often I reload I always get responstimes (TTFB) about 30-40ms which is perfect!

What is also different in these two installations:
The one which runs v10.0.0 is in boost-mode. The other not.
The one which runs v10.0.0 does have a cache_period = 3600 (1h) the other one with 604800 (1w) but this shouldnt matter as this "bug" happens like every second.

**Expected behavior/output**

**Environment**
- TYPO3 version(s): TYPO3 v9.5.9
- staticfilecache version: 6.1.2, 9.0.0 & 10.0.0-dev

**Comment by lochmueller** [comment]
So.... version 6.1.2 I will not check anymore. For the other problem... I added debug headers via configuration. Please update to the current master commit, enable the debug headers ( https://github.com/lochmueller/staticfilecache/blob/master/ext_conf_template.txt#L11 ) and check the output of the "X-SFC-State" header:
- TYPO3 - add to cache (First request. Added the result to the cache)
- TYPO3 - no cache (Page is not cachable, check the backend module)
- TYPO3 - already in cache (There is a cache entry, but htaccess and Fallback middle cannot handle the request)
- StaticFileCache - via Fallback Middleware (there is a cache entry, but your htaccess seems to be wrong!)
- StaticFileCache - via htaccess (perfect!!!)

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @MartinH0 
if the problem still exists (note: Please use current master!), please check the headers and reopen the issue with more tecnical information...
Regards,
Tim
