### ISSUE TITLE
Cron "staticfilecache:flushCache" does not work in Bootst-Mode

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#188]
## Bug Report

**Current Behavior**
I run a Cron which executes the "staticfilecache:flushCache" Symfony Command but the Cache does not get Flushed.

I also tried to flush the cache manually with ckearing the Frontend and Backendcache but this also did not clear (or in this case regenerate) the Files even if the description clearly says "If the boost mode is active, all pages are recrawlt" but it does not work.

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 9.5.9
- staticfilecache version: 10.0.0-dev

**Comment by lochmueller** [comment]
Hey @MartinH0 
I fixed the task description.
Regards,
Tim
