### ISSUE TITLE
".gz" gets generated in TYPO3 root-folder

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#189]
## Bug Report

**Current Behavior**
Maybe this is not a bug but a side-effect.
After playing around a bit with the configuration I noticed there is a new File in the TYPO3 root-Folder called ".gz" actually I just opened it and saw its the gzip version of the rootpage (same file as index.gz)

So I just deleted it and called the Page again and it worked like befor. This file seems to be unnecessary sadly I could not reproduce how the file got created. But I hope you know why :)

**Environment**
- TYPO3 version(s): 9.5.9
- staticfilecache version: 10.0.0-dev

**Comment by lochmueller** [comment]
Hmm... sounds strange. I added a check for the path, so this should throw a exception now.

**Comment by MartinH0** [comment]
I changed the settings to:

Hash URI (BETA!!!): [X]

After this I noticed the File but could also come from another setting.
