### ISSUE TITLE
Optimization of htaccess

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#191]
# Feature Request

**Describe the solution you'd like**
As the htaccess is kind of "slow" under certain circumstances it could be optimized.
Reffering to: http://thomaslohner.github.io/slides/Performance-Myths/#/6/4

htaccess is getting slower the more it have to go deeper in the Filesystem. So to optimize it we should avoid saving the Cache to deep in the folder structure on the Server.

**Describe alternatives you've considered**
As TYPO3 does not differenciate between a call from "https" and "http" thios should neither be checked nor be created.

In the TYPO3 Backend we just set up a Domain. For Example "www.domain.tld"

SFC then creates (in our case) these Cache-Directories:

/typo3temp/tx_staticfilecache/**https**/www.domain.tld/**443**/[CACHED_FILES]
/typo3temp/tx_staticfilecache/**http**/www.domain.tld/**80**/[CACHED_FILES] (if we can call the Domain at http)

(They are both in the **6th Subfolder**)

And the Cache itself will be the same. For me this is completely unnecessary and doubled:

1. "https" means Port "443" (at least at websites!)
2. "http" means Port "80" (at least at websites!)

So at least the Scheme (https or http) or the Port (443 or 80) is unneccassary, but I even think they are both not needed in any case!

For me this Part of the htaccess is "to much":

```
# Get scheme
RewriteRule .* - [E=SFC_PROTOCOL:http]
RewriteCond %{SERVER_PORT} ^443$ [OR]
RewriteCond %{HTTP:X-Forwarded-Proto} https
RewriteRule .* - [E=SFC_PROTOCOL:https]

# Get port
RewriteRule .* - [E=SFC_PORT:80]
RewriteCond %{ENV:SFC_PROTOCOL} ^https$ [NC]
RewriteRule .* - [E=SFC_PORT:443]
RewriteCond %{SERVER_PORT} ^[0-9]+$
RewriteRule .* - [E=SFC_PORT:%{SERVER_PORT}]
RewriteCond %{HTTP:X-Forwarded-Port} ^[0-9]+$
RewriteRule .* - [E=SFC_PORT:%{HTTP:X-Forwarded-Port}]
```

Without this part the Cache Folder would look like this:

/typo3temp/tx_staticfilecache/www.domain.tld/[CACHED_FILES]

(The Cache not would be in the **4th Subfolder!**)

and this for every scheme and every port which makes absolutely sense as you cant configurate two different websites in TYPO3 with the same FQDN (in the htacces its the "HTTP_HOST")

I know this is not a lot of performance gain but I think it makes the whole thing:

1. better structured
2. with less htacces rules
3. folderstructure less deep by "2 Folders" which will also gain a more performance.

If I'm wrong about the TYPO3 System is not able to register a FQDN twice please correct me but at least for what I understand TYPO3 does not differenciate between http and https it just sees the Domain itself.

## Step 2

Related to http://thomaslohner.github.io/slides/Performance-Myths/#/8

Maybe it would be good also provide a htacces which people can paste into their "vhost.config" as this is again much faster then rewriting with the htaccess.

Would at least love to test this!

**Comment by lochmueller** [comment]
Hey @MartinH0 
good point.
I created a combined identfier for scheme, host and port. So the information isn't lost and we reduce the structure (2 levels). Th einformation are important, because the relation "https -> 443" and "http -> 80" are only the default ports and Staticfilecache take care, that http://www.page.de and http://www.page.de:8080 result in different versions of the output. But I think the combined identifier is a good way.
Step 2: It is possible to place the rules of the root configuration in you vhost config. But each cache entry has a own htaccess file (this logic could not be static in a configuration like vhosts).
Regards,
Tim
