### ISSUE TITLE
Path of static file

### ISSUE THREAD

**Issue by SventB** [lochmueller/staticfilecache#195]
The generated static file is stored in a directory like this:
`typo3temp/tx_staticfilecache/https/mydomain/443/my/path/`

But in your htaccess example (https://github.com/lochmueller/staticfilecache/blob/master/Documentation/Configuration/Htaccess.rst) you write the path with underscore:
`RewriteRule .* - [E=SFC_FULLPATH:typo3temp/tx_staticfilecache/%{ENV:SFC_PROTOCOL}_%{ENV:SFC_HOST}_%{ENV:SFC_PORT}%{ENV:SFC_URI}/index]`
so the server looks for the file at
`typo3temp/tx_staticfilecache/https_mydomain_443/my/path/index`

The file ending (.html) also seems to be missing in the htaccess example.

**Comment by lochmueller** [comment]
Hey @SventB 
If you are using 9.0.0 please use the documentation for version 9:
https://github.com/lochmueller/staticfilecache/blob/9.0.0/Documentation/Configuration/Htaccess.rst
The Current master documentation is only usefull if your are using the current master ;)
I close this issue...
Regards,
Tim

**Comment by SventB** [comment]
Ok, thank you for your quick answer and the hint.
I thought version 9.0.0 is the master branch, but version 10.0.0-dev is master.
