### ISSUE TITLE
Static files aren't created until saving extension manager configuration

### ISSUE THREAD

**Issue by SventB** [lochmueller/staticfilecache#196]
After I did everything described in the documentation, just a folder with an empty htaccess file was created, with no index.html.
After I saved the configuration of the extension in the extension manager, it worked as expected. You should add a hint for that here: https://github.com/lochmueller/staticfilecache/blob/master/Documentation/Installation/Index.rst

**Comment by lochmueller** [comment]
In the next version the configuration is checkt and throw a speaking exception if the extension configuration is missing. I suggest to install packacges via CLI or run typo3_console `extension:setupactive` in your deployment/development process.
