### ISSUE TITLE
PHP warnings  Illegal string offset

### ISSUE THREAD

**Issue by bdpfreizeiten** [lochmueller/staticfilecache#198]
Hello,

i get some PHP warnings after updating to the newes version:

 PHP Warning: Illegal string offset 'tx_staticfilecache_cache_force' in ext/staticfilecache/Classes/Cache/Rule/ForceStaticCache.php line 77 
PHP Warning: Illegal string offset 'tx_staticfilecache_cache' in ext/staticfilecache/Classes/Cache/Rule/PageCacheable.php line 29 
 PHP Warning: Illegal string offset 'doktype' in ext/staticfilecache/Classes/Cache/Rule/ValidDoktype.php line 41 

**Environment**
- TYPO3 version(s): 9.5
- staticfilecache version: 10.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by angeloprevitali** [comment]
I got the same problem, too.

**Comment by lochmueller** [comment]
Already fixed in current master. I will push 10.0.1 in a few seconds.
