### ISSUE TITLE
Pages cached but not delivered cached

### ISSUE THREAD

**Issue by bh-teufels** [lochmueller/staticfilecache#199]
## Bug Report

**Current Behavior**
According to the backend, all pages can be cached.
But sometimes sites delivered cached and sometimes not (Same pages).
occurs mostly at generated pages. 
It seems that amount of X pages is cached and on open Page X+1 this page will be (new)cached and another will be removed from cache

**Expected behavior/output**
All Sites should be delivered form cache.

**Questions**
Is there a limit like maximum number of cached pages?
I tried also the boost-mode but no changes in behavior

**Environment**
- TYPO3 version(s): 8.7.27
- staticfilecache version: 9.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

Thank you very much for your help

**Comment by lochmueller** [comment]
yes & yes 👍

**Comment by lochmueller** [comment]
I close this issue. If you upgrade to SFC v10 you will benefit from smarter debug headers to check the HIT-MISS-ratio...
