### ISSUE TITLE
[BE] Cache entries displayed on parent node

### ISSUE THREAD

**Issue by No5251** [lochmueller/staticfilecache#20]
See title and screenshot. Applies to all pages. Cache entries of root pages are displayed on ID 0.

![staticfilecache](https://user-images.githubusercontent.com/468954/29866369-7ef95412-8d78-11e7-956a-4377f169d7b5.png)

**Comment by lochmueller** [comment]
Hey @No5251 
I don't understand the problem. Could you run some debugging? If your URL configuration is wrong and render the homepage on wrong URLs then StaticFileCache create wrong Cache records for the URLs. But this is not a SFC problem. 
Regards,
Tim

**Comment by No5251** [comment]
Hi Tim,
pages get rendered and cached. It's just a minor mistake that could confuse some people. In my screenshot "Home" is selected, but SFC shows the cache info for the subpage(s).
Kind regards,
Marco

**Comment by lochmueller** [comment]
Hey @No5251 
You are right. But I think the functionality is ok, but the description in the top ist wrong.
I will addapt the description in the next commit..
Regards,
Tim
