### ISSUE TITLE
EXT:solr indexing problem, while SFC enabled

### ISSUE THREAD

**Issue by jackd248** [lochmueller/staticfilecache#200]
## Bug Report

**Current Behavior**
The combination of EXT:staticfilecache and EXT:solr leads to the problem, that the solr indexer encounters errors, while trying to index cached pages. It isn’t possible to index cached pages, because of the detection of user/group restrictions. Here is an example output in the solr log:
```
[ERROR] request="e61cd3af138d7" component="ApacheSolrForTypo3.Solr.IndexQueue.PageIndexerRequest": Failed to execute Page Indexer Request. Request ID: 5d973b8d71d98 - {"request ID":"5d973b8d71d98","request url":"https://example.com/hochschule/aktuelles","request headers":["User-Agent: TYPO3","X-Tx-Solr-Iq: {\"requestId\":\"5d973b8d71d98\",\"item\":142433,\"page\":3,\"actions\":\"findUserGroups\",\"hash\":\"acf21104ba692cc9e35ef11f74991ab4\",\"loggingEnabled\":\"0\"}"],"response headers":{"Date":["Fri, 04 Oct 2019 12:31:09 GMT"],"Server":["Apache"],"Last-Modified":["Fri, 04 Oct 2019 12:17:05 GMT"],"Accept-Ranges":["bytes"],"Content-Length":["137427"],"Vary":["Accept-Encoding"],"Cache-Control":["max-age=85555"],"Expires":["Sat, 05 Oct 2019 12:17:05 GMT"],"Strict-Transport-Security":["max-age=31536000"],"X-UA-Compatible":["IE=edge"],"X-Content-Type-Options":["nosniff"],"X-Cache":["StaticFileCache"],"Content-Type":["text/html; charset=utf-8"]},"raw response body":""}
```

**Expected behavior/output**
The solr indexer should work with the SFC without problems. 

**Environment**
- TYPO3 version: 9.5.9
- staticfilecache version: 9.0.0
- EXT:solr version: _dev-master_ (because of the site handling compatibility)
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
The idea was to redirect the request of the solr indexer (with his custom header) in the _.htaccess_ to bypass the static files.

**Comment by jackd248** [comment]
Actually I'm not sure **why** this problem appears, but the redirect solution works for me so far. So I place the following line near to the _SFC_HOST_ variable declaration in the .htaccess file to bypass the SFC of the solr specific request.
```
# Disable cache for EXT:solr indexing requests
RewriteCond %{HTTP:X-Tx-Solr-Iq} .+
RewriteRule .* - [E=SFC_HOST:invalie]
```

**Comment by MartinH0** [comment]
I dont know iof this helps but maybe updating SFC to at least version 9 (or 10) would be good as there are a lot of fixed/changes.

Also pls keep in mind that I think that version 4 will not be supported anymore.
I think Version 8, 9 & 10 are supported but as there is no roadmap noone knows exactly but version 4 is not supported!

Pls update, check if the problem persists and if so report back

**Comment by jackd248** [comment]
I'm sorry, I was using Version 9.0.0. This was just a typo. But I can try the new Version 10. Thanks for the hint.

**Comment by lochmueller** [comment]
Hmm... special request headers havee to checked in the htaccess. I added the lines to the htaccess default configuration.

**Comment by jackd248** [comment]
Thanks! 👍

**Comment by akoenig-clickstorm** [comment]
The same issue occures when "Use fallback middleware" is activated. As a workaround you have to use the current htaccess rules and disable "Use fallback middleware" when you want to use SOLR indexing on a cached page.

Software: 
- TYPO3 9.5.23
- StaticFileCache 11.1.7
- SOLR: 11.0.3

**Comment by lochmueller** [comment]
Should we add a blacklist configuration for the headers of the Fallback-Middleware? Please create a new issue if you think this solves the problem?!?

**Comment by lochmueller** [comment]
Fixed in current master with a separate Fallback check for the Solr header.
