### ISSUE TITLE
starttime and endtime of content elements not working

### ISSUE THREAD

**Issue by breakone** [lochmueller/staticfilecache#207]
### Current Behavior ###
I added a content element with a enddate on a page:

![Bildschirmfoto 2019-10-24 um 12 19 03](https://user-images.githubusercontent.com/4848121/67476587-96426780-f658-11e9-8634-be33d71b616b.png)

The cache entry is generated as expected:

![Bildschirmfoto 2019-10-24 um 12 17 16](https://user-images.githubusercontent.com/4848121/67476627-ad815500-f658-11e9-9076-0c0f27de5d11.png)

The first call creates this cache:

![Bildschirmfoto 2019-10-24 um 12 17 54](https://user-images.githubusercontent.com/4848121/67476742-e4f00180-f658-11e9-8c50-4725a9a08e5b.png)

![Bildschirmfoto 2019-10-24 um 12 18 06](https://user-images.githubusercontent.com/4848121/67476767-f507e100-f658-11e9-8f0a-968cfb8391ff.png)

### Expected behavior/output ###
Get a fresh page after the enddate of the content element without the element and recreate the cache instead of getting the cached file:

![Bildschirmfoto 2019-10-24 um 12 24 13](https://user-images.githubusercontent.com/4848121/67476935-4b751f80-f659-11e9-8096-ccd840f468e7.png)

### Environment ###
- TYPO3 version(s): 9.5.10
- staticfilecache version: master
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 10.14.2
- PHP: 7.3.9
- ddev: 1.11.1

### Additional context ###

**The content of the htaccess file:**

```
<IfModule mod_expires.c>
	ExpiresActive on
	ExpiresByType text/html M181
</IfModule>


<IfModule mod_rewrite.c>
	RewriteEngine On
	
	RewriteCond %{ENV:REDIRECT_STATUS} ^$
	RewriteRule .* - [F,L]

	RewriteCond {TIME} >20191024122002
	RewriteRule ^.*$ /index.php
</IfModule>



	<ifModule mod_headers.c>
		
				Header set Content-Type "text/html; charset=utf-8"
		
				Header set Content-Language "de"
		
				Header set X-SFC-Tags "pageId_1, sfc_pageId_1, sfc_domain_typo3-9_ddev_site"
		
				Header set Link "</typo3temp/assets/compressed/merged-cb65c3e90fb524f8669e205afcd6544f-min.css.gzip?1571725907>; rel=preload; as=style, </typo3conf/ext/dp_cookieconsent/Resources/Public/css/cookie.min.css>; rel=preload; as=style, </typo3temp/assets/compressed/merged-79ca330a60fff97ec5b742d5acb9b6e6-min.js.gzip?1571726426>; rel=preload; as=script, </fileadmin/_processed_/4/d/csm_testimage_c638a78f68.jpg>; rel=preload; as=image, </fileadmin/_processed_/b/2/csm_testimage8_acb8575ca4.jpg>; rel=preload; as=image, </fileadmin/_processed_/8/f/csm_testimage15_fb2f57687b.jpg>; rel=preload; as=image, </fileadmin/user_upload/testimage3.jpg>; rel=preload; as=image, </fileadmin/_processed_/4/d/csm_testimage_c638a78f68.jpg>; rel=preload; as=image, </fileadmin/_processed_/b/2/csm_testimage8_acb8575ca4.jpg>; rel=preload; as=image, </fileadmin/_processed_/8/f/csm_testimage15_fb2f57687b.jpg>; rel=preload; as=image"
		
				Header set X-SFC-State "StaticFileCache - via htaccess"
		
	</ifModule>
```

**Comment by lochmueller** [comment]
Hey @breakone 
some feedback and ideas. Could you patch this and test again?
- There is a missing `%` in front of the time. Fix is already in the current master (please update) https://github.com/lochmueller/staticfilecache/commit/5e7ae7eb311a748d2a6678cb0dd43299041a8fda This rule is important so the file redirect to the index file again.
- Please check if mod_expires ais active in the installation. You can do this with the backend module of the current master version also. There is a flash message in the Support tab: https://github.com/lochmueller/staticfilecache/commit/a8ce0ea33c3b0ff81bda7a6ed71a9b5418f1728b The second request schould have a time()+181 response in your case.

I hope the fist point is the problem?!

Regards,
Tim

**Comment by breakone** [comment]
Thanks @lochmueller ,
I've updated to the current master and checked the apache modules  

> Hey @breakone
> some feedback and ideas. Could you patch this and test again?
> 
> * There is a missing `%` in front of the time. Fix is already in the current master (please update) [5e7ae7e](https://github.com/lochmueller/staticfilecache/commit/5e7ae7eb311a748d2a6678cb0dd43299041a8fda) This rule is important so the file redirect to the index file again.
> * Please check if mod_expires ais active in the installation. You can do this with the backend module of the current master version also. There is a flash message in the Support tab: [a8ce0ea](https://github.com/lochmueller/staticfilecache/commit/a8ce0ea33c3b0ff81bda7a6ed71a9b5418f1728b) The second request schould have a time()+181 response in your case.
> 
> I hope the fist point is the problem?!
> 
> Regards,
> Tim

**Comment by lochmueller** [comment]
Note. Version 10.1.0 was release a few hours ago. Both patches are part of the version 👍

**Comment by breakone** [comment]
Hey @lochmueller ,
thanks for your answer!

I've updated to the current master. The modules check here [a8ce0ea](https://github.com/lochmueller/staticfilecache/commit/a8ce0ea33c3b0ff81bda7a6ed71a9b5418f1728b) does not work for me, because of php fpm. But the apache modules are enabled and it seems, that everything works as expected.

:)
