### ISSUE TITLE
Pages not properly Cached

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#210]
## Bug Report

**Current Behavior**
When I clear all Caches and manually delete the generated files & clear needed DB Tables as clearing all Caches from the Backend and now call my page in an anonym new Browser window I encounter this issue:

I call the page but is does not get delivered statically, not even on the 3rd or 4th hard-reload (STRG + F5)

As soon as I close the anonym Browser Windows and open a new one the Site gets delivered statiyally cached at the second call!

Little Video which starts after I called all the Pages once and did not cache them:

![SFC Cache Bug_16](https://user-images.githubusercontent.com/17692860/67829941-2c531380-fad9-11e9-8254-147e4bd69ccf.gif)

You will notice, as soon as I call the page now in an anonym Tab it will cache the page properly

**Environment**
- TYPO3 version(s): 9.5.10
- staticfilecache version: 10.0.2-dev

**Comment by lochmueller** [comment]
Hey @MartinH0 
this is the line of StaticFileCache: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/StaticCacheable.php#L32
So the core said, the page is not cachable. You have to debug into detail, why this funcktion is false and which componenten said that the page is not cachable. I am just the consumer of the function and the result is not part of the StaticFileCache extension.
If you find the problem we can add this to the FAQ are try to get a more clear message of the problem.
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @MartinH0 ,
the Prepare middlewar seams to be "to high". We reduce the level a little bit. But it is possible, that there are still problems with the TSFE. If the problem still exists, please check if you could move the prepareMiddleware even more down in the MiddlewareStack (After TSFE init process).
https://github.com/lochmueller/staticfilecache/commit/623d0e5b3b21a6dab6749c328b60b294f4c65cee

I close this issue, because there are no more detail information.

Regards,
Tim

**Comment by MartinH0** [comment]
Hi and sorry to reopen this issue, but the exact same thing happens again. Fiorst the site (all sites with forms) are not cachable. But calling them twice (with clearing cookies between the calls) makes it suddenly cachable.

Is there anything you can do? I think reproducing this is very simple with a site that does have a form.

**Comment by lochmueller** [comment]
This is not a StaticFileCache problem. Du you using the honexpot feature of forms? This will create frontend sessions and disable the caches. Otherwise you have to check, why the form disable the cache...
