### ISSUE TITLE
SFC v10.0.2 typo

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#212]
Version 10.0.2 is not stating its v10.0.2 but v10.0.1

https://github.com/lochmueller/staticfilecache/blob/7ab59051c71549b96479569b1467f63e5bfd344f/ext_emconf.php#L9

**Comment by lochmueller** [comment]
Fixed: https://github.com/lochmueller/staticfilecache/commit/2f2d9cd4914294f1cb876df7bab5b661f07f2f40
