### ISSUE TITLE
Boost mode and TCEMAIN.clearCacheCmd

### ISSUE THREAD

**Issue by SventB** [lochmueller/staticfilecache#215]
Hi,
I've activated "Boost mode" and I have a page with news records and page TSconfig `TCEMAIN.clearCacheCmd=1,2,3`

I expected that three new entries will be created in table tx_staticfilecache_queue after editing a news record, but there is no new entry in this table.
Is this a bug or don't you support this setting?

TYPO3 8.7.29
EXT:staticfilecache 9.0.0

**Comment by lochmueller** [comment]
The extension support this,because the caching framework does. The queue will only be filled, if there are valid cache entries: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/StaticFileBackend.php#L145 do you check that the extension already cache in the right way?

**Comment by SventB** [comment]
Ok, I understand, there have to be an entry in table cf_staticfilecache, then an entry is created in tx_staticfilecache_queue. This makes sense. Sorry for stealing your time.
