### ISSUE TITLE
Shortcuts get cached and result in an empty page

### ISSUE THREAD

**Issue by tgaertner** [lochmueller/staticfilecache#216]
## Bug Report

**Current Behavior**
Reproduce:
- create a SiteConfiguration for a root page
- make the root page a shortcut to first sub page 
- - lets say root page has slug "/" and first subpage "/home"
- call your base like https://devdomain.com/
- you get redirected to https://devdomain.com/home
- call https://devdomain.com/ again - you get a white page
(https://devdomain.com/home) works

- disabling staticfilecache results in the pages works like expected

**Environment**
- TYPO3 version(s): 9.5.11
- staticfilecache version: 10.0.3
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux, Apache, PHP 7.2

**Comment by lochmueller** [comment]
Hey @tgaertner 
seems that the cache store non n200 status code responses.
Could you try to add this lines:
```        if ($response->getStatusCode() !== 200) {
            return $response;
        }```
After this condition:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Middleware/GenerateMiddleware.php#L51
and rerun your test?!?
Regards,
Tim

**Comment by tgaertner** [comment]
Thanks @lochmueller for the fast investigation!

This change fixes it.

By design the call becomes much slower in case if the redirect. That's sad but ok in that case.
Other solution could be to create static file cache for the shortcut page path of the target...? (maybe feature)

**Comment by lochmueller** [comment]
Great. Added for the next version.

Caching redirects in files will be hard. I will think about it ;)
