### ISSUE TITLE
http/2 push for css files not working properly in all cases

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/staticfilecache#217]
## Bug Report

**Current Behavior**
After activation of http/2 push for js and css files I realized errors inside the google chrome network monitor when loading a page using EXT:bootstrap_package.
Some of the css resource paths coming with EXT:bootstrap_package are not added properly to the <link> header coming with http/2 push feature of EXT:staticfilecache.
Comparing to other resources, the problematic link paths are quoted with backslashes.
A working path would look like `/typo3temp/assets/bootstrappackage/fonts/346739da479e213b7b079a21c35f9ffac6feb37c93b4210969602358a8011f68/webfont.css` but it's added this way: `\/typo3temp\/assets\/bootstrappackage\/fonts\/346739da479e213b7b079a21c35f9ffac6feb37c93b4210969602358a8011f68\/webfont.css`
After removing css from the http/2 push file extension the error is gone, but all other css files are also removed from the link header.

**Expected behavior/output**
All resources in the http/2 push link header should be added without quoted paths 

**Environment**
- TYPO3 version(s): [9.5.11]
- staticfilecache version: [10.0.3]
- bootstrap_package: [10.0.8]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]
- OS: [Docker-Container with Debian 9]

**Comment by lochmueller** [comment]
Hey @mediaessenz 
I added one more test case for your description and the function works well:
https://github.com/lochmueller/staticfilecache/commit/d4db89e4f2013a6099ac21198e88575ea8f7cce3
Could you check if the link-tag looks like in the UnitTest?
Regards,
Tim

**Comment by mediaessenz** [comment]
I'm really not know what you are asking me?
Is the problem solved in the current master and I should test it?

**Comment by lochmueller** [comment]
No. I added you example to the UnitTests and everything works fine. I need the complete HTML markup of the page, where the error appears, so I can add it to a test case or more tecnical information.

**Comment by mediaessenz** [comment]
I already descriped my Environment in the Bug Report.
I don't know what you are missing.

**Comment by lochmueller** [comment]
The complete HTML markup of the page (not just the name of the CSS file), so I can rebuild your test case in a Unit Test like here: https://github.com/lochmueller/staticfilecache/blob/master/Tests/Unit/Service/HttpPush/AbstractHttpPushTest.php#L23
I don't know where the error is (in the parsing of the document, in the workflow, in the response object). Currently I don't have the error in my systems, so I need more information.
Regards,
Tim

**Comment by mediaessenz** [comment]
Do you use the same environment like me, especial bootstrap_package 10?

**Comment by lochmueller** [comment]
No, because the mechanism is indepandant from any TYPO3 related structure, because the implemntation parse the generated HTML Markup (that is the reason, why the markup is required). I cannot rebuild any env incl. 3rd party extensions. I will check this in the next days/weeks again...

**Comment by lochmueller** [comment]
Fixed in current master. Add added the critical markup to the Unit test and fix the implementation: https://github.com/lochmueller/staticfilecache/commit/b94dac62808993d613ebc4fb40ff02194ad79e14 ... next time, please just send me the critical HTML markup. It is much easier than buildung up complex envs ;)
