### ISSUE TITLE
Nginx example configuration doesn't work for chrome 

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/staticfilecache#218]
## Bug Report

**Current Behavior**
After upgrading staticfilecache from 8.2.2 to 10.0.3 and change the old staticfilacache configuration for nginx with the new one included in the documentation, all frontend pages opened in google chrome browser ends in a download of the html file. The downloaded file has the name of the title of the page.
If I open the same url in firefox, everything works without problems.

This is a response header of a page request using `curl -I url`:
```
HTTP/2 200
server: nginx
date: Sun, 10 Nov 2019 19:02:00 GMT
content-type: application/octet-stream
content-length: 22785
last-modified: Sun, 10 Nov 2019 17:44:47 GMT
etag: "5dc84c8f-5901"
x-powered-by: PleskLin
strict-transport-security: max-age=63072000
x-content-type-options: nosniff
accept-ranges: bytes
```
If I add any query param to the url (like `?blub`) I get this response header:
```
HTTP/2 200
server: nginx
date: Sun, 10 Nov 2019 19:02:12 GMT
content-type: text/html; charset=utf-8
content-length: 22785
vary: Accept-Encoding
content-language: de
expires: Mon, 11 Nov 2019 17:44:45 GMT
etag: "289dd56047283b86d92f626d0443098c"
cache-control: max-age=81754
pragma: public
x-ua-compatible: ie=edge
link: </typo3temp/assets/compressed/merged-2e3a9793929c2ff564d25b1b37fbb421-66999a067ded878e5bb22542f14331e1.1573407873.js>; rel=preload; as=script, </typo3conf/ext/bootstrap_package/Resources/Public/Contrib/webfontloader/webfontloader.js>; rel=preload; as=script, </typo3temp/assets/compressed/merged-1eb531aeefced5819b7a651fa37e1d70-dd62a5bcef99c23be7f385e81406dddb.1573407873.js>; rel=preload; as=script, </typo3temp/assets/compressed/merged-4e917cd2800fe3b497ffa035e2f7e16e-2ae1c79823e63487a40852c9150b7a3a.1569672130.js>; rel=preload; as=script
x-powered-by: PleskLin
strict-transport-security: max-age=63072000
x-content-type-options: nosniff
```

**Expected behavior/output**
A generated page should also served correctly to google chrome users 

**Environment**
- TYPO3 version(s): [9.5.11]
- staticfilecache version: [10.1.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]
- OS: [OSX 10.15.1]
- Browser: [Google Chrome 78.0.3904.97]

**Comment by mediaessenz** [comment]
I really have only basic knowledge in nginx configuration, but I got it running for me, by adding `default_type text/html;` inside the `@sfc` block right before `try_files /typo3temp/tx_staticfilecache/${scheme}_${host}_${server_port}${uri}/index`

Maybe this helps...

**Comment by lochmueller** [comment]
Hey @mediaessenz 
I add this line to the documentation. The generated .htaccess files are useless for nginx so it is a good point to add the default type in the configuration.
Regards,
Tim
