### ISSUE TITLE
Export/Import SFC settings

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#220]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A lot of Issues could be reproduced better if users can export their setting (from SFC) directly and offer them here.

**Describe the solution you'd like**
Button in the TYPO3 Backend which exports all SFC related Infos & setting to a XML/JSON/TXT File which can be applyed to any Bug-Report.

I think this is something that would make debugging Issues more easier.

Also an Import function would be great to test various different settings and make it more easiert to Export/Import setting.

**Comment by lochmueller** [comment]
Good idea. I will add this...

**Comment by MartinH0** [comment]
May I add:

This Debug-Log should contain probably this:

1. TYPO3 Version
2. SFC Version
3. PHP Version
4. WebServer
5. OS
6. Database
7. Enviroment
8. Extensions (LOCAL EXT only)
9. Cron last Time run

10. [ALL SFC Settings]

--------------------------------

1-9 should get exported aswell (for debugging) but if you import just 10 should be imported.

1-9 = System Info
10 = SFC Settings
