### ISSUE TITLE
Cache isn't flushed on edit

### ISSUE THREAD

**Issue by syssi** [lochmueller/staticfilecache#222]
## Bug Report

**Current Behavior**
A cached page has 3 tags at cf_staticfilecache_tags:

1, https://example.com/kontakt/, pageId_15
2, https://example.com/kontakt/, sfc_pageId_15
3, https://example.com/kontakt/, sfc_domain_example_com

If I hide a content element in **list mode** the three items are deleted and the files & directory at typo3temp/tx_staticfilecache/https_example.com_443/kontakt/ are removed.

If I hide the content element in **page mode** the "pageId_15" tag is removed only, the files aren't removed and the cache doesn't get updated anymore. If I use "Clear FE cache" everything gets pruged and I can start from scratch.

**Expected behavior/output**
The cache should be flushed everytime.

**Environment**
- TYPO3 version(s): 9.5.11
- staticfilecache version: 10.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian Buster

**Possible Solution**

**Additional context**

Used extensions:

```
beuser_fastswitch
fluidpages
flux
ig_slug
masi
schema_org_generator
sluggi
sms_responsive_images
solr
staticfilecache
translate_locallang
typo3_encore
typoscript_rendering
vhs
webp
yoast_seo
youtubevideo
```

**Comment by syssi** [comment]
A cached page has 3 tags at cf_staticfilecache_tags:

1, https://example.com/kontakt/, pageId_15
2, https://example.com/kontakt/, sfc_pageId_15
3, https://example.com/kontakt/, sfc_domain_example_com

If I hide a content element in list mode the three items are deleted and the files & directory at `typo3temp/tx_staticfilecache/https_example.com_443/kontakt/` are removed.

If I hide the content element in page mode the "pageId_15" tag is removed only, the files aren't removed and the cache doesn't get updated anymore.

**Comment by syssi** [comment]
If I disable `yoast_seo` the issue is solved.

**Comment by lochmueller** [comment]
Hmm.... sounds like a problem with `yoast_seo` ?!
StaticFileCache do not implement the tag and remove logic. It is core based.

**Comment by syssi** [comment]
I'm afraid you are right. :-) Sorry for the noise. I will close the issue.
