### ISSUE TITLE
Cache garbage-collection not cleaning up database tables in boostMode

### ISSUE THREAD

**Issue by MK-42** [lochmueller/staticfilecache#223]
## Bug Report

**Current Behavior**
When running in boost mode, the collectGarbage task of StaticFileBackend exits early and never cleans up expired database table entries
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/StaticFileBackend.php#L265

**Expected behavior/output**
The expired entries in the sfc_* tables should be deleted even in boost-mode

**Environment**
- TYPO3 version(s): 9.5.11
- staticfilecache version: 10.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian

**Possible Solution**
Flushing expired entries either during garbage-collection (together with the expired files) or during boostMode command (probably favorable)

**Additional context**
Running without boost mode seems to be stable in that regard

**Comment by lochmueller** [comment]
Preparation for better controll of the enable/disable state of the BoostQueue:
https://github.com/lochmueller/staticfilecache/commit/f39d87923e9661b82d583feaf347f32767780f62

**Comment by lochmueller** [comment]
Please also check this information:
https://github.com/lochmueller/staticfilecache/commit/d26fe2368753e1f7148a93f538fbd7c4a6526222#diff-976faf4feece57aa1a4ea6ff061265baR256
https://github.com/lochmueller/staticfilecache/commit/bbd646d49294f040f7e9346ffd810f27e2e7e1bb#diff-bf68ab9f962692f3a483c38bb0b9d927R61

**Comment by MK-42** [comment]
Thanks for taking care!
