### ISSUE TITLE
System hardening

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#229]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Is related to https://github.com/lochmueller/staticfilecache/issues/225 & https://github.com/lochmueller/staticfilecache/issues/227

**Describe the solution you'd like**
Atm some important parts https://github.com/lochmueller/staticfilecache/blob/af213de046f14de31e88a696d40ec8c4b715d174/ext_conf_template.txt#L14 can be missing if the system is missconfigured or/and updated/upgraded 

**Describe alternatives you've considered**
Seems like the Part `Content-Type` is indispensable, so it should not be editable.
Solution would be renaming the System-Var from "validHtaccessHeaders" to "additionalSfcHeaders" which could be look like this:

```
cat=basic; type=string; label=Valid .htaccess headers: List of headers that are transferred to the .htaccess configuration. E.g. if you use config.additionalHeaders.xxx you can add this headers here. Please change this configuration only, if you know what you do.
additionalSfcHeaders= Content-Language,Link,X-SFC-Tags
```
they will be added/appended to the needed/indispensable elements which should not be editable by the User!

Means there are two settings:

1. `neededSfcHeaders` = `Content-Type` (not editable by the User)
2. `additionalSfcHeaders`= `Content-Language,Link,X-SFC-Tags` (editable and optional)

in the end the system should add them together

3. `allSfcHeaders` = `neededSfcHeaders` + '`,`' + `additionalSfcHeaders`
3. `allSfcHeaders` = `Content-Type,Content-Language,Link,X-SFC-Tags`

This would make the system more stable and not making users run into trouble if they change the configuration. Also Issue https://github.com/lochmueller/staticfilecache/issues/225 & https://github.com/lochmueller/staticfilecache/issues/227 could have been prevented if this would have been implemented befor.

**Comment by lochmueller** [comment]
👍 done.
