### ISSUE TITLE
The page is not static chachable due to [FE][lockIP]

### ISSUE THREAD

**Issue by vmans** [lochmueller/staticfilecache#23]
It appears that [FE][lockIP] must be 0 in order to avoid 

>     The page is not static chachable via TypoScriptFrontend
>     User or group are set

Don't know if that's a requirement, something that should be documented, a coincidence.

If you run into problems, it is possible that you need to flush fe_sessions and fe_session_data, as in my case.

**Comment by lochmueller** [comment]
Hey @vmans 
How does the lockIP affect the page generation? 
If a page is for FE users only, the cache is not generated at all...  
Regards,
Tim

**Comment by vmans** [comment]
Hi Tim, @lochmueller 
There were no fe_users of groups defined, and the tables were empty. But I still got the message:

> The page is not static chachable via TypoScriptFrontend
> User or group are set

So digging deeper, it appeared that there was a cookie set (I don't know if that matters) and that [FE][lockIP] was set to 2. Changing that to 0 and flushing the tables fe_sessions and fe_session_data (they had data), solved the issue.

That's what I know.

Cheers,
Vincent

**Comment by lochmueller** [comment]
Stange. I will check this in the next days.

Note: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoUserOrGroupSet.php#L26 I only check isUserOrGroupSet and I don't know at the moment, how the lockIP affect the user auth "in this direction".

**Comment by vmans** [comment]
Perhaps it's a different thing, coincidence, I don't know. Hope you can tell soon.

**Comment by lochmueller** [comment]
Hey @vmans ,
we need more information about your setup!? There is no relation between lockIP and the "user or group are set" message. We checked our systems. We use FE|lockIP=2 in all our systems and staticfilecache works well. Perhaps you could run some debugging?
Regards,
Tim

**Comment by vmans** [comment]
Okay, sure. I work on this installation today and tomorrow and I'll dig into it.

**Comment by lochmueller** [comment]
@vmans Any news on this topic? Should I close this issue?

**Comment by lochmueller** [comment]
I Double check this. There is no relation between lockIP and the Static File Cache. This is the only "user related" cache check for the frontend: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoUserOrGroupSet.php#L26
But the lockIP is not related to the existing user session?!?!
I close this issue. If you have more information please create a new one or reopen this issue...

Regards,
Tim
