### ISSUE TITLE
Clean up cache entries if page settings changes

### ISSUE THREAD

**Issue by jackd248** [lochmueller/staticfilecache#231]
## Feature Request

It would be great if the extension could clean up cache files and entries if a previous cached page will be marked to disable the generation of static files anymore. 

Possible solution could be a Backend Hook into the DataHandler that check the page settings and remove the cache if the cache exists.

**Comment by lochmueller** [comment]
Hey @jackd248 
Thanks for feedback... I added the hook to the current master.
Regards,
Tim
