### ISSUE TITLE
BoostQueueRun tries to access site with `$config['disableStaticFileCache']`

### ISSUE THREAD

**Issue by MK-42** [lochmueller/staticfilecache#232]
## Bug Report

**Current Behavior**
Setting `$config['disableStaticFileCache']` in the site-configuration does not completely disable SFC for that site. BoostQueue-Runs will still try to fetch urls of that site.
Note: in our case these pages are behind access control, and the log is spammed with 403 Errors of guzzle.

**Expected behavior/output**
Setting `$config['disableStaticFileCache']` should completely disable SFC for all urls under that site, as if SFC wasn't installed.

**Environment**
- TYPO3 version(s): 9.5.11
- staticfilecache version: 10.2.0 (update to 10.2.1 pending)
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: debian something...

**Comment by lochmueller** [comment]
Any ideas how to handle this? The log will be clean up... the "design" of the boost queue is, that there are errors in the log. E.g. if you rnamee pages, you will get 404 errors.
The question is, how should we cleanup the queue and stop running worker, if the site configuration is set to disableStaticFileCache?

**Comment by MK-42** [comment]
What you are suggesting is, that these errors only occur, because I have previously had boost-mode enabled for that site?
Otherwise there shouldn't be any entries for that site in the queue in the first place?

If thats the case, than I'm already (nearly) happy. Maybe the boost-queue could be flushed when that setting for a site is enabled?

**Comment by lochmueller** [comment]
Hmm... I will check this. There is no mechanism in TYPO3 that can actively do this. We cannot truncate the queue (because perhaps there is one page that use the queue and one page that do not) and thee problem is, that the site configuration is editable via ID, so we get no note about the change.

First thought... just ignore the queue. The queue don't havee to be "clean". If there are wrong entries thee entries will run throw thee queue and nothing happen...

Tim

**Comment by lochmueller** [comment]
Hey @MK-42 
there is no mechanism in the core, that can handle this problem in the right way. Problem will be, that the site configuration will changed often via Deployment and not via the backend. So I solve this problem by a more detailed description:
![Bildschirmfoto 2020-02-11 um 22 03 19](https://user-images.githubusercontent.com/3907126/74278999-5e9c2000-4d1a-11ea-948e-6de4dc78521f.png)

Regards,
Tim
