### ISSUE TITLE
File extensions for HTTP/2 push: If only jpg, getHeaders gets png too

### ISSUE THREAD

**Issue by markusa86** [lochmueller/staticfilecache#235]
## Bug Report

Hi,
if I choose png in File extensions for HTTP/2 push, the handler gehts jpeg and jpg too.

**Environment**
- TYPO3 version(s): 9.7.11
- staticfilecache version: 10.2.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: linux

**Possible Solution**
getHeaders shout check the extension and not return all images

Maybe it is possible to exclude files. for example touch-icon.png should not be pushed :)

Regards,
Markus

**Comment by lochmueller** [comment]
Do you mean this: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/HttpPush/ImageHttpPush.php#L21 ? The file extensions are not configurable? Where do you "choose" png only?

Regards,
Tim

**Comment by markusa86** [comment]
In ext_conf_template...
sendHttp2PushFileExtensions = css,js,png

**Comment by lochmueller** [comment]
Thanks for the report. Problem is fixed in current master.
