### ISSUE TITLE
FallbackMiddleware uses wrong cookie

### ISSUE THREAD

**Issue by Teddytrombone** [lochmueller/staticfilecache#237]
## Bug Report

**Current Behavior**
If a frontend login is active and the FallbackMiddleware tries to handle the request, it checks, if the staticfilecache cookie is set to fe_typo_user_logged_in. As the cookie never gets this value, the check is always passed and so the cached output is shown.

**Expected behavior/output**
If a frontend login is active, the FallbackMiddleware shouldn't deliver the cached output.

**Environment**
- TYPO3 version(s): 9.5.13
- staticfilecache version: 10.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**
Instead of checking the cookie for fe_typo_user_logged_in the value typo_user_logged_in should be used (line 69 in fileClasses/Middleware/FallbackMiddleware.php)

**Comment by lochmueller** [comment]
Hey @Teddytrombone 
Thanks for reporting. Fixed in current master.
Regards,
Tim
