### ISSUE TITLE
No cache if Backend Login User

### ISSUE THREAD

**Issue by mhirdes** [lochmueller/staticfilecache#239]
## Bug Report
I have a Fluid partial where I show a language menu only if a backend user is logged in. Therefore I use
`<f:be.security.ifAuthenticated>`

If I view the page first while I am logged in TYPO3 the language menu is also in the cache. This should be avoid.

**Expected behavior/output**
If a user is logged in TYPO3 no file cache shold be generated. 

**Environment**
- TYPO3 version(s): 9.5.13
- staticfilecache version: 10.2.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 18 with PHP 7.3
- Browser: Chrome 79

**Comment by lochmueller** [comment]
Hey @mhirdes ,

there is a cache rule that prevent this: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoBackendUser.php

I will check this in the next week.

Note: I don't know if the "be" ViewHelper are for frontend Fluid templates?!

Regards,
Tim

**Comment by lochmueller** [comment]
There was no feedback anymore. I will close this issue. If there are any news/hints related to this problem, please check the NoBackendUser rule and check if the rule do the right thing (I just call the TYPO3 core and trust the return value).
Regards,
Tim
