### ISSUE TITLE
Call to a member function stdWrap() on string

### ISSUE THREAD

**Issue by CarstenHager** [lochmueller/staticfilecache#240]
## Bug Report

In einigen Installationen bekomme ich in unregelmäßigen Abständen folgende Fehlermeldung (Siehe Screenshot). Ein Cache leeren hilft nur kurz.

**Environment**
- TYPO3 version(s): 9.5.13
- staticfilecache version: 10.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux 2.6.32-openvz-042stab127.2-amd64 (Mittwald VServer)
![screencapture-fuer-wuerzburg-de-2020-02-13-14_25_26](https://user-images.githubusercontent.com/5907780/74444718-9075c980-4e75-11ea-91d5-811b80f8012f.png)

**Comment by lochmueller** [comment]
Hey @CarstenHager 
that is realy strange. I would understand `Call to a member function stdWrap() on null` because the cObj is not there at the moment. But the message said `on string` could you check why $this->cObj is a string and log the content, if $this->cObj is a string?
Regards,
Tim

**Comment by lochmueller** [comment]
Ahh... found. It is related to "force statif file cache". Please DO NOT use this. I will drop this function and add a more detailed note for the current release (see next commit). Please fix the plugins/configuration that is not cachable and not just enable the checkbox. See next commit....

**Comment by lochmueller** [comment]
![Bildschirmfoto 2020-02-18 um 22 28 19](https://user-images.githubusercontent.com/3907126/74779537-ff9c5500-529d-11ea-972b-ed48d0775f9d.png)
