### ISSUE TITLE
TableNotFoundException with TYPO3 9.5.14

### ISSUE THREAD

**Issue by AureliusHogan** [lochmueller/staticfilecache#243]
## Bug Report

**Current Behavior**
I just installed lochmueller/staticfilecache and got the following error message when I viewed the first page:
`Doctrine\DBAL\Exception\TableNotFoundException
An exception occurred while executing 'SELECT COUNT(*) FROM `cf_staticfilecache` WHERE (`identifier` = ?) AND (`expires` >= ?)' with params ["http:\/\/my.develop\/service", 1582387304]: Table 'db.cf_staticfilecache' doesn't exist.
`

And there is no cf_staticfilecache in the database. But there is a table called tx_staticfilecache. But just renaming this is no sulution, since it doesn't have the correct structure to handle this query.

**Environment**
- TYPO3 version(s): 9.5.14
- staticfilecache version: 10.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 18.04.4 LTS

**Possible Solution**
Seems like there are table definitions missing in ext_tables.sql. The strange thing is, that older versions don't have the missing tables as well.

**Additional context**
I tried staticfilecache version: 9.0 and had the same problem.

**Comment by AureliusHogan** [comment]
Strange things are happening. I removed it again, added it again and again and again and all of a sudden ... there they are. 🤔

So everything is fine now.

**Comment by lochmueller** [comment]
Hey @AureliusHogan 
There are table definitions, that are not part of the ext_tables.sql file (like all caching framework tables). I think it was a problem in the installation process.
Regards,
Tim
