### ISSUE TITLE
Adapt method getMissingApacheModules

### ISSUE THREAD

**Issue by echavaillaz** [lochmueller/staticfilecache#247]
## Bug Report

**Current Behavior**
If the function `apache_get_modules` does not exist, a warning is shown in the backend module. I think it is not the good behavior because perhaps there is no missing module.

**Expected behavior/output**
No warning when the function does not exist.

**Possible Solution**
Replace the method with something like this :+1: 

```
/**
 * get if the apache support the needed modules
 *
 * @return array
 */
public function getMissingApacheModules(): array
{
    $missingApacheModules = [];

    if (function_exists('apache_get_modules') === true) {
        $missingApacheModules = array_diff(['mod_rewrite', 'mod_headers', 'mod_expires'], apache_get_modules());
    }

    return $missingApacheModules;
}
```

Thanks

**Comment by lochmueller** [comment]
Thanks for reporting. Fixed in current master.
