### ISSUE TITLE
Cache Flush Error while in BoostMode

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#249]
## Bug Report

**Current Behavior**
When in BoostMode I get this error while flushing the Cache:

![SFC Flush Cache Error](https://user-images.githubusercontent.com/17692860/78593295-b2247900-7846-11ea-89ce-ee9181e1b6e7.PNG)

No matter if I flush "Frontend Cache" or "All Caches".
I think this comes from the fact that in Boostmode the Cache of SFC is not flushable, but this should not display any errors as this is a wanted behaviour.

The issue immediately is solved when disableing BoostMode.

**Environment**
- TYPO3 version(s): 10.3.0
- staticfilecache version: 11.0.0
- PHP version: 7.4
- Is your TYPO3 installation set up with Composer (Composer Mode): No

**Additional context**
In v10.1.0 (latest version I tested) this was not the case.

**Comment by lochmueller** [comment]
hey @MartinH0 Could you check the error in the Network monitor. There should be a AJAX call that result in a error...

**Comment by MartinH0** [comment]
Indeed. there was a AJAX call with status code 500. When called the URL directly this error pops up:

![SFC Error](https://user-images.githubusercontent.com/17692860/78604916-e144e580-785a-11ea-8303-8122ba1c19fc.PNG)

**Comment by MartinH0** [comment]
I just looked in the db and it does really not exist. They also do not get generated when I install the extension

**Comment by lochmueller** [comment]
You are right: this line is wrong for TYPO3 >= 10.3:
https://github.com/lochmueller/staticfilecache/blob/ece94eafbed604756adf5c3e99a0090663a41015/Classes/Domain/Repository/CacheRepository.php#L75

**Comment by MartinH0** [comment]
By changing the line to:

`$prefix = 'cache_';`

Its again working. Thanks for the quick hint. But how to implement this fix just for TYPO3 >= 10.3 and not breaking compatibility for lower versions?

**Comment by lochmueller** [comment]
We have to check the version via: https://api.typo3.org/master/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_version_number_utility.html ... I will add a patch in the next days...

**Comment by lochmueller** [comment]
Hey @MartinH0 
fixed in current master.
Regards,
Tim
