### ISSUE TITLE
Boostmode without Crons does not work

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#251]
## Bug Report

**Environment**
- TYPO3 version(s): 10.3.0
- staticfilecache version: 11.0.0

Exampel of generated `index.config.json`

```
{
    "generated": "Mon, 20 Apr 2020 11:47:30 +0000",
    "headers": {
        "Content-Type": [
            "text\/html; charset=utf-8"
        ],
        "Content-Language": [
            "de"
        ],
        "Expires": [
            "Tue, 21 Apr 2020 11:47:29 GMT"
        ],
        "ETag": [
            "\"94339b14cf558ac4b14cc17e971aec8c\""
        ],
        "Cache-Control": [
            "max-age=86400"
        ],
        "Pragma": [
            "public"
        ]
        [...#...]
    }
}
```

Now the static file related to this is not getting served statically after the Expires date is reached. But as I'm in Boost-Mode I still wants it to be served untill it gets regenerated. In normal Mode it of course get validated

Why I'm doing so? Becasue 100% of my page is just changing Event-Based and not Time-Based. So the only reason to regenerate a Cached file is when it got: created, changed, deleted.

But not for any reason recurring. Thats why I choosed BootstMode and when I change content it should automatically regeenrated, but not with Crons.

In older versiosn Boost-Mode did work without Crons perfectly fine

So my request: when in Boost-Mode the file should not be validated if its already expired but instead just getting delivered.

.

Note: after the file was not getting served statically anymore, just deleting the file (on the storage) and letting it generate again was solving the issue for another day untill the same thing repeats ofc.

**Comment by lochmueller** [comment]
Hey @MartinH0 I think there was already issues like this, right? Could you add a solution/concept to understand the problem better? ;) What means "event based" in your context and why your event change content, but do not trigger clear cache commands?
Regards, Tim

Note: "after the file was not getting served statically anymore, just deleting the file (on the storage) and letting it generate again was solving the issue" This do not solve the problem, because the Idea of the boost mode is, that the user ALWAYS get a fast file cache, and the regeneration is done by TYPOo3
Note 2: Doo not remoove file manually. The files are bound to a database representation and the cache is "inconsistent" if you delete the file and do not delete the DB respresentation.

**Comment by MartinH0** [comment]
I dont know if there is a existing one, but feel free to move this over to a already existing one.

About Event-Based:
Nothing on my site will change its content unless someone goes into the TYPO3 Backend and changes it. So there will never be a reason to regenerate the Cache, as the content would be the same. Thats why I choosed Boost-Mode.

Note1:
Thats why I reported this as a Bug. As this was not working for me as expected. I will wait one more day and inspect it a bit closer. But it seems that the static Files are not getting delivered after the Expires date was reached.

Note2:
I know, after this test I altered the needed DB parts.

**Comment by lochmueller** [comment]
Hey @MartinH0 

But the question is, what to you expect? 

The process ist currently (in boost mode):
- A editor change someting (event driven)
- The core invalidate the caches (e.g. of the page, content element etc. based on configuration of your instance)
- Static file cache clear cache is triggert (normally by the pageId_XXX tag).
- Boost mode is enabled, so the URI is placed in the queue and the file is NOT deleted
- Later (e.g. 5 min later, based on the scheduler/cron configuration) the queue worker get this URL and recrawl the page
-- if this works, the page has the right content
-- if this do not work, the cache entry (DB and file) is dropped

Could you explain in wich step you expect another process?!

Regards,
Tim

**Comment by MartinH0** [comment]
Ok let me explain what I mean and what I think the bug is.

1. I set SFC to Boost mode
2. I call the frontend and let the cache beeing generated
3. I wait one day (without changing anything!)
4. I call the frontend again and do get served dynamically and not statically

Now I wonder why this happens as I'm in Boost-Mode and the static files are there on the fileserver but I do not get served statically.

**Comment by lochmueller** [comment]
If the files are there and will not deliverd, the htaccess configuration is wrong. Note... the caches create also htaccess files. Perhaps you use one of this options: https://github.com/lochmueller/staticfilecache/blob/master/Resources/Private/Templates/Htaccess.html
- sendCacheControlHeader (via core)
- sendCacheControlHeaderRedirectAfterCacheTimeout (via SFC)

Note: Enable "config.sendCacheHeaders = 1" is the next level of complexity and you have to check, if the generated htaccess files match your needs.

**Comment by MartinH0** [comment]
I do have both options enabled.
Should I disable both?

Do they even apply in Boost-Mode?

**Comment by MartinH0** [comment]
Also: after running these Crons manually all the Caches have been deleted and not regenerated. They are not existing in the filesystem and also the extension does not show them as cached anymore. But I'm in Boost-Mode.

The Crons I run:
1. `staticfilecache:flushCache`
2. `staticfilecache:boostQueue`

**Comment by lochmueller** [comment]
"Send Cache-Control header" is not missing. It is based on the typo3 core configuration. 

If the caches are only deleted (that means that the queue get errors in the recrawl process), than the configuration of your server/instance is wrong. problems could be: The domain/DNS is not routed to your own website?! Are the URIs in the queue the right one (right sheme, right domain)?

**Comment by MartinH0** [comment]
Domain is currently set to "/" so not set, or dynamcally. But when I call the page the Cache is getting genereated again for the pages which I called.

I will check the queue

**Comment by MartinH0** [comment]
Yes Queue looks fine. But as soon as I execute `staticfilecache:boostQueue`:

1. `tx_staticfilecache_queue` its empty (like it should)
2. `cache_pages` is empty
3. `cache_staticfilecache` is empty

**Comment by lochmueller** [comment]
Could you check the `call_result` column for a few URIs in the `tx_staticfilecache_queue` table?

**Comment by MartinH0** [comment]
When exactly should I do this?
After executing `flushCache` or `boostQueue`

AFter calling these links again the statuscode is 304. Which `call_result` are you exactly talking about?

For me there is no column in the DB named `call_result`

**Comment by lochmueller** [comment]
OK. You have to check your server configuration. It is not possible for Guzzle to call the website. This could be problems in your DNS configuration or SSL configuration or something else: https://de.wikipedia.org/wiki/HTTP-Statuscode#9xx_%E2%80%93_Propriet%C3%A4re_Fehler

Please call `curl YOUR_URL_WITH_RIGHT_SHEME` und your TYPO3 server and check if the website is callable.

**Comment by MartinH0** [comment]
But the site is working fine. I use Cloudflare as DNS and do not have a local DNS Server. When I manually call the site it returnes a 200/304 which is perfectly fine.

I will try to downgrade and test with a different version where I will apply the 10.3 patch manually and report back. Becasue the site itself is working fine.

**Comment by lochmueller** [comment]
I think they update Guzzle and perhaps the SSL handling is another. I cannot chnage this in SFC... it ist related to your TYPO3 Konfiguration (TYPO3_CONF_VARS|HTTP für guzzle handling) or server configuration. You can test this also by manually call `GeneralUtility::getUrl('YOUR_URL');`

**Comment by MartinH0** [comment]
Where exactly should I test/call `GeneralUtility::getUrl('YOUR_URL');`? Would like to test it.

**Comment by lochmueller** [comment]
In any PHP file that is called via frontend/backend. 
Do you try to disable the verify in your HTTP configuration?

`LocalConfiguration.php`

```  
...
  'HTTP' => [
        'allow_redirects' => [
            'max' => 5,
            'protocols' => [
                'http',
                'https',
            ],
            'referer' => false,
            'strict' => false,
            'track_redirects' => false,
        ],
        'connect_timeout' => 10,
        'timeout' => 10,
        'verify' => false,
    ],
...

```

**Comment by MartinH0** [comment]
Also this did not work. I use a Cloudflare certificate. So if the call is internally it could trigger a SSL cert error, but if its external through cloudflare it will not trigger any errors as the outer SSL Cert is a valid (not singned by CloudFlare) one.

But this again did not work.

**Comment by lochmueller** [comment]
But external is irrelevant. If your server is not allowed to call your own Domain/URI incl. SSL termination etc. from your server host, you cannot use Boostmode, because SFC Boostmode need this feature. Sorry :-/

**Comment by lochmueller** [comment]
There is no other solution at the moment and 99% of the servers resolve domain/SSL in the right way.

**Comment by MartinH0** [comment]
> There is no other solution at the moment and 99% of the servers resolve domain/SSL in the right way.

My Server is allowed to resolve its own domains/SSL otherwise it would not work on TYPO3 v9 as these installations are on the same server with the same setup.
And both also do have the same cloudflare-signed SSL-Cert. So there is no difference between them, but I will ask some from the TYPO3 core team if this could be related tosomething from them.

Thanks!

**Comment by lochmueller** [comment]
OK. As technical information. I use the guzzle client:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/ClientService.php#L57 and also respect `$GLOBALS['TYPO3_CONF_VARS']['HTTP']` Feel free to debug in this function and check detailed error handling of guzzle for more information. Perhaps Guzzle can show you your problem on othis server.
