### ISSUE TITLE
Wrong Content-Type of cached JS-Files

### ISSUE THREAD

**Issue by einpraegsam** [lochmueller/staticfilecache#253]
TYPO3 10.4 and 11.0 for staticfilecache

We have two typenums that are cacheable and should have the Content-Type "text/javascript" (see https://github.com/in2code-de/lux/blob/develop/Configuration/TypoScript/Lux/11_PageConfiguration.typoscript#L182). It's ok that they are cacheable because the content does not change that often.
So files are correct stored at `typo3temp/tx_staticfilecache/https_www.in2code.de_443/fieldmapping.js/` also with a index.config.json file

The content of this file is:
```
cat index.config.json 
{
    "generated": "Tue, 21 Apr 2020 16:33:06 +0200",
    "headers": {
        "Content-Type": [
            "text\/javascript"
        ],
        "Content-Language": [
            "de"
        ],
        "Expires": [
            "Wed, 22 Apr 2020 14:33:06 GMT"
        ],
        "ETag": [
            "\"950472d74156de74dda89738c6a6dd7e\""
        ],
        "Cache-Control": [
            "max-age=86400"
        ],
        "Pragma": [
            "public"
        ],
        "Strict-Transport-Security": [
            "max-age=63072000;"
        ],
        "X-XSS-Protection": [
            "1; mode=block"
        ],
        "X-Frame-Options": [
            "SAMEORIGIN"
        ],
        "Content-Length": [
            "448"
        ],
        "X-SFC-Cachable": [
            "1"
        ],
        "X-SFC-Tags": [
            "pageId_1",
            "sfc_pageId_1",
            "sfc_domain_www_in2code_de"
        ],
        "X-SFC-State": [
            "TYPO3 - add to cache"
        ]
    }
}
```

Is there a problem in the .htaccess file because of the wrong content-type? We have per default a entry with `AddType application/javascript                      js` and after those line the lines of your example .htaccess are added. I also tested to change `ForceType` to `AddType` but without result.
It is a DomainFactory Server.

Any hints for me?

Content-Type delivered from cache:
![screenshot_chrome](https://user-images.githubusercontent.com/89055/79975746-c352c400-849b-11ea-98a0-406d16b0433a.png)

Correctly saved:
![screenshot-module](https://user-images.githubusercontent.com/89055/79975748-c3eb5a80-849b-11ea-9ee9-e4d11bc3fab2.png)

**Comment by lochmueller** [comment]
Hey @einpraegsam 
problem is currently, the cache file has no file ending anymore. That is the reason why `ForceType` and `AddType` do not works. I don't check the apache konfiguration, but perhaps it is something like "*.js/"-folder to add the type? Because for apache the only information is the ".js" in the cache folder name.
Regards,
Tim

**Comment by einpraegsam** [comment]
Because we can't change the vHost records of this Managed Server, Marcus is playing with the .htaccess - the current status is
```
<If "%{ENV:SFC_URI} =~ /.*\.js$/">
        ForceType text/javascript
    </If>
```
But it works only on subpages. So we are going on with digging into this issue.

Other question: Why is the Content-Type stored in the config file when it can't be used?

**Comment by lochmueller** [comment]
Hey @einpraegsam 
the cconfig.json ist used for the fallback middleware: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Middleware/FallbackMiddleware.php#L95
The middleware could restore all the headers  (but not used all the headers currently).

If you find any ideas for a good solution -> this would be cool :) 

Regards,
Tim

**Comment by einpraegsam** [comment]
What a pitty, we played a lot but did not find a solution. I'm not thinking of generating JS files with a USER_INT so they are not cached any more :(

**Comment by felixbuenemann** [comment]
@einpraegsam Could you test if the proposed solution from #259 fixes your problem? There's more discussion in #258.

I think you should be able to test it by overriding the default Htaccess Template in the extension settings (`basic.htaccessTemplateName`) and adding `ForceType {contentType}` below the `{escaping off}` line of the template.

**Comment by lochmueller** [comment]
Note: I merged the change a few seconds ago to current master.

**Comment by lochmueller** [comment]
I tested it with the current master (and published version) and it works (for Apache + mod_headers only, because we need the .htaccess incl. the headers). Here my example:

Site Configuration:
```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: ''
    map:
      test.js: 123123
```

TS:
```
js_test = PAGE
js_test {
    typeNum = 123123
    config {
      disableAllHeaderCode = 1
      additionalHeaders.10.header = Content-Type:text/javascript
      xhtml_cleaning = 0
      admPanel = 0
   }

   10 = TEXT
   10.value = alert('Hallo World');
}
```

Important (!!!!): TYPO3 create a header called "Content-Type" and StaticFileCache use this and check this. If you add "Content-type" it is a second header in the response and the TYPO3 default header is still wrong. So keep in mind that the header is case sensitive and you have to use "Content-Type".

My test works well. Fist hit and second hit (cache hit) -> both are used the content type "text/javascript".

I close this issue...

Regards,
Tim

**Comment by einpraegsam** [comment]
Thx for the time that you spent into that issue
