### ISSUE TITLE
Typo in the htaccess template

### ISSUE THREAD

**Issue by knusperpixel** [lochmueller/staticfilecache#254]
In the fluid template file that is used to generate the htaccess files for the cached files (staticfilecache/Resources/Private/Templates/Htaccess.html) there is a typo in the `headers`block.
Instead of `<ifModule mod_headers.c>` it should read `<IfModule mod_headers.c>` (uppercase I).

**Current Behavior**
The SFC-Headers are not being sent. 

**Expected behavior/output**
Show the SFC-Headers.

**Environment**
- TYPO3 version(s): 9.5.15
- staticfilecache version: 10.2.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 10.14.6

**Possible Solution**
Uppercase the letter.

**Comment by lochmueller** [comment]
Fix by commit https://github.com/lochmueller/staticfilecache/commit/e7e1d57f9e0648aef6af69adcf914c28b41814e8.

Thanks for the pull request @knusperpixel 

Hint/Note: If you write the commit message like "Fix #XXX - ...." (XX the issue and ... a short description) next time, Github will close the issue automatically after the merge.
