### ISSUE TITLE
Cache is not being regenerated

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#256]
## Bug Report

**Current Behavior**
after `flushCache` and `boostQueue` cache is not getting regenerated, changes are not visible

**Expected behavior/output**
Cache should be regenerated.

> **Environment**
> * **TYPO3 Version**: 10.4.0
> * **SFC Version**: 11.1.6
> * **PHP Version**: 7.4.5
> * **OS**: Unix
> * **Composer**: no
> * **SFC Settings**: (see below)
> * **backendDisplayMode**: both
> * **boostMode**: 1
> * **cacheTagsEnable**: 0
> * **clearCacheForAllDomains**: 1
> * **debugHeaders**: 0
> * **disableInDevelopment**: 0
> * **enableGeneratorBrotli**: 0
> * **enableGeneratorGzip**: 1
> * **enableGeneratorManifest**: 0
> * **enableGeneratorPlain**: 1
> * **hashUriInCache**: 0
> * **htaccessTemplateName**: EXT:staticfilecache/Resources/Private/Templates/Htaccess.html
> * **overrideCacheDirectory**: 
> * **rawurldecodeCacheFileName**: 0
> * **renameTablesToOtherPrefix**: 0
> * **sendCacheControlHeaderRedirectAfterCacheTimeout**: 0
> * **sendHttp2PushEnable**: 1
> * **sendHttp2PushFileExtensions**: css
> * **sendHttp2PushFileLimit**: 10
> * **useFallbackMiddleware**: 1
> * **useReverseUriLengthInPriority**: 1
> * **validHtaccessHeaders**: Content-Type,Content-Language,Link,X-SFC-Tags

**Comment by MartinH0** [comment]
Steps to reproduce:

1. set mode to Boostmode
2.0. call a page from frontend
2.1. verify its cached
3. change some content
4. run `flushCache` and `boostQueue`
5. call frontend and check if the changes applied

**Comment by MartinH0** [comment]
If I update content and Clear Cache (in TYPO3) and trigger the recreation it will also NOT recreate the pages which I have changed.
I know Boostmode if for "not touching" the static Cache, but if something changed it really should also replace the cche with an updated version.

@lochmueller do you think you can look into this?

**Comment by MartinH0** [comment]
Thank you for your reply. I will try to provide the needed Infos later.

Also: this just happens if the cache is already created!.
If I (just on the fs) delete the generated files it will properly regenerate the cache.

So I think if "Boostmode" is on it will not **overwrite** existing cache.

I will in the next hours provide the missing infos about "Queue table"

**Comment by lochmueller** [comment]
Hey @MartinH0 
please call the boostQueue with "avoid-cleanup" and check the call_date and call_result in the table after the call.

Note: There should never be the situation that only the files or only the DB representation is removed. A StaticFileCache cache entry should always be the combination of the DB record the and file!

Regards,
Tim

**Comment by MartinH0** [comment]
I did now run it with that parameter.

After `flushCache`
![before](https://user-images.githubusercontent.com/17692860/84512427-450ae500-acc8-11ea-8dfa-04527a0523d9.PNG)

After `boostQueue`
![after](https://user-images.githubusercontent.com/17692860/84512429-463c1200-acc8-11ea-87db-36f31a1143d5.PNG)


I know there there should never be that situation, but apparently there is this situation and it seems to be needed to manually delete the files as they ATM will not get overwritten.
Everything seems to be finde. But even the Cache did get recreated it will NEVER be updated once the static cache is created.

So before I run the two functions I changed something at the mainpage and since I run both commands it should have been updated but it is not. Changes are not possible in Boostmode atm.

**Comment by kathangeorg** [comment]
I think I stumbled upon the same problem. I have activated the BoostMode. I changed a cached page. Correctly the page is added to the queue.

I then run `vendor/bin/typo3 staticfilecache:boostQueue`. What I expect is that the cache entry and the cached file for the page gets deleted and regenerated now. But this is not happening.

The  cache entry and the cached file only gets removed if `$statusCode = $clientService->runSingleRequest($runEntry['cache_url']);` is not 200.

I think both should be removed before `$clientService->runSingleRequest($runEntry['cache_url']);` which will then regenerate both.

I changed runSingleRequest method in QueueService.php:

        $configuration = GeneralUtility::makeInstance(ConfigurationService::class);

        // [START]
        // Remove cache entry from database and delete cached files
        if ($configuration->get('boostMode') === '1') {
            $configuration->override('boostMode', '0');
            $cache = GeneralUtility::makeInstance(CacheService::class)->get();
            $cache->flushByTag('sfc_pageId_' . $runEntry['page_uid']);
            if ($cache->has($runEntry['cache_url'])) {
                $cache->remove($runEntry['cache_url']);
            }
            $configuration->override('boostMode', '1');
        }
        // [END]

        $configuration->override('boostMode', '0');

Then it works as I would expect. 

Is my expectation of the `boostQueue` command wrong? Or is the current behaviour in combination with BoostMode unintended?

**Comment by MartinH0** [comment]
> The cache entry and the cached file only gets removed if `$statusCode = $clientService->runSingleRequest($runEntry['cache_url']);` is not 200.
> 
> I think both should be removed before `$clientService->runSingleRequest($runEntry['cache_url']);` which will then regenerate both.

If I'm not wrong this will trigger regeneration of the cache ALL the time, right?
What I think would be good for specially big sites is: just regenerating the pages which do have changes. So if I never change a page it ofc should never be regenerated.

Means: if a page gets saved and does have some changes it should be marked as "need regenerate" and when the crawler comes it will just regenerate the pages which have been changed. Also if a page get saved it could automatically trigger the command `boostQueue` which on long term would make cronjobs for using boostmode obsolete.
Also: regenerating the saved/changed pags immediately is always faster then doing it by crons.

**Comment by kathangeorg** [comment]
> If I'm not wrong this will trigger regeneration of the cache ALL the time, right?

I don't think so. If the page is cached properly (in the database and more important in typo3temp/tx_staticfilecache as a file) and when I open it in the browser the .htaccess file redirects me to the generated html file instead of hitting the database or anything in TYPO3, right? As far as I see, I have to run the boostQueue command to trigger regeneration for all queued files, which seems not to work without makeing chan ges to the extension currently.

But I'll have to dig a little deeper, cause it's the first time I use the extension. 

It seems to work also if I move 

    $configuration = GeneralUtility::makeInstance(ConfigurationService::class);
    if ($configuration->get('boostMode') === '1') {
        $configuration->override('boostMode', '0');
        $cache = GeneralUtility::makeInstance(CacheService::class)->get();
        $cache->flushByTag('sfc_pageId_' . $runEntry['page_uid']);
        if ($cache->has($runEntry['cache_url'])) {
            $cache->remove($runEntry['cache_url']);
        }
        $configuration->override('boostMode', '1');
    }

right before `$queueService->runSingleRequest($runEntry);` in the `BoostQueueCommand.php`. So even if `runSingleRequest` method gets called anywhere outside of the boostQueue command the patch then should not affect the current behaviour.

tested with v11.1.7 on a managed root server with PHP 7.2.31
BoostMode active, all other settings not changed

**Comment by MartinH0** [comment]
@kathangeorg 
Do you talk about the file `Classes/Command/BoostQueueCommand.php` ([LINK](https://github.com/lochmueller/staticfilecache/blob/master/Classes/Command/BoostQueueCommand.php)))?
I added the code from you into [L70](https://github.com/lochmueller/staticfilecache/blob/master/Classes/Command/BoostQueueCommand.php#L70) of it but as soon as I run `boostQueue` it triggers this error:
![SFC-mod Error](https://user-images.githubusercontent.com/17692860/86501123-5494bf80-bd96-11ea-920f-1979452c5004.PNG)

**Comment by kathangeorg** [comment]
@MartinH0 

Looks like you forgot to add the corresponding use statements:

    use SFC\Staticfilecache\Service\ConfigurationService;
    use SFC\Staticfilecache\Service\CacheService;

I run the commands from terminal. Don't think it makes a difference, but works just fine in my project.

I also ended up implementing a new Command (extending the BoostQueueCommand) with the changes in one of my own extensions.

**Comment by MartinH0** [comment]
True, now it works.
It also would be cool to trigger `boostQueue` directly after saving a page. Then it would be recreated immediately and not on the next cron.

**Comment by kathangeorg** [comment]
@MartinH0 good to hear.

Renewing the cache immediately sounds good at first. But if you save a page (for example if you have changed the title), all pages for which there is a static file cache entry are added to the queue. That can literally be hundreds on a large TYPO3 installation. In this case, a cron job probably makes more sense.

**Comment by kathangeorg** [comment]
I created a [Gist](https://gist.github.com/kathangeorg/8717a4ec0af651da59362b07cd7041f8) with a working example of my `BoostQueueCommand` extending `\SFC\Staticfilecache\Command\BoostQueueCommand`.

**Comment by MartinH0** [comment]
> Renewing the cache immediately sounds good at first. But if you save a page (for example if you have changed the title), all pages for which there is a static file cache entry are added to the queue. That can literally be hundreds on a large TYPO3 installation. In this case, a cron job probably makes more sense.

Here are 2 solutions for this:

manual changes end in one list, and all others (like `flushCache`) in another.
Or: the latest change (or the change which triggers the `boostQueue` will be handled first.

Also I have to disagree on "can literally be hundreds" if ALL changes are processed immediately they will not summon up to hundreds as they are processed when the change is happening.

**Comment by lochmueller** [comment]
Hey @MartinH0 the idea is good, but the problem is, that both information (manual changes or "other changes" & change the trigger the boost queue) are not present in the Caching Framework and it is not the way the cache purge process works :-/ 

Example: If you change the page title of a page in the first layer probably the complete cache is cleared, because the menu of every page is obselete. The caching framework do not know "the source" (that it is a change on a single page) and also not know the tecnical reason for the change (manually by a editor or automatically with e.g. a scheudler import).

**Comment by MartinH0** [comment]
@lochmueller I understand. May it the TYPO3 Core who should come up with something here to be able to directly recreate Cache much more stable and faster.

Is there any chance to get the changes made by @kathangeorg into the extension as for me this now works as it should.
May you do have a different approach in mind but actually this fixes the bug this thread is addressing

**Comment by kathangeorg** [comment]
If my solution (see: [Gist](https://gist.github.com/kathangeorg/8717a4ec0af651da59362b07cd7041f8)) would be acceptable I can of course create a Pull request for the `BoostQueueCommand.php`.

**Comment by lochmueller** [comment]
Hey @MartinH0 ,
I think the next core integration would be PSR-16 ( https://www.php-fig.org/psr/psr-16/ ). This integration has the same "problem".
@kathangeorg I will check this in the next days. Perhaps we could also add some functional tests for this. 
Regards,
Tim
