### ISSUE TITLE
EXT:crawler compatibility

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/staticfilecache#260]
First thoughts...

https://github.com/lochmueller/staticfilecache/commit/d925be8e47da0355c9ffa3ca85ac9a7dd47d8705#commitcomment-40366414

**Comment by tomasnorre** [comment]
Let me know if I can assist you in any way.

**Comment by lochmueller** [comment]
hey @tomasnorre 
I think about another solution than the replacement of the complete content https://github.com/AOEpeople/crawler/blob/master/Classes/Middleware/CrawlerInitialization.php#L54 but I don't have cool ideas :-/ Do you have this problem (switch the complete response object by some crawler meta JSON information) in other middlewares as well, because all middlewares after you, get no valid renderd content, right?
Regards,
Tim

**Comment by tomasnorre** [comment]
I'm not 100% I understand what you mean. I'm unfortunately not really into the middleware concept yet, and still a little fuzzy for me. 

I've no setup where process/middleware happens with the content after the crawler has handled it, to be honest, I have no installation with 10 LTS and the crawler either. 

I'm always working on devbox level to help those out using it in production projects. So there are for sure use cases that I unknown/missing to me.

**Comment by lochmueller** [comment]
Hey @tomasnorre ,

I try to explain. There are people that use the crawler to "warm up the cache" and also the cache for static file cache. The screenshot attached is the middleware stack. The request is done from the top to the bottom and back. This stack handle all the stuff that is needed for generate a page. You see the staticfilecache-middlewares and also the crawler Middleware.

The crawler call the page with a special header so I can identify the request https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoCrawlerCall.php#L14 and disable StaticFileCache. In the best case, I do not need to disable the cache and can create the StaticFileCache. But this is currently the problem.

The aoe/crawler-initialization middleware replace the complete content that is geenrated by TYPO3 with some meta information: https://github.com/AOEpeople/crawler/blob/master/Classes/Middleware/CrawlerInitialization.php#L82 You do this after the "$handler->handle($request);"-call. So all middlewares under yours get the valid generated content of the frontend. But all middleware up get no TYPO3 page content anymore. So it is impossible for middlewares to modify (or in my case write the content to a file) the content.

I have also no very good solution for this :-/ 

Possible solution coould be: Create a new middleware on top of the stack. Do not replace the content in the lower Middleware and just save the state that you are needed. Then replace the content in the middleware on the top. In this case all middlewares can work with the content of TYPO3.

Regards,
Tim

<img width="1365" alt="Bildschirmfoto 2020-08-27 um 10 56 32" src="https://user-images.githubusercontent.com/3907126/91419868-31e1cd00-e854-11ea-9e0b-f86ce36d57d8.png">

**Comment by tomasnorre** [comment]
Hi @lochmueller,

Thanks for the explanation. It sounds like we (Crawler) are doing something unintended, I will for sure look into this. I don't want to break functionality by doing this.

**Comment by lochmueller** [comment]
Hey everyone,
I cannot change the EXT:crawler logic in StaticFileCache and the content of the middleware is invalid/useless in Crawler execution. So I add a warning in the configuration module of StaticFileCache. Feel free to create a issue for EXT:crawler on Github.
Regards,
Tim

**Comment by tomasnorre** [comment]
Thanks for the update, I unfortunately never got to this. Have too many other issues on my plate. 

I'll create an issue on my side referencing this. Hopefully this can be solved in a good way, so that we don't break functionality of your extension.

Inputs are more than welcome, but let us continue the discussion in the crawler issue.

**Comment by tomasnorre** [comment]
I'm pretty sure I have found the issue with the crawler.

We are returning the response 
https://github.com/AOEpeople/crawler/blob/master/Classes/Middleware/CrawlerInitialization.php#L83

And not the `return $handler->handle($request);` like besically every other middelware that I have looked at, therefore we break the chain and ignores what comes after the crawler. 

I'll be starting write tests for this to make sure that it works like its intended when done.

**Comment by lochmueller** [comment]
Hey @tomasnorre 
Great! (I describde the problem already in https://github.com/lochmueller/staticfilecache/issues/260#issuecomment-681827495 ). Would be cool to solve this problem.
Regards,
Tim

**Comment by tomasnorre** [comment]
Sorry I think I was a little sleepy. Yeah, you have mentioned my suspicion a long time ago. 
Will let you know when I have something that can be tested.

**Comment by tomasnorre** [comment]
Hi @lochmueller,

Could you please tests this Crawler Branch in your setup? 
https://github.com/AOEpeople/crawler/pull/651

I cannot reproduce the error anymore.

**Comment by lochmueller** [comment]
Looks good in first view 👍

**Comment by tomasnorre** [comment]
Super. Thanks for you feedback.

**Comment by Patta** [comment]
Are there any news here? Crawler runs now, but no staticfilecache is generated.

(TYPO3 10.4.12, staticfilecache 12.0.4, crawler 9.2.2)

**Comment by lochmueller** [comment]
Do you saw any information in the StaticFileCache backend related to the pages that are not cached? Please create a new issue and I can check this...
