### ISSUE TITLE
ForceType {contentType} in Htaccess template breaks lightspeed webserver system

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/staticfilecache#262]
## Bug Report

**Current Behavior**
After updating EXT:staticfilecache from 11.1.6 to version 11.1.7, installed in a TYPO3 9.5 page running on a LiteSpeed webserver, a content encoding error is thrown by the firefox browser (chrome only shows a blank white page) when trying to open a static cached page.

**Expected behavior/output**
Same behavior as before, because it was only a minor release update, which shouldn't have any breaking changes.

**Environment**
- TYPO3 version: 9.5.19
- staticfilecache version: 11.1.7
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Development OSX 10.15.5; Webserver LiteSpeed (Provider: Serverprofis) 

**Possible Solution**
1. Remove shortly added `ForceType {contentType}` from the Htaccess.html template again
2. Release version 11.2.0 with a breaking change note about this change
3. Add a hint for lightspeed users to remove this entry by overriding the template

**Comment by mediaessenz** [comment]
This is a bug in litespeed webserver below version 5.4.8 build 2!
See https://github.com/lochmueller/staticfilecache/commit/7bfb25a51453b79894ba805e14d7d5a76273a4e0#commitcomment-40600299

**Comment by lochmueller** [comment]
Should we add some lines to the documentation: https://github.com/lochmueller/staticfilecache/blob/master/Documentation/KnownProblems/Index.rst Just send me a note which text and I will add this.
