### ISSUE TITLE
Performance problem, cf_staticfilecache and tx_staticfilecache_queue get bloated with duplicates?

### ISSUE THREAD

**Issue by j4k3** [lochmueller/staticfilecache#263]
## Bug Report

**Current Behavior**
I've been running a system in boostQueue mode for about a week. I would have expected this to be a performance gain but it's developing into more of a headache than anything else. 
I have multiple routeEnhancers that generate about 4000 pages each in two languages. I now noticed that the tables related to staticfilecache, cf_staticfilecache and tx_staticfilecache_queue keep growing bigger and bigger. There are multiple entries for every identifiers respectively cache_urls, the url of the root page has as much as 460 entries in the tx_staticfilecache_queue table.

    SELECT COUNT(*) FROM `cf_staticfilecache` ; # -> 40165
    SELECT COUNT(DISTINCT identifier) FROM `cf_staticfilecache`; # -> 7699
    SELECT COUNT(cache_url) FROM `tx_staticfilecache_queue`; # -> 36867
    SELECT COUNT(DISTINCT cache_url) FROM `tx_staticfilecache_queue`; # -> 7476

I've noticed the boostQueue runner had a queue of > 3000 pages to work on when I started it manually from the command line when in fact the system has a cronjob that constantly works on the boostQueue and no user in the backend had cleared the FrontendCache in the past week. 
My suspicion is that the boostQueue runner is grinding itself to a halt because it's trying to generate caches for these duplicate entries when the pages are in fact already cached. 

**Expected behavior/output**
A single entry per identifier/url and the columns to be keys or at least indexed in the table structure.

**Environment**
- TYPO3 version(s): 9.5.13
- staticfilecache version: 11.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: nondescript linux distribution

**Possible Solution**
Prevent duplicates in the table, better yet, make the identifier columns keys or at least create indexes in the table structure?

**Comment by j4k3** [comment]
Can I get any developer input on this? Is the described behavior by design or is this a bug? I'm asking because my installation this morning, again, has a boostQueue of 5000 entries (I guess that's a hard limit?) to work on, and the only page where someone actually made changes is lost somewhere deep in that queue.
By the way, version 8.0.x of staticfilecache was previously installed, the tables don't seem to be have grown.

**Comment by j4k3** [comment]
I applied this unique key manually to the table now, and now the boostQueue is actually reducing the amount of pages in the queue, which is, by my understanding the intended behavior.

    CREATE TABLE tx_staticfilecache_queue_TMP SELECT * FROM tx_staticfilecache_queue;
    TRUNCATE TABLE tx_staticfilecache_queue;
    ALTER TABLE tx_staticfilecache_queue ADD UNIQUE INDEX cache_url (cache_url);
    INSERT IGNORE INTO tx_staticfilecache_queue SELECT * from tx_staticfilecache_queue_TMP;
    # 38.241 entries before unique -> 7.739 entries after unique.
    # DROP TABLE tx_staticfilecache_queue_TMP;

**Comment by lochmueller** [comment]
This line should avoid double entries: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/QueueService.php#L57
Perhaps the Queue cleanup is missing in your case?

**Comment by j4k3** [comment]
It in fact is missing, thanks for the hint. But why is this even required? Shouldn't there be only a single line per identifier in the queue? Is any more documentation available on the boostQueue? How often should I run the queue cleanup?

**Comment by lochmueller** [comment]
No. There should only one "active line" per identifier. There could be multiple entries for one identifier, but there should all already crawled. The "keep & cleanup" mechanim is only for debugging. In the current version there is a default option that run the cleanup direct after the regular bootqueue task: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Command/BoostQueueCommand.php#L32

**Comment by lochmueller** [comment]
No. There is no deep documentation for the BoostQueue Topic.

**Comment by j4k3** [comment]
I just now found the time to check up on this again. At first I thought the cleanup was a different task, but I can only find a parameter in the boostQueue task, --avoid-cleanup, which is not set in my task.
I've tried to read into the code. What this does is, remove lines from the queue that have a call date. But doesn't address my problem in any way.

The updated counts for my quieres seem to be growing exponentially. _There are now over 100000 lines in the queue!_

    SELECT COUNT(cache_url) FROM `tx_staticfilecache_queue`; # -> 106770
    SELECT COUNT(DISTINCT cache_url) FROM `tx_staticfilecache_queue`; # -> 8634

**Comment by lochmueller** [comment]
Hey @j4k3 
Please send me some more information. Are there any identifiers MORE than ONCE in the list, WITHOUT a call date? (then the insert is brocken, if not, the cleanup do not work). Yes. In the current version is not seprate cleanup task anymore.

Perhaps there are some "bad" clearCacheCmds in your instance, that refill the complete cache by ome editor actions. Do you check this? You should NEVER user clearCacheCmds with "pages" or "all": https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/TceMain.html#clearcachecmd

Regards,
Tim

**Comment by j4k3** [comment]
Hi Tim @lochmueller,

the latter is the case, there are up to 400 entries for the very same identifier in the table. call_date now seems to be set on all entires. There are no clearCacheCmds in the TSconfig of pages at all. avoid-cleanup is set to false in the task configuration.

I had to fix this problem yesterday, because changes in the pages weren't updated at all anymore. Similarly to the SQL code I posted above, I've copied the table structure, added a unique key on identifier to the copy, insert-ignored into the new table, flushed the old and copied from the new. That killed the duplicates. But I've already got 21439 rows again, at 8821 distinct identifiers.

My suspicion is, that clearing the frontend cache resets the call_date on all lines and the boostQueue generates a cache for every single line, meaning the caches for all those duplicates get generated multiple times, disregarding the fact that the pages are cached after the first duplicate.

**Comment by lochmueller** [comment]
Hey @j4k3 

- Do you use version 11.1.7 or current master?
- Do you call "staticfilecache:boostQueue" command via CLI and get two outputs?
-- X items are done (perhaps not all are processed).
-- X items are removed.
- I never got any entry in the DB with a call-date if I call the CLI without the --avoid-cleanup parameter?!?!
- Perhaps your CLI task is terminated BEFORE the cleanup is executred? Could you set the limit of items to a lower number?

Regards,
Tim

**Comment by j4k3** [comment]
Hey Tim @lochmueller,

I've just checked on the projects again. The cronjob for the boostQueue is called once per minute and I additionally ran it from the command line multiple times. The queue is empty, the command exits cleanly, but the table keeps growing. I've updated to the newest version in the TER just before opening the issue, 10.1.0.

**Comment by lochmueller** [comment]
@j4k3 

If you call "staticfilecache:boostQueue" command via CLI you get two outputs status?
-- "X items are done (perhaps not all are processed)."
-- "X items are removed."

**Comment by j4k3** [comment]
Hi Tim @lochmueller,

no, these specific lines don't show up. In addition I now noticed another problem. The flushCache command does not work. When calling the command, it takes a few seconds to finish. But calling the boostQueue runner immediately afterwards, it exists with 0 pages in the queue. 
Heres the output of both commands:

    ...:~ > /html/typo3/typo3/sysext/core/bin/typo3 staticfilecache:flushCache
    ...:~ > /html/typo3/typo3/sysext/core/bin/typo3 staticfilecache:boostQueue
        0 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]
    
                                                                                                                            
      [OK] 0 items are done (perhaps not all are processed).

**Comment by lochmueller** [comment]
If `X items are removed.` is missing, then this condition is not right in your case: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Command/BoostQueueCommand.php#L78
So the cleanup is not executed in your case. Pleease check `$input->getOption('avoid-cleanup')`

**Comment by j4k3** [comment]
**EUREKA!**

    ###BoostQueueCommand.php:80
    var_dump( $input->getArgument('avoid-cleanup') );
    
            if ((int)$input->getArgument('avoid-cleanup') !== 0) {
    var_dump( 'cleanupQueue($io)'.print_r($io,true) );
                $this->cleanupQueue($io);
            }

The comparisson is the wrong way around. The cleanup is skipped when the parameter, I've changed it to:

        if (!$input->getArgument('avoid-cleanup')) {
            $this->cleanupQueue($io);
        }

...and presto. Thanks for helping me find that.

**Comment by j4k3** [comment]
I looked up the version history, this seems to have been fixed in 11. Not sure why it was different for me. I may have had the BoostQueueCommand.php file open from debugging and overwritten it in the newer versions. However the problem seems fixed now, thanks for the help.
