### ISSUE TITLE
Configuration Test fails if typo3-secure-web is used

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/staticfilecache#272]
## Bug Report

**Current Behavior**
In installations with installed typo3-secure-web package Configuration Test fails with this error:
We couldn't find the StaticFileCache configuration in the htaccess file. Perhaps you configure the rules in the Webserver or do not use an Apache webserver. But: In most cases the configuration is missing!! (Note: We search for "SFC_FULLPATH" in this file)

**Expected behavior/output**
This error should not appear, because the configuration is correct

**Environment**
- TYPO3 version: 9.5.22
- staticfilecache version: 11.1.7 - master
- helhum/typo3-secure-web: 0.2.11
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 10.15.7

**Possible Solution**
a) Do not use Enviroment::getPublicPath() in installations using typo3-secure-web, because the returned path points to the "private" directory, where no .htaccess exists.
b) Add a symlink from public/.htaccess to private/.htaccess

**Comment by lochmueller** [comment]
Hey @mediaessenz 
I cannot check the existence of "typo3-secure-web" because it is a composer package. I suggest to create the symlink by yourself. Checking the "getPublicPath" is the right path to check. I will add a note in the error message.
Regards,
Tim
