### ISSUE TITLE
Class 'SFC\Staticfilecache\Service\ManifestService' not found

### ISSUE THREAD

**Issue by spoonerWeb** [lochmueller/staticfilecache#274]
## Bug Report

After updating the extension to latest 12.0.2, I get the exception `Class 'SFC\Staticfilecache\Service\ManifestService' not found` when accessing any frontend page.
When searching the code, the class should be instantiiated in ManifestGenerator, but the class really does not exist.

**Current Behavior**
Exception is thrown.

**Expected behavior/output**
Exception is not thrown, extension works as expected

**Environment**
- TYPO3 version(s): 10.4.9
- staticfilecache version: 12.0.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: ddev 1.15.3

**Possible Solution**
Either create ManifestService again or change the code to work without this class

**Comment by lochmueller** [comment]
Good point. Thanks for reporting. Fixed in master and v12.0.3 is on the way to TER 👍
