### ISSUE TITLE
Exception 'Header value can not be an empty array.'

### ISSUE THREAD

**Issue by spoonerWeb** [lochmueller/staticfilecache#276]
## Bug Report

I have an AJAX request which returns stuff from inside a Middleware.
This Middleware is configured to run after the staticfilecache Middleware classes.

The exception `Header value can not be an empty array.` is thrown because in PrepareMiddleware it may happen that the $cacheTags are an empty array.

**Current Behavior**
Exception is thrown when no $cacheTags defined.

**Expected behavior/output**
No exception.

**Environment**
- TYPO3 version(s): 10.4.9
- staticfilecache version: 12.0.3
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: ddev 1.15.3

**Possible Solution**
Check if `$cacheTags` is not empty, then set the headers.

**Comment by lochmueller** [comment]
Hey @spoonerWeb 
Thanks for the direct pull request. Should I release a new version or do you have more cool stuff/fixes for the extension before :) 
Regards,
Tim

**Comment by spoonerWeb** [comment]
Hey @lochmueller,

for now it works on my v10 website. I don't think that there will come some more PRs until Monday.
Next week more people will test it. Let's see.
It's your thing if you want to release a new version. I can deal with it by using composer. ;)

Regards,
Thomas
