### ISSUE TITLE
Sitemap.xml has wrong Content-Type if fallback middleware is enabled

### ISSUE THREAD

**Issue by KreativeKrise** [lochmueller/staticfilecache#278]
## Bug Report

**Current Behavior**
If I the `fallback middleware` is enabled, then the cached version of the sitemap.xml has the wrong Content-Type.

enabled: Content-Type: text/html; charset=utf-8
disabled: Content-Type: application/xml;charset=utf-8

**Expected behavior/output**
Cached version of sitemap.xml should be delivered with `Content-Type: application/xml;charset=utf-8`.

**Environment**
- TYPO3 version(s): 10.4.8
- staticfilecache version: 11.1.7
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian 9 with Plesk 17.8

**Comment by lochmueller** [comment]
Thanks for reporting. The bug is fixed in the current version (currently dev master).

Regards,
Tim
