### ISSUE TITLE
EXT:solr indexing problem, when useFallbackMiddleware is enabled

### ISSUE THREAD

**Issue by akoenig-clickstorm** [lochmueller/staticfilecache#279]
## Bug Report

**Current Behavior**
EXT:solr indexing should work with useFallbackMiddleware on cached pages. But an indexing error occures:

```
1319116885: RuntimeException: Failed to execute Page Indexer Request. See log for details. Request ID: 5fcdf62a2d2c8 in /var/www/html/projekte/dpfa/website/site-9/public/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php:221
Stack trace:
#0 /var/www/html/projekte/dpfa/website/site-9/public/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php(171): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerRequest->getUrlAndDecodeResponse('http://dpfa-aug...', Object(ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerResponse))
#1 /var/www/html/projekte/dpfa/website/site-9/public/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(163): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerRequest->send('http://dpfa-aug...')
```

**Expected behavior/output**
- I would expect, that useFallbackMiddleware is ignored, when the htaccess rules for staticFileCache are found. "Use the fallback middleware to deliver the static file, if there is no .htaccess configuration"
- Indexing with EXT:solr should work with useFallbackMiddleware on cached pages

**Environment**
- TYPO3 version: 9.5.23
- staticfilecache version: 11.1.7
- EXT:solr version: 11.0.3
- Apache Solr: 8.5.1
- solrconfig.xml & schema.xml: tx_solr-11-0-0--20200415
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux 5.4.0
- PHP 7.2

**Possible Solution**
Disable useFallbackMiddleware and make sure to have the current StaticFileCache htaccess rules enabled.
```
# Disable cache for EXT:solr indexing requests
RewriteCond %{HTTP:X-Tx-Solr-Iq} .+
RewriteRule .* - [E=SFC_HOST:invalid-host]
```

Related issue: #200

**Comment by lochmueller** [comment]
Hey @akoenig-clickstorm ,

> I would expect, that useFallbackMiddleware is ignored, when the htaccess rules for staticFileCache are found. "Use the fallback middleware to deliver the static file, if there is no .htaccess configuration"

No. This is exact the reason of the Fallback. There is a missing Cache rue for the Fallback middleware. I will add this in a few minutes....

Regards,
Tim
