### ISSUE TITLE
Generated .htaccess causes Error 500 in Apache2

### ISSUE THREAD

**Issue by jacobsenj** [lochmueller/staticfilecache#280]
## Bug Report

**Current Behavior**
After the generation of the static template file and the related .htaccess file an error 500 is raised when reloading the page.

**Expected behavior/output**
The page should be displayed as before, but from the static file cache instead.

**Environment**
- TYPO3 version(s): 9.5 LTS
- staticfilecache version: 11.1.7
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 18.04.5 LTS

**Possible Solution**
Slashes escaping the quotes need to be added to the header value(s). Especially the link value in this case:

is
```
ForceType text/html




	<IfModule mod_headers.c>
		
				Header set Content-Type "text/html; charset=utf-8"
		
				Header set Content-Language "de"
		
				Header set Link "</typo3conf/ext/site/Resources/Public/Build/runtime.685dcb44.js>; rel="preload"; as="script",</typo3conf/ext/site/Resources/Public/Build/main.f9f9e230.js>; rel="preload"; as="script",</typo3conf/ext/site/Resources/Public/Build/style.a129c8b7.css>; rel="preload"; as="style""
		
				Header set X-SFC-Tags "tx_news, tx_news_uid_68, tx_news_uid_69, tx_news_uid_34, tx_news_pid_5, pageId_1, articles, news, sfc_pageId_1, sfc_domain_site_localhost"
		
	</IfModule>
```

should be
```
ForceType text/html




	<IfModule mod_headers.c>
		
				Header set Content-Type "text/html; charset=utf-8"
		
				Header set Content-Language "de"
		
				Header set Link "</typo3conf/ext/site/Resources/Public/Build/runtime.685dcb44.js>; rel=\"preload\"; as=\"script\",</typo3conf/ext/site/Resources/Public/Build/main.f9f9e230.js>; rel=\"preload\"; as=\"script\",</typo3conf/ext/site/Resources/Public/Build/style.a129c8b7.css>; rel=\"preload\"; as=\"style\""
		
				Header set X-SFC-Tags "tx_news, tx_news_uid_68, tx_news_uid_69, tx_news_uid_34, tx_news_pid_5, pageId_1, articles, news, sfc_pageId_1, sfc_domain_site_localhost"
		
	</IfModule>
```

**Additional context**
Error messsage is

```
.htaccess: Header has too many arguments
```

this is due to the unescaped quotes in the Header set Link value.

I fixed it for me using this patch (composer patches):
```patch
--- web/typo3conf/ext/staticfilecache/Classes/Generator/HtaccessGenerator.php	(date 1611136466809)
+++ web/typo3conf/ext/staticfilecache/Classes/Generator/HtaccessGenerator.php	(date 1611136466809)
@@ -94,7 +94,7 @@
         $result = [];
         foreach ($headers as $name => $values) {
             if (in_array($name, $validHeaders)) {
-                $result[$name] = implode(', ', $values);
+                $result[$name] = addslashes(implode(', ', $values));
             }
         }
```

**Comment by lochmueller** [comment]
Hey @jacobsenj 
it is allready fixed in the current version:
https://github.com/lochmueller/staticfilecache/commit/a5ab098e13e2a377fb490090bfc999595d9d1a25#diff-717c52592d9fd56f138171eb14ab03b634be6d0ff195001eef1ac2a89fa6c929
https://github.com/lochmueller/staticfilecache/commit/f92ac27271f53f2caeacab9c30bcd16f943476a4#diff-717c52592d9fd56f138171eb14ab03b634be6d0ff195001eef1ac2a89fa6c929

I suggest patch the version in your project and upgrade to StaticFileCache 12.x after the next TYPO3 update.

I will close this issue. Sorry... but due the limit of time there will be no bug fixes for old releases.

Regards,
Tim
