### ISSUE TITLE
Error on Cash Flush in Maintainance Module

### ISSUE THREAD

**Issue by kledo-34** [lochmueller/staticfilecache#281]
If I flush the cash in the Maintainance Module with Boost Mode activated I get the following error:

[CRITICAL] request="907f872aef521" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function SFC\Staticfilecache\Service\QueueService::__construct(), 0 passed in **mypath**/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3431 and exactly 4 expected | ArgumentCountError thrown in file **mypath**/typo3conf/ext/staticfilecache/Classes/Service/QueueService.php in line 50. Requested URL: **myurl**/typo3/install.php?install[controller]=maintenance&install[context]=backend&install[action]=cacheClearAll - {"TYPO3_MODE":"BE","exception":{}}

**Expected behavior/output**
No error on flushing cash (I do not get one by flushing cashes in any other way, it's only in the Maintainance module)

**Environment**
- TYPO3 version: 10.4.10
- staticfilecache version: 12.0.4
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- Linux

Edit: The exact same error sometimes shows up when flushing cache in the top bar with Flush all cashes under flush frontend cash, but it does not always occur here

**Comment by brotkrueml** [comment]
I encounter the same problem. When flushing the cache in the maintenance module the error occurs. Also removing var/cache/ manually throws the error when flushing again.

**Environment**

- TYPO3 version: 10.4.13
- staticfilecache version :12.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- Linux

**Comment by lochmueller** [comment]
Strange... the constructor injection do not work in this case: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/QueueService.php#L50 Perhaps we cannot use constructor injection in this case. I/we have to check this...

**Comment by brotkrueml** [comment]
I set "public: true" for the QueueService in the Services.yaml file, mostly this helps, but not in this case.

See also: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/DependencyInjection/Index.html#errors-resulting-from-wrong-configuration

Perhaps a dependency that should be injected into the QueueService is not public, set also these as "public: true", but same result :-( Checked also the dependencies of the dependencies, but they looked good, as they are core classes ready for injection.

**Comment by MartinHotmann** [comment]
Same error for me, but now on:

TYPO3: v11.1.1
PHP: 7.4
SFC: 12.2.0

Error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function SFC\Staticfilecache\Service\QueueService::__construct(), 0 passed in /var/www/domain.de/httpdocs/www/typo3_src-11.1.1/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3224 and exactly 4 expected | ArgumentCountError thrown in file /var/www/domain.de/httpdocs/www/typo3/typo3conf/ext/staticfilecache/Classes/Service/QueueService.php in line 39. Requested URL: https://www.domain.de/typo3/install.php?install[controller]=maintenance&install[action]=cacheClearAll`

Rebuilding on TYPO3 v11.1.1 does not work either. No folder in `typo3temp/` will be created.

**Comment by lochmueller** [comment]
The problem with the QueueService is solved in current master.

@MartinHotmann also your described problem. Note: Your Screenshot is not related to your description. The screenshot seems to be a EXT:flux bug.
