### ISSUE TITLE
Static files not written in combination with extension crawler

### ISSUE THREAD

**Issue by Patta** [lochmueller/staticfilecache#282]
## Bug Report

**Current Behavior**
Static files of crawled pages are not written.

**Expected behavior/output**
Static files of crawled pages are written.

**Environment**
- TYPO3 version(s): 10.4.12
- staticfilecache version: 12.0.4
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux
- crawler version: 9.2.2

**Possible Solution**
no

**Additional context**
reproduce:
- add crawler config (via backend) to root page without any field filled except the name
- flush queue: crawler:flushQueue all
- build queue: crawler:buildQueue 2342 sitename --depth=9 --mode=queue
- process queue: crawler:processQueue

Issue exists regardless of whether a fegroup is set for the request in the crawler config or not.

Do you saw any information in the StaticFileCache backend related to the pages that are not cached? No.

Additional the StaticFileCache module message due to bug #260 can now be removed.

**Comment by lochmueller** [comment]
Hey @Patta 
this is the current behavior. Do you try to set this condition to false? https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoCrawlerCall.php#L18
If this works and files are generated, please check the generated files. In the last crawler versions a "configuration JSON" was stored in the cache, because EXT:crawler replace the output of the rendering process.
Regards,
Tim

**Comment by Patta** [comment]
@lochmueller i deactivate the NoCrawlerCall Rule in https://github.com/lochmueller/staticfilecache/blob/master/Classes/Configuration.php#L142  and the files are generated.
The index.gz/index contains in fact a "configuration JSON" like:
`a:4:{s:7:"running";b:1;s:10:"parameters";a:3:{s:3:"url";s:57:"https://removed/";s:16:"procInstructions";a:1:{i:0;s:0:"";}s:15:"procInstrParams";a:0:{}}s:3:"log";a:1:{i:0;s:13:"User Groups: ";}s:4:"vars";a:3:{s:2:"id";i:11010;s:7:"gr_list";s:4:"0,-1";s:8:"no_cache";b:0;}}`
I thought according to the issue https://github.com/AOEpeople/crawler/issues/642 that it would work now.

**Comment by lochmueller** [comment]
Sorry... I don't use crawler very much. I think crawler still replace the content output in the Middleware Stack. I use my own tool sometime if I want to recrawl the page for example in deployment processes: https://github.com/lochmueller/seocli

**Comment by lochmueller** [comment]
@Patta 
I will close this issue. Currently, the rule is right, because EXT:crawler still modified the content in the Middlewar stack. Perhaps create a new issue in EXT:crawler related to this?!
Regards,
Tim

**Comment by Patta** [comment]
Thanks for your Feedback. I also use your tool for cache warmup on deployment and daily at night. 
But for re-cache new/edited content/pages etc. crawler is used.
For now i can live with that. Greetz.

**Comment by cweiske** [comment]
crawler since version 11.0.1 returns the proper response: https://github.com/tomasnorre/crawler/commit/8a9b896721f479d7babc4bb5920536e8124a1797
