### ISSUE TITLE
TYPO3 8.7.40 removes IdnaConvert which is used by staticfilecache

### ISSUE THREAD

**Issue by linkpool** [lochmueller/staticfilecache#287]
## Bug Report

**Current Behavior**
TYPO3 8.7.40 removes IdnaConvert which is used by staticfilecache

**Environment**
- TYPO3 version(s): 8.7.40
- staticfilecache version: 9.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: any

**Possible Solution**
none

**Comment by lochmueller** [comment]
Hey @linkpool 
thanks for reporting... StaticFIleCache version 9.x is very old. There will be no new versions for old releases (also TYPO3 v8 is not supported anymore). In the current version the Converter is not used anymore.
So I close this issue. I suggest to upgrade your TYPO3 installation (also StaticFileCache) or fix this problem in a fork by yourself.
Regards,
Tim
