### ISSUE TITLE
Error since TYPO3 8.7.40 (\Mso\IdnaConvert\IdnaConvert not found)

### ISSUE THREAD

**Issue by Raidri** [lochmueller/staticfilecache#288]
Hi,

TYPO3 has removed in TYPO3 8.7.40 this one:
2021-03-15 a3592edf13 [BUGFIX] Replace algo26-matthias/idna-convert with native PHP functionality (thanks to Andreas Fernandez)

which now runs in an error with staticFileCache ( Class \Mso\IdnaConvert\IdnaConvert not found).

**Comment by lochmueller** [comment]
Hey @Raidri 
already reported yesterday: https://github.com/lochmueller/staticfilecache/issues/287 Please check the comment in the other ticket.
I close this issue.
Regards,
Tim
