### ISSUE TITLE
Cronjob throws error / Type declaration wrong? 

### ISSUE THREAD

**Issue by qualle** [lochmueller/staticfilecache#293]
## Bug Report

**Current Behavior**
The cronjob of my web projects sends me this Error:
`Uncaught TYPO3 Exception syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)
thrown in file /var/***/typo3conf/ext/staticfilecache/Classes/Configuration.php
in line 55`

**Expected behavior/output**
No error. 

**Environment**
- TYPO3 version(s): 10.4.15
- staticfilecache version: 12.2.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux rs243945 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
- PHP Version 7.4.13

**Possible Solution**
None.

**Additional context**
Even when I turn of all Scheduler Tasks, the Error remains. 
This is the code line but it seems correct?
![ggkcjmdlfbkfdnpg](https://user-images.githubusercontent.com/339447/117450655-d10da700-af41-11eb-8286-860701977167.png)

**Comment by lochmueller** [comment]
Hey @qualle 
the type is PHP 7.4 compatible: https://stitcher.io/blog/new-in-php-74#typed-properties-rfc
I think you execute the TYPO3 CLI with an old PHP version. Could you check this?
Regards,
Tim

**Comment by qualle** [comment]
Hi Tim, thank you for your fast reply. That was exact the case, CLI did run with PHP 7.3.
