### ISSUE TITLE
Pass crossorigin attribute to the link header

### ISSUE THREAD

**Issue by christophlehmann** [lochmueller/staticfilecache#296]
## Feature Request

I have this in my dom `<link rel="preload" as="font" href="/typo3conf/ext/styleguide/Resources/Public/assets/fonts/fontxy.woff" crossorigin>`

with `sendHttp2PushFileExtensions: 'woff'` the font arrives in the `Link` header, but the `crossorigin` attribute is missing, so Chrome does not use it and lighthouse complains.

I can try to fix it.

**Comment by lochmueller** [comment]
"I can try to fix it." -> would be cool.
I think we have to change the complete abstraction to handle this. Current integration found here: https://github.com/lochmueller/staticfilecache/tree/master/Classes/Service/HttpPush

**Comment by lochmueller** [comment]
There are no new about the problem and I close this old issue.

**Comment by chesio** [comment]
Hi Tim,

this is still a problem - I wonder whether no one is using preloading for font files..? :-)

Would you accept PR for this? If yes, should I open new issue?

**Comment by lochmueller** [comment]
Hey @chesio ,
feel free to send a PR (perhaps open a new issue before).
Was not on the prio high list in 2022....
Regards,
Tim
