### ISSUE TITLE
Documentation for dummies

### ISSUE THREAD

**Issue by ursbraem** [lochmueller/staticfilecache#298]
Proposal for beginner setup instructions. Maybe you'd want to integrate some of it into the docs at the beginning @lochmueller ?

* Install staticfilecache via composer
* Enable `basic.debugHeaders` in the extension settings
* Call some pages in a different browser than the one you're logged into TYPO3
* Check the staticfilecache module - are there cached pages listed? good!
* Check the your `typo3temp/tx_staticfilecache` folder for content. Is there content? Good!
* Check the statcifilecache configuration test in the backend and follow instructions there if needed.
* Make sure your public .htaccess file contains the code from https://github.com/lochmueller/staticfilecache/blob/master/Documentation/Configuration/Htaccess.rst at the end.
* Make sure typo3temp/tx_staticfilecache is accessible publicly.
* In case you use `helhum/typo3-secure-web` instruct .htaccess and Static File cache to use the `typo3temp/assets` directory which is automatically symlinked by typo3-secure-web by modifying the following lines as such:
 
.htaccess:
```
 # Full path for redirect
RewriteRule .* - [E=SFC_FULLPATH:typo3temp/assets/tx_staticfilecache/%{ENV:SFC_PROTOCOL}_%{ENV:SFC_HOST}_%{ENV:SFC_PORT}%{ENV:SFC_URI}/index]

 # Do not allow direct call the cache entries
RewriteCond %{ENV:SFC_URI} ^/typo3temp/assets/tx_staticfilecache/.*
```
LocalConfiguration.php:
```
'overrideCacheDirectory' => '../typo3-secure-web/typo3temp/assets/tx_staticfilecache/',
```

* In the different browser than the one you're logged into TYPO3, hard reload the pages you previously called and check for `x-sfc` headers. Loaded? Good! `x-sfc-state: StaticFileCache - via Fallback Middleware`? Ok, but there's something missing in the .htaccess. ``x-sfc-state: TYPO3 - already in cache` Perfect! You're set.
* In your code, make sure there are no USER_INT objects on pages you want to be cached. A single statically-uncacheable element will make the entire page statically-uncacheable.

**Comment by ursbraem** [comment]
Added working paths for typo3-secure-web config

**Comment by lochmueller** [comment]
Hey @ursbraem 
nice idea. Feel free to send a PR. I would suggest avoiding the `helhum/typo3-secure-web` add-ons in the beginning guide, because the extension is another third party extension. Furthermore, the mechanism is part of the TYPO3 v12 core, I think. But feel free to add the typo3-secure-web part to a separate section.
Regards,
Tim

**Comment by ursbraem** [comment]
@lochmueller done! I hope the PR into `master` is correct.

**Comment by lochmueller** [comment]
Hey @ursbraem ,
Thanks for add-on. PR is merged and I close this issue...
Regards,
Tim
