### ISSUE TITLE
Ignore print css files in preload header

### ISSUE THREAD

**Issue by christophlehmann** [lochmueller/staticfilecache#299]
## Feature Request

i think it does not really make sense to preload css files having `media="print"` since they are not used most of the time. 

IMHO they should be excluded by default.

**Comment by lochmueller** [comment]
Good point, but not so easy integrated in the current structure. I will check this in the future: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/HttpPush/StyleHttpPush.php

**Comment by chesio** [comment]
Note that use of `media="print"` makes it very simple to load CSS asynchronously: https://www.filamentgroup.com/lab/load-css-simpler/ In such case one may still want to preload CSS assets with `media="print"`.

**Comment by xerc** [comment]
> one may still want to preload CSS assets with `media="print"`

@chesio this may interfere with the browser ; cleaner solution ..
`<link rel="preload" as="style" href="/path/file.css" onload="this.onload=null;this.rel='stylesheet'">`

**Comment by xerc** [comment]
https://github.com/lochmueller/staticfilecache/commit/23255a663c08335d925def26c122df5c5024581c

**Comment by lochmueller** [comment]
Thanks for the fix @xerc 
Last part would be fixing the tests ( composer test  ). I will check this later...
