### ISSUE TITLE
releases for TER

### ISSUE THREAD

**Issue by DanielRuf** [lochmueller/staticfilecache#30]
So far there were no new releases at https://extensions.typo3.org/extension/nc_staticfilecache/

Where can we find the current extension in the TER?

**Comment by DanielRuf** [comment]
Also here seems to be nothing https://extensions.typo3.org/extension/staticfilecache/

**Comment by lochmueller** [comment]
There is no TER release. TYPO3 suggest to use composer and EXT:staticfilecache is a composer only extension. Please use:
composer require lochmueller/staticfilecache

Regards,
Tim

**Comment by lochmueller** [comment]
Packagist:
https://packagist.org/packages/lochmueller/staticfilecache

**Comment by DanielRuf** [comment]
I saw it. So there is no public listing but the packagist one? Thanks for the information.

**Comment by lochmueller** [comment]
Yes.

You are welcome,
Tim
