### ISSUE TITLE
[Feature] Exclude page types

### ISSUE THREAD

**Issue by ste101** [lochmueller/staticfilecache#300]
It would be great if I could exclude page types like sitemap or RSS feeds from being cached.

**Comment by lochmueller** [comment]
Hey @ste101 
You could disable SFC by setting `tx_staticfilecache.disableCache = 1` and you could set this by condition in TS. So your feature requirement is actually possible now. The TS solution is much more flexible then a separated typeNum-check in the SFC extension.
Regards,
Tim

**Comment by lochmueller** [comment]
hey @ste101 
here the documentation for the condition: https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Conditions/Index.html#gettsfe

```
[getTSFE().type == YOUR_TYPE_HERE]
tx_staticfilecache.disableCache = 1
[global]
´´´

**Comment by ste101** [comment]
Thanks for your fast answer.
This is not what I ment, I could not find any information about `tx_staticfilecache.disableCache` within the staticFileCache docu and I had to use `config.tx_staticfilecache.disableCache`

**Comment by lochmueller** [comment]
I add some documentation. Feel free to send a pull request next time 👍

**Comment by ste101** [comment]
Thank you very much
