### ISSUE TITLE
If Composer install it has an issue

### ISSUE THREAD

**Issue by dustin-webschuppen** [lochmueller/staticfilecache#306]
Everytime i install it with composer their is an issue in HtaccessConfigurationService.php

foreach ($this->getHtaccessPaths() as $path) {
            if (is_file($path)) {
                $content = GeneralUtility::getUrl($htacessFile);
                if ((bool) strpos($content, 'SFC_FULLPATH')) {
                    return true;
                }
            }
        }
        
        
        Their is a variable $htacessFile.
        
        Do you have the same problem?

"lochmueller/staticfilecache": "^12.3",

**Comment by lochmueller** [comment]
Already fixed in current master: https://github.com/lochmueller/staticfilecache/commit/20c2ee72cbb26bd4527f56122cd2ad1caa10e573

I close this issue and push a new bugfix release to github.

**Comment by lochmueller** [comment]
Fixed in 12.3.2
