### ISSUE TITLE
Does it work on multi-tier system and a shared file system with multiple nodes

### ISSUE THREAD

**Issue by bh-teufels** [lochmueller/staticfilecache#316]
Does the Extension work on t work on multi-tier system and a shared file system with multiple nodes.
We have a typo3 Installation on a Cloud Hosting with multiple "Webserver Nodes"
We already uses b13/distributed-locks for Redis Locking mechanism to store the locks in a (shared) Redis database.
Maybe needed b13/distributed-flysystem to synchronize typo3temp though all "nodes"?

**Comment by lochmueller** [comment]
Hey @bh-teufels 
Yes the extension works on multi-tier system. Keep in mind, that one StaticFileCache entry consist of a DB & a file representation. That means the folder have to share in the same way as the database is shared.

I will close this issue. If there are concrete problems, feel free to create bug issues. Open questions in the #ext-staticfilecache channel in Slack.

Regards,
Tim

Note: If you scale your infrastructure with multiple nodes, perhaps it is easier to use only the nodes for scaling and no TYPO3 StaticFileCache. The strengths of SFC are more in the single host server env...
