### ISSUE TITLE
Undefined array key "TSFE"

### ISSUE THREAD

**Issue by itx-stefanie-doell** [lochmueller/staticfilecache#317]
## Bug Report

**Current Behavior**
I installed the extension right now, added the rules in the .htaccess and 
set the debugHeaders configuration. When I open a page in the frontend, I get the following message:

YPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'Undefined array key "TSFE"', '/var/www/html/public/typo3conf/ext/staticfilecache/Classes/Cache/Listener/ForceStaticCacheListener.php', 32)

This applies for all kind of pages, filled with content or completely empty.

**Environment**
- TYPO3 version: 11.5.3
- staticfilecache version: 12.3.3
- php Version: 8.0
- TYPO3 Context: Development

Thank you very much for your help.

**Comment by lochmueller** [comment]
Fixed in current master.
