### ISSUE TITLE
Error in Backend module

### ISSUE THREAD

**Issue by itx-stefanie-doell** [lochmueller/staticfilecache#318]
Thank you very much that you fixed my last issue so impressively fast!
Unfortunately I now have another problem - probably also because of the 8.0 php version. 
Thank you very much for having a look at it.

## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

After successfully caching of a frontend page, I opened the staticfilecache backend module and receved the following messange:
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "explanation" in /var/www/html/public/typo3conf/ext/staticfilecache/Classes/Controller/BackendController.php line 156

**Environment**
- TYPO3 version(s 11.5
- php 8.0

**Comment by lochmueller** [comment]
Thanks for reporting @itx-stefanie-doell 
Fixed with next commit...
