### ISSUE TITLE
Exception with PHP 8.0

### ISSUE THREAD

**Issue by topfender** [lochmueller/staticfilecache#321]
Hey

I get the following exception in fe:
PHP Warning: Undefined array key "TSFE" in /var/www/html/htdocs/typo3conf/ext/staticfilecache/Classes/Cache/Listener/StaticCacheableListener.php line 23

**Environment**
- TYPO3: 11.5.4
- staticfilecache version: 12.4.0
- Composer Mode
- PHP 8.0

**Comment by lochmueller** [comment]
Thanks @topfender  for reporting. Please check current master. If the problem is fixed completely I will release a new version...

**Comment by topfender** [comment]
Could you add the ($GLOBALS['TSFE'] ?? null) to all conditions where $GLOBALS['TSFE'] is checked. I get similar errors for example in the Rule/NoNoCache.php or Rule/NoWorkspacePreview.php.
![grafik](https://user-images.githubusercontent.com/13070580/149619962-4a3d614f-91d5-4384-95a5-6fdd68a8a022.png)


I really don't get why the TSFE key is sometimes not present. I think those PHP 8 warning are really annoying :D

**Comment by lochmueller** [comment]
Hey @topfender 
Thanks... I fixed this in current master.
In the future TSFE part should be dropped, because the TSFE is also part of the request object.
Regards,
Tim

**Comment by Physikbuddha** [comment]
The same warning also appears in:

- staticfilecache/Classes/Cache/Rule/ValidPageInformation.php line 26
- staticfilecache/Classes/Cache/Rule/NoNoCache.php line 24
- staticfilecache/Classes/Cache/Rule/LoginDeniedConfiguration.php line 24
- staticfilecache/Classes/Cache/Rule/NoIntScripts.php line 24
