### ISSUE TITLE
https://github.com/lochmueller/staticfilecache/releases stuck at 12.2.0

### ISSUE THREAD

**Issue by criwe** [lochmueller/staticfilecache#323]
Hi!

https://github.com/lochmueller/staticfilecache/releases <- is stuck at 12.2.0.
Would be great to get infos about the newer releases.
Regards,
Christoph

**Comment by lochmueller** [comment]
Hey @criwe ,
all "Bugfix only" releasees have no special release notes: https://github.com/lochmueller/staticfilecache/tags
You can check technical integration details in the commit history: https://github.com/lochmueller/staticfilecache/commits/master
Regards,
Tim

**Comment by lochmueller** [comment]
FYI... this is the compare between the 12.2.0 and the newest version:
https://github.com/lochmueller/staticfilecache/compare/12.2.0...12.4.1

**Comment by criwe** [comment]
Cool, thanks!
