### ISSUE TITLE
Caching broken

### ISSUE THREAD

**Issue by hannesbochmann** [lochmueller/staticfilecache#327]
## Bug Report

**Current Behavior**
There is a missing namespace import in SFC\Staticfilecache\Cache\Rule\ValidDoktype for TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController. Therefore the rule will always result in a skipped processing as $GLOBALS['TSFE'] will never be the correct instance,. 

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 10.4.23
- staticfilecache version: 12.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
Pull request will be provided.

**Comment by lochmueller** [comment]
Thanks for reporting. I will push a new version in a few minutes.
