### ISSUE TITLE
Call to a member function stdWrapValue() on null

### ISSUE THREAD

**Issue by nwm-dev** [lochmueller/staticfilecache#333]
## Bug Report

**Current Behavior**
In some instances this error gets thrown on a subpage (it works after a fresh cache clear, but after the first access the error persists on subsequent calls). 

**Expected behavior/output**
The page showing up without errors

**Environment**
- TYPO3 version: 11.5.6
- staticfilecache version: 12.4.4
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Additional comments**
The problem with this error is I can't reliably reproduce it in a fresh installation or understand what exactly triggers this behaviour because it only seems to happen to a specific subpage (which by now has no content at all). Further down in the trace stack the error is triggered in staticfilecache/Classes/Cache/Listener/ForceStaticCacheListener.php line 41. The trace stack also suggests it has something to do with the pageTitleSeparator, but I don't recall any special setting for the pageTitleSeparator. I tried searching through previous reports but didn't seem to find a similar result. Any help is much appreciated.

**Comment by lochmueller** [comment]
Hey @nwm-dev 
Do you saw the notice on the "force static file cache" field in the backend ;-) => "Force the static cache generation (NOTE: This result in undefined states. Do not enable this field for editors, do not use in production and do not report bugs related to this feature!)"

Please do not use the "force static file cache" function.
Does this information help? StaticFileCache cannot control the states of INT script loading... and there is no direct API to handle this.

Regards, Tim

**Comment by nwm-dev** [comment]
Hello @lochmueller 
This seems to do the trick, thank you! Should I only uncheck this for pages that load INT scripts or with all pages altogether? What would be the use case for (un)checking this option? (You can close this issue afterwards)

Best regards

**Comment by lochmueller** [comment]
You should always uncheck this option! If there are *_INT objects, the page is not cachable. The checkbox is only for testing. If you want a fully cachable page, do not use *_INT object and fix the plugins/typoscript that use *_INT scripts.

Regards,
Tim
