### ISSUE TITLE
Status "User or group are set" without any fe_uers

### ISSUE THREAD

**Issue by topfender** [lochmueller/staticfilecache#34]
Hey there, I'm not quiet sure if this really is an issue in the extension or a misconfiguration in my system. I'm hoping you can help me to solve this. I don't use any frontend users, but I get the message "User or group are set" in info module on every page. I tried it in a separate browser without active backend session.  I digged a little deeper and found this:

In NoUserOrGroupSet.php the following method "TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->isUserorGroupSet()" checks if $GLOBALS['TSFE']->fe_user->user is an array. When I debug it, I get an Array with a few "ses_.." keys e.q. "ses_anonymous" an "ses_data".

Any idea what causes this issue?

**Comment by lochmueller** [comment]
The function desribe ```Checking if a user is logged in or a group constellation different from "0,-1"``` and also ```TRUE if either a login user is found (array fe_user->user) OR if the gr_list is set to something else than '0,-1' (could be done even without a user being logged in!)```
This is exactly the usecase. Perhaps some other extensions force this problem or break the session handling? Please run some more debugging and send me some information to check this in detail. Which process create the fe_user->user array?
Regards,
Tim

**Comment by topfender** [comment]
Looks like sysext:form is causing my problem. It stores honeypot data in this array. But I'm not sure why it is stored there. Where should the session data be stored regular and what could manipulate this?

**Comment by lochmueller** [comment]
Do you also created a core issue on forge?

**Comment by topfender** [comment]
Not yet, because I'm not sure if a misconfiguration causes this issue. I'll try a clean TYPO3 installation with form and staticFileCache this week.

**Comment by topfender** [comment]
https://forge.typo3.org/issues/83212
I hope I'll get feedback soon.

Could you try to reproduce it? I added a viewhelper with
```
$GLOBALS['TSFE']->fe_user->setKey('ses','testing',serialize([0 => 'test']));
$GLOBALS['TSFE']->fe_user->storeSessionData();
\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($GLOBALS['TSFE']->fe_user->user);
```

**Comment by lochmueller** [comment]
Hey @topfender 
I could rebuild the problem with you code example. After the storeSessionData call, the ```isUserOrGroupSet``` function return true and the cache is disabled.
Regards,
Tim

**Comment by topfender** [comment]
Sadly it seems like it's a core bug, so I'll have to wait until TYPO3 10 Release to use your extensions :D

**Comment by lochmueller** [comment]
Hey @topfender 
fixed in current master. Please check if this solve your problem. The "workaround" is documented in the rule class and the internal function check the existens of the "uid" field in the array now.
Regards,Tim

**Comment by lochmueller** [comment]
Link: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoUserOrGroupSet.php#L31

**Comment by topfender** [comment]
\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->isStaticCacheble() checks for isUserOrGroupSet(), too (Rule StaticCachable). This method also check ->isINTincScript(). Maybe you could check $frontendController->no_cache instead, because there are already separate ruls for int_scripts and userOrUsergroup.

**Comment by lochmueller** [comment]
Could you add a pull request so I can test this....
