### ISSUE TITLE
PHP version constraint in ext_emconf.php doesn't match version constraint in composer.json

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/staticfilecache#344]
## Bug Report

**Current Behavior**
PHP version constraint in ext_emconf.php doesn't match version constraint in composer.json
ext_emconf.php: 7.4.0-8.0.99
composer.json: ^7.4||^8.0

The later constaint (composer.json) allows installation under PHP 8.0 and 8.1 (up all version < 9). The constraint in ext_emconf.php only up to 8.0.99.

**Expected behavior/output**
Both constaints should be the same.

**Possible Solution**
Change contraint in ext_emconf.php to '7.4.0-8.99.99' or at least to '7.4.0-8.1.99'

**Comment by lochmueller** [comment]
Done in current master.
