### ISSUE TITLE
Pages with very long slugs are truncated

### ISSUE THREAD

**Issue by stat1x** [lochmueller/staticfilecache#345]
## Bug Report

**Current Behavior**
If a page has a very long slug, it is truncated in cf_staticfilecache.identifier and cf_staticfilecache_tags.identifier. i.e. : https://dummy-site.ddev.site/dummy/page/test-url-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue/test-url-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue/test-url-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue
The reason is that this columns are varchar(255).

**Expected behavior/output**
The pages with very long slugs should not be truncated. TYPO3 allows pages slug with 2048 chars.

**Environment**
- TYPO3 version(s): [8.7.12, 9.2.0]
- staticfilecache version: [^4.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Possible Solution**
The identifier should be encoded.

**Comment by lochmueller** [comment]
Hey @stat1x 
there is a rule that fit to this problem: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoLongPathSegment.php
As a result, the cache will not work for this URI.
The problem is not only the field-length in the DB, also the folder-name length in the file system is critical, if there are more than 255 chars.
Does the rule not work for your case?
Regards,
Tim

**Comment by stat1x** [comment]
Hi,

Thanks for the answer.

In my case the page has 254 chars.
It is located under another page that also has 254 chars.
So I don't hit this rule.

The full slug has ~800 chars.

In the cf_staticfilecache and cf_staticfilecache_tags table the identifier looks like this :
```
https://dummy-site.ddev.site/dummy/page/test-url-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-longue-lon
```

It is truncated at 255 chars.

A solution would be to increase the field-length of identifier in cf_staticfilecache and cf_staticfilecache_tags but it comes from TYPO3 core.

I tried to increase the values and it works fine but I am not sure it is the best solution.

What do you think?

**Comment by mkempe** [comment]
@lochmueller @stat1x Many thanks for your comments. Have exactly the problem as @stat1x, except that an additional exception is thrown that the indentifier field is too big to insert. It happens on chinese pages with encoded characters.

@lochmueller Many thanks for this great extension ❤️.

**Comment by lochmueller** [comment]
Added in current master.
