### ISSUE TITLE
Handle special characters in URI

### ISSUE THREAD

**Issue by j6s** [lochmueller/staticfilecache#36]
Currently, the RAW URI is used as cache identifier in `\SFC\Staticfilecache\StaticFileCache`. This works well as long as the whole URI is alphanumerical + a couple of extra chars. If however the URI contains special characters, `TYPO3\CMS\Core\Cache\Frontend\AbstractFrontend` throws an exception when validating the cache key against the regex in `TYPO3\CMS\Core\Cache\Frontend\FrontendInterface::PATTERN_ENTRYIDENTIFIER`.

In our case there is a korean subpage at `http://domain.com/kr/뉴스/프레스-릴리즈/` which contains special characters.

A proposed fix for this issue would be easy: Punycode-escape the whole URL before returning it from in `\SFC\Staticfilecache\StaticFileCache::getUri`

**Comment by lochmueller** [comment]
Thanks for your contribution
