### ISSUE TITLE
PHP dependency

### ISSUE THREAD

**Issue by clausharup** [lochmueller/staticfilecache#362]
Extension says PHP dependency (7.4.0 - 8.0.99) - it should work with PHP 8.1.x

**Comment by lochmueller** [comment]
Hey @clausharup 

I saw that this was already fixed: https://github.com/lochmueller/staticfilecache/commit/09ce4efbf8497e610540dce326a2c9435ad67cfa

Will be part of the next release in a few days.

Regards,
Tim
