### ISSUE TITLE
Possible notice?

### ISSUE THREAD

**Issue by georgringer** [lochmueller/staticfilecache#369]
Wanted to link https://forge.typo3.org/issues/98509 with a possible issue in your ext.

feel free to close if not an issue of your ext

**Comment by lochmueller** [comment]
Hey @georgringer ,
I also think it is core related. I added a comment to the issue in forge. Thanks for inform me about this problem.
https://forge.typo3.org/issues/98509
Regards,
Tim

**Comment by lochmueller** [comment]
I will close this issue. Problem is solved in Core: https://forge.typo3.org/projects/typo3cms-core/repository/1749/revisions/a14a3aae52eb5ab4fad405cc8adc5a68b0fd451c/diff/typo3/sysext/fluid/Classes/ViewHelpers/Be/PageInfoViewHelper.php
