### ISSUE TITLE
Warning: Undefined array key `enableGeneratorPhp` @ Classes/Configuration.php

### ISSUE THREAD

**Issue by xerc** [lochmueller/staticfilecache#378]
**will happen after composer-update before save EXT conf. @ BE**
Upgrading lochmueller/sourceopt (dev-master 10886c0 => dev-master e62690d)

https://github.com/lochmueller/staticfilecache/blob/d126680f61fc0b360962c3d2a5f3f1ac9e049e26/Classes/Configuration.php#L198-L201

`$ /opt/php_8.0/bin/php vendor/bin/typo3cms configuration:set `[..]

  [ TYPO3\CMS\Core\Error\Exception ]
  Warning: Undefined array key "enableGeneratorPhp" in /homes/kartell/diversity-kartell.d
  e/source/typo3conf/ext/staticfilecache/Classes/Configuration.php line 198

**Comment by lochmueller** [comment]
Hey @xerc ,
Thanks for reporting. Fixed in the current master.
Regards,
Tim
