### ISSUE TITLE
Version 12.5.0 is not in TER

### ISSUE THREAD

**Issue by chesio** [lochmueller/staticfilecache#380]
## Bug Report

**Current Behavior**
The latest version available in TER is 12.4.5: https://extensions.typo3.org/extension/staticfilecache/

**Expected behavior/output**
The latest version available in TER is 12.5.0: https://github.com/lochmueller/staticfilecache/releases/tag/12.5.0

**Possible Solution**
Release version 12.5.0 in TER.

**Additional context**
Hi Tim,

for me as non-composer user, the ability to get the extension via TER is very useful. To be precise, getting extension from elsewhere is not a problem, but getting notified about new version is a problem. I subscribed to GitHub releases, but they are stucked at version 12.2.0. Now with TER stucked at version 12.4.5 I missed the release of version 12.5.0 (tagged almost half a year ago) until today... :-)

**Comment by lochmueller** [comment]
Hey @chesio 
Thanks for reporting. TER publishing and non-composer installations are not very high on my agenda. The current master is in preparation for the upcoming major release. So I will not publish a release currently, sorry. I suggest to download the extension here from github or (recommended) switch to composer (PHP projects are a lot more fun with composer!!)
I will close this issue. I try to keep an eye on the next release, that this is published also to TER.
Regards,
Tim

**Comment by chesio** [comment]
Hi Tim,

thanks for quick response, I see your point. Unfortunately I cannot switch to Composer yet. Hopefully in the near future :-)
