### ISSUE TITLE
ActionMenuViewHelper extends from final class

### ISSUE THREAD

**Issue by Smove** [lochmueller/staticfilecache#385]
## Bug Report

**Current Behavior**
In TYPO3 12 (i'm using 12.3.0-dev currently), all core ViewHelpers are marked as final. Currently, the class `SFC\Staticfilecache\ViewHelpers\Be\Menus\ActionMenuViewHelper` extends from `TYPO3\CMS\Fluid\ViewHelpers\Be\Menus\ActionMenuViewHelper` which results in an error.

![image](https://user-images.githubusercontent.com/3686891/223062306-c04f2534-4d39-4562-93da-505f1d221806.png)

**Expected behavior/output**
There shouln't be an error

**Environment**
- TYPO3 version(s): 12.3.0-dev
- staticfilecache version: dev-master
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu (docker)

**Comment by lochmueller** [comment]
FIxed in current master.
