### ISSUE TITLE
TYPO3 12

### ISSUE THREAD

**Issue by fritzdacat** [lochmueller/staticfilecache#386]
What are the plans for TYPO3 12?
Is there already a schedule when staticfilecache for TYPO3 12 will be available?

**Comment by lochmueller** [comment]
Hey @fritzdacat ,
the current main branch is prepared for the next major release, but not finished yet. There is/was an agenda: https://typo3.slack.com/archives/C9LRD4LSJ/p1667587886500749 , but currently no support (not financial nor man-power) from anyone. So I need much more time to finish the next release.
I will close this issue.
Regards,
Tim
