### ISSUE TITLE
How to install in non-composer site?

### ISSUE THREAD

**Issue by ursbraem** [lochmueller/staticfilecache#39]
On a site that's not in "composer mode": can I download the code, run composer locally and thus add all the required dependencies to the extension?

Or is there another way to make it work? Can you point me in the right direction?

**Comment by lochmueller** [comment]
There are no local requirements anymore. You can download the extension, put it into typo3conf/ext/staticfilecache and it should work. Do you have any exceptions/problems/errors?

**Comment by ursbraem** [comment]
I didn't even try 😀 I just saw that in the readme it says `You have to install the extension in composer mode, because there are dependencies to guzzle.`

**Comment by ursbraem** [comment]
Seems to work just fine (apart from INC scripts that shouldn't be on the page 😬) Thanks!

**Comment by lochmueller** [comment]
I adapt the description: https://github.com/lochmueller/staticfilecache
Thanks for the hint...
