### ISSUE TITLE
TER release version 13

### ISSUE THREAD

**Issue by rafu1987** [lochmueller/staticfilecache#394]
## Feature Request

Upload version 13 to TER for non-composer installations. 🙂

**Comment by chesio** [comment]
@rafu1987 you might want to download the extension directly from GitHub, see also #380.

**Comment by rafu1987** [comment]
@chesio Thanks for the hint with #380 

Unfortunately, if I have a non-composer installation with an extension and a dependency to staticfilecache, it needs to be in the TER.

**Comment by marcoHolz** [comment]
Hey @lochmueller 
can you say when the current version will be available in TER? 
Greetings

**Comment by lochmueller** [comment]
TER publish works again. Problem was the "declare strict" in the ext_emconf.php. Version 13.1.3 should appear in TER shortly.
