### ISSUE TITLE
Workspace Preview not working

### ISSUE THREAD

**Issue by markusa86** [lochmueller/staticfilecache#395]
## Bug Report

If I send a workspace Preview link to an user, staticfilecache ignores the cookie "ADMCMD_prev".
The user gets the cached value instead of uncached version.
TYPO3 sets this cookie to get the workspace version on the whole website, if a user navigate on the website.

Middleware and htaccess.
In htaccess only the Rule:
`RewriteCond %{HTTP_COOKIE} !ADMCMD_prev [NC]`
is missing after 
`RewriteCond %{HTTP_COOKIE} !staticfilecache [NC]`

**Environment**
- TYPO3 version(s): 11.5.25
- staticfilecache version: 12.5.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

Regards,
Markus

**Comment by lochmueller** [comment]
Hey @markusa86 ,
I checked the core and there is no "ADMCMD_prev" cookie that is used or set by the core. I think it is only a query parameter and Query parameter result in a skipped StaticFileCache.
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @markusa86 
good point. I add this to the htaccess file example/documentation.
Thank you,
Tim
