### ISSUE TITLE
Warning INTScript TYPO3 11

### ISSUE THREAD

**Issue by quadronet** [lochmueller/staticfilecache#398]
I use this ext in a lot of TYPO3 Versions, but now it don´t work with PHP 8.2. 

TYPO3 11.5.27
PHP 8.2

The page has a INTincScript: type: FUNC, userFunc: TYPO3\CMS\Extbase\Core\Bootstrap->run, extensionName: Felogin, pluginName: Login
The page has a INTincScript: type: FUNC, userFunc: TYPO3\CMS\Extbase\Core\Bootstrap->run, extensionName: MindshapeCookieConsent, pluginName: Consentmodal

The same extensions are installed in other TYPO3 Versions, but there your extension works fine.

**Comment by lochmueller** [comment]
Hey @quadronet 

Thank for reporting, but I don't know, who the messages related to a problem with PHP 8.2? In your case, you use two uncacheble plugin on your page. That is the reason, why the STtaicFileCache is not generated. Do you check the integration of Login and Consentmodal?

Why you think it is a problem with your PHP 8.2?

Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue. Feel free to open a new on incl. the PHP 8.2 error, if this is actually a PHP Error.
As already mentioned the log message above are "uncachable plugins" and are no problem in EXT:staticfilecache.
