### ISSUE TITLE
Add .css.gz and .js.gz to .htaccess example

### ISSUE THREAD

**Issue by rafu1987** [lochmueller/staticfilecache#399]
## Bug Report

**Current Behavior**
With the example .htaccess file and TYPO3 12.4.x there will be an error with the JS and CSS assets, because TYPO3 12 changed the .gzip file ending to .gz

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-93182-ChangedFileExtensionForGzipCompressedFiles.html

**Expected behavior/output**
CSS and JS assets should work

**Environment**
- TYPO3 version(s): 12.4.7
- staticfilecache version: 13.1.3
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: OSX 14.0

**Possible Solution**
Add this to example .htaccess file:

```
<FilesMatch "\.js\.gz$">
  ForceType text/javascript
  # AddType "text/javascript" .gzip
</FilesMatch>
<FilesMatch "\.css\.gz$">
  ForceType text/css
  # AddType "text/css" .gzip
</FilesMatch>
```

**Comment by lochmueller** [comment]
Hey @rafu1987  Thanks for reporting. Fixed in current master. Regards, Tim
