### ISSUE TITLE
Static file is not deleted when there's an edit in BE

### ISSUE THREAD

**Issue by webian** [lochmueller/staticfilecache#4]
Hi @lochmueller,
I upgraded to TYPO3 8 LTS and switched from nc_staticfilecache to staticfilecache.
It all works good except the fact that when an editor edits something in the BE the static file is still serving the old page in the FE.
The editor has to clear frontend caches to see the edit.
I'm still investigating this but maybe you can point me in the right direction faster.
Thanks anyway for this beautiful extension!

**Comment by lochmueller** [comment]
Hmmm.... I think the core should run the cleanup, because the page is tagged in the right way and the core delete all caches based on Tags, if the editor change something...
https://github.com/lochmueller/staticfilecache/blob/master/Classes/StaticFileCache.php#L107

Regards,
Tim

**Comment by webian** [comment]
I just debugged editing the title of a page and that method `\SFC\Staticfilecache\StaticFileCache::insertPageInCache` is not called.
Still debugging...

**Comment by lochmueller** [comment]
The "insertPageInCache" is called when the cache is created. The cache record should created with a "pageId_XXXX" tag. Thie is the cache, that is dropped from the core, if the editor change something. So... the SFC extension is not involved in the "delete cache process". It is just the caching framework an the core.

**Comment by webian** [comment]
> SFC extension is not involved in the "delete cache process"

Debugging I found that SFC deletes the folder 'typo3temp/tx_staticfilecache' with the method `\SFC\Staticfilecache\Cache\StaticFileBackend::flush`. This method is called only when the editors clears all frontend caches.

I don't see any other SFC method that could delete the static file relative to a just edited page. I would expect a method that deletes the file relative to that page.

Maybe I didn't understand all the static file cache process.

**Comment by webian** [comment]
Sorry, the method that shuld delete the static file relative to a just edited page is `\SFC\Staticfilecache\Cache\StaticFileBackend::flushByTag` but it's not called when the page is edited.

**Comment by webian** [comment]
When a page is edited, TYPO3 calls `$this->caches['staticfilecache']->flushByTags($tags);` and `$tags` is an array populated with the tags of the pages whose cache has to be cleared.
But then it doesn't execute that method `\SFC\Staticfilecache\Cache\StaticFileBackend::flushByTag`.
Instead it executes `\TYPO3\CMS\Core\Cache\Backend\Typo3DatabaseBackend::flushByTags`.
This is what happens in my installation debugging.

**Comment by webian** [comment]
Is it possible that the problem is that SFC is missing the method `flushByTags()` (watch the final 's') that then calls `flushByTag()` ?
