### ISSUE TITLE
Core: Exception handler (CLI): Uncaught TYPO3 Exception Error

### ISSUE THREAD

**Issue by LMFC-Krisi** [lochmueller/staticfilecache#403]
## Bug Report

Hello
Since Update staticfilecache 13.1.3 i have many errors in my typo3 protocol:
Example here:
Core: Exception handler (CLI): Uncaught TYPO3 Exception: syntax error, unexpected 'static' (T_STATIC) | ParseError thrown in file /homepages/33/d13475450/htdocs/typo3/typo3conf/ext/staticfilecache/Classes/Command/AbstractCommand.php in line 20 

I don't know what is wrong here. Is it a bug in your extension or something wrong in my Typo3 configuration?
I hope you can help.

**Environment**
- TYPO3 version(s): 11.5.33
- staticfilecache version: [e.g. 13.1.3]
- Is your TYPO3 installation set up with Composer (Composer Mode): [ no] Symlink Version
- PHP 8.1

If you have any questions, don't hesitate to contact me.
Best Regards Michael

**Comment by lochmueller** [comment]
Hey @LMFC-Krisi 
Please execute the Command with PHP > 8.0. The static return type is allowed since PHP 8.0 https://php.watch/versions/8.0/static-return-type, and you call the command with a lower PHP Version.
Regards,
Tim
