### ISSUE TITLE
Commands should follow Interface constraints from `symfony/console:v7`

### ISSUE THREAD

**Issue by m41r** [lochmueller/staticfilecache#404]
## Bug Report

**Current Behavior**
After a composer update, the symfony package "console" was updated from v6 to v7 and the cli command `typo3 extension:setup`  is now throwing an error:

> typo3 extension:setup
PHP Fatal error:  Declaration of SFC\Staticfilecache\Command\BoostQueueCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/lochmueller/staticfilecache/Classes/Command/BoostQueueCommand.php on line 65

**Expected behavior/output**
No exception

**Environment**
- TYPO3 version(s): 12.4.10
- staticfilecache version: 13.1.3
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by lochmueller** [comment]
Thanks for the direct PR. Merged.
