### ISSUE TITLE
compatibility issue within the 'execute' method of a Command in Symfony Console version 7

### ISSUE THREAD

**Issue by GigaCode93** [lochmueller/staticfilecache#406]
## Bug Report

**Current Behavior**
In Symfony 7, the execute method of Symfony Command now requires a return value of type `int` as part of its method signature. However, this requirement has not been implemented in your extension's Commands. Additionally, your code includes the strict types declaration `declare(strict_types=1);`. As a result, it leads to a fatal error due to this incompatibility.

**Expected behavior/output**
Preventing fatal errors and ensuring compatibility.

**Environment**
- TYPO3 version(s): 12.4.10
- staticfilecache version: 13.1.3
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 22

**Possible Solution**
Modifying the method signature to make it compatible with the execute method of the Symfony command, or alternatively, removing `declare(strict_types=1);`.

**Comment by lochmueller** [comment]
Hey @GigaCode93 ,
already fixed yesterday in current main branch: https://github.com/lochmueller/staticfilecache/commit/14a985251742268a3be34975fb8e4dc1eaf4f64b
Regards,
Tim
