### ISSUE TITLE
staticfilecache breaks on symfony/console v7.0.3

### ISSUE THREAD

**Issue by misterboe** [lochmueller/staticfilecache#407]
Fatal error: Declaration of SFC\Staticfilecache\Command\BoostQueueCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /vendor/lochmueller/staticfilecache/Classes/Command/BoostQueueCommand.php on line 65

TYPO3 12.4.10
staticfilecache 14.0.0

FIX:
Downgrading symfony/console (v7.0.3 => v6.4.3)

**Comment by lochmueller** [comment]
Already fixed in current main Branch: https://github.com/lochmueller/staticfilecache/commit/14a985251742268a3be34975fb8e4dc1eaf4f64b
