### ISSUE TITLE
TYPO3 v13: TypoScriptFrontendController::isStaticCacheble() is now internal

### ISSUE THREAD

**Issue by peterkraume** [lochmueller/staticfilecache#410]
## Bug Report

> Too few arguments to function TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::isStaticCacheble(), 0 passed in /var/www/html/vendor/lochmueller/staticfilecache/Classes/Cache/Listener/StaticCacheableListener.php on line 23 and exactly 1 expected

**Environment**
- TYPO3 version(s): 13.0
- staticfilecache version: master
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: DDEV

**Possible Solution**
TypoScriptFrontendController::isStaticCacheble() is now internal:
https://docs.typo3.org/c/typo3/cms-core/main/en-us//Changelog/13.0/Breaking-102621-MostTSFEMembersMarkedInternalOrRead-only.html

I tried to come up with a solution and rewrite the entire listener but unfortunately that was too much for me.

**Comment by lochmueller** [comment]
hey @peterkraume ,
I think the internal is not a/the problem at the moment, becuase the method is callable in v13 (currently). BUT the method need the request object in v13 and so we have to split up the isStaticCacheble for Version 12 & 13.
What do you think about https://github.com/lochmueller/staticfilecache/commit/37fc64a7ed03371e9632466b2b4843a8b29753fb to get it working with v13?
Regards,
Tim
PS: Thanks for the sponsoring ;)

**Comment by lochmueller** [comment]
I will close this issue. There are currently working solutions in the extension. For TYPO3 v14 I will think about another solution/integration.
