### ISSUE TITLE
Docu htaccess file

### ISSUE THREAD

**Issue by ste101** [lochmueller/staticfilecache#413]
The [docu](https://docs.typo3.org/p/lochmueller/staticfilecache/main/en-us/Configuration/Htaccess.html) says:

```
If you use the oldschool .htaccess rewrite rules that come with the TYPO3 dummy,
then the relevant StaticFileCache configuration should be inserted in the
.htaccess file just before these lines:

.. code-block:: apache

   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteCond %{REQUEST_FILENAME} !-d
   RewriteCond %{REQUEST_FILENAME} !-l
   RewriteRule .* index.php [L]
```

The resent htaccess changed a bit.

Is this the correct place now:
```
	# If the file/symlink/directory does not exist => Redirect to index.php.
	# For httpd.conf, you need to prefix each '%{REQUEST_FILENAME}' with '%{DOCUMENT_ROOT}'.
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-l
	RewriteRule ^.*$ %{ENV:CWD}index.php [QSA,L]
```

Why is there the text `If you use the oldschool .htaccess rewrite rules that come with the TYPO3 dummy,`?
Is there a better way?

**Comment by lochmueller** [comment]
Hey @ste101 
good point. We could change "oldschool" with "default". Furthermore we could switch to the new default rewrite of the core. Would you send a PR?
Regards,
Tim
