### ISSUE TITLE
Use a custom User-Agent in Boostmode-Crawler

### ISSUE THREAD

**Issue by lavitto-private** [lochmueller/staticfilecache#415]
## Feature Request

I work with StaticFileCache (Boostmode) in combination with Cloudflare.

There is the problem that the boostmode-command does not regenerate the pages if they are still in the Cloudflare cache. This could be solved with a custom user agent.

In my installation, I have overwritten the user agent (in ClientService.php) with "TYPO3 StaticFileCache". In Cloudflare, I have defined a cache rule that bypasses the cache for this user agent. I have also created a WAF rule that ensures that only the web server is allowed to use this user agent.

If a custom hardcoded user agent can lead to problems, it could be made configurable.

**Comment by lochmueller** [comment]
Hey @lavitto-private 
good point. Would you create a PR? I think we can use a "overrideClientUserAgent" here ( https://github.com/lochmueller/staticfilecache/blob/master/ext_conf_template.txt ) and - if set - use it as UserAgent?!?
Regards,
Tim

**Comment by lavitto-private** [comment]
Hi @lochmueller
Gladly, just done.
Philipp
