### ISSUE TITLE
http2 // .htaccess: Unrecognized header format %C

### ISSUE THREAD

**Issue by mweber1973** [lochmueller/staticfilecache#416]
## Bug Report

An error occurs  (".htaccess: Unrecognized header format %C") when using http/2 and special chars (German "Umlauts") occur in the header defined in the htaccess for each path. 

Here is an example htacces, which was generates from staticfilecache

`ForceType text/html
<IfModule mod_headers.c>
	Header set Content-Type "text/html; charset=utf-8"
	Header set Content-Language "de-DE"
	Header set X-SFC-Tags "pageId_81"
	Header set Link "</typo3temp/scriptmerger/compressed/head-b75f03d35c905c5e7f3438762a028aaa.merged.gz.css>; rel=preload; as=style, </typo3temp/scriptmerger/compressed/merged-af70fc85406b2f7c6d25c15bda660181-bd7646673baae1566a3f74314c38cbf2-008ee18b117d3e771ee72e0a00361a2f.gz.js>; rel=preload; as=script, </typo3temp/scriptmerger/compressed/head-a88c27c9be3c0fcc2823970964ba6ffd.merged.gz.js>; rel=preload; as=script, </typo3temp/scriptmerger/compressed/merged-5e6a73611e6158bb979dbd6ae2c8188c-983f4c9e03bc5be4e7775e6055b57dfc-7bf3d5904b79b8f7fb05127ff563e9c6.gz.js>; rel=preload; as=script, </typo3temp/scriptmerger/compressed/merged-dd7be22ad69ffe47acfc503a8204eb65-e76fd976eacbd2e3c02bef1383237c55-6b9d17db2e13eab9a6835438e2372b98.gz.js>; rel=preload; as=script, </typo3temp/scriptmerger/compressed/ba19e614c16923a947df5b199324c770-ba19e614c16923a947df5b199324c770.gz.js>; rel=preload; as=script, </fileadmin/_processed_/1/e/csm_lehrg%C3%A4nge_9539b64e6b.jpg>; rel=preload; as=image, </fileadmin/_processed_/1/e/csm_lehrg%C3%A4nge_d172503e7b.jpg>; rel=preload; as=image, </fileadmin/_processed_/1/e/csm_lehrg%C3%A4nge_66692d8670.jpg>; rel=preload; as=image, </fileadmin/_processed_/1/e/csm_lehrg%C3%A4nge_0dfcea555f.jpg>; rel=preload; as=image"
</IfModule>`

**Environment**
- TYPO3 version(s): 12.4
- staticfilecache version: 14.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Possible Solution**
Disbale http/2 in staticfilecache

**Comment by lochmueller** [comment]
Hmm... I think TYPO3 backend cleanup german umlauts, so the file names should be clean (do you try this)?! Do you use files, that aren't uploaded via TYPO3 backend or from old TYPO3 versions?
Regards,
Tim

**Comment by mweber1973** [comment]
All files were uploaded via Typo3, not via FTP. 

Perhaps we can get in contact so you can have look in the backend to reproduce the error?

**Comment by lochmueller** [comment]
> All files were uploaded via Typo3, not via FTP.
> 
> Perhaps we can get in contact so you can have look in the backend to reproduce the error?

Feel free to write me, via TYPO3 Slack...

**Comment by mweber1973** [comment]
Hallo Tim,

 

keine Ahnung ob das hier ankommt…..ich bin zwar auch in der Entwicklung tätig weiß aber gerade mit „Typo3 Slack“ nichts anzufangen

 

Wenn diese Mail ankommt schicke ich dir gerne mal di Zugangsdaten zu dem Projekt, das ist nichts kommerzielles….und wenn Du das gegen Rechnung machen möchtest wäre es auch kein Problem 😊

 

Markus

 

Von: Tim ***@***.***> 
Gesendet: Donnerstag, 20. Juni 2024 13:47
An: lochmueller/staticfilecache ***@***.***>
Cc: Markus Weber ***@***.***>; Author ***@***.***>
Betreff: Re: [lochmueller/staticfilecache] http2 // .htaccess: Unrecognized header format %C (Issue #416)

 

All files were uploaded via Typo3, not via FTP.

Perhaps we can get in contact so you can have look in the backend to reproduce the error?

Feel free to write me, via TYPO3 Slack...
