### ISSUE TITLE
Typo in github repo description

### ISSUE THREAD

**Issue by infabo** [lochmueller/staticfilecache#422]
## Bug Report

**Current Behavior**

🚀 Fastes TYPO3 Extension ever 🚀 

**Expected behavior/output**

🚀 Fastest TYPO3 Extension ever 🚀 

**Environment**
- GitHub

**Possible Solution**

Add the letter "t" to the word "Fastes"

**Additional context**

![image](https://github.com/user-attachments/assets/c3234e22-25d8-4677-a31c-7ea9a5bee3cc)

**Comment by lochmueller** [comment]
Hey @infabo 
thanks for the note. Changed!
Regards,
Tim
