### ISSUE TITLE
Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getContext()

### ISSUE THREAD

**Issue by GigaCode93** [lochmueller/staticfilecache#424]
## Bug Report

**Current Behavior**
Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getContext()
in /var/www/html/vendor/lochmueller/staticfilecache/Classes/Cache/Rule/NoWorkspacePreview.php line 21

I did not found any Documantation about it but getContext() is removed from TypoScriptFrontendController in typo3 13.4.

**Environment**
- TYPO3 version(s): [e.g. 13.4]
- staticfilecache version: [e.g. 14.0.1]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Comment by lochmueller** [comment]
Hey @GigaCode93 
I close this issue. Please use a 15.x version of EXT:staticfilecache.
This line is already switched to DI : https://github.com/lochmueller/staticfilecache/blob/main/Classes/Cache/Listener/NoWorkspacePreviewListener.php
Regards,
Tim
