### ISSUE TITLE
Is it possible to disable filecaching for a list of filenames?

### ISSUE THREAD

**Issue by clausharup** [lochmueller/staticfilecache#43]
I have made a dynamic manifest.json file as a typeNum and unfortunately staticfilcache adds comments to my file, which makes .json invalid..... :-(

I would like to keep the functionality to add comments to the genetaed .html files, but disable caching for a list of filenames.... is that possible?

**Comment by lochmueller** [comment]
Hey @clausharup ,
you can disable static file ache by TypoScript. This should also be possible for your special page type.
I close this question... For simple questions is the Slack the best way to communicate...
Regards,
Tim
