### ISSUE TITLE
Expiry timeframe

### ISSUE THREAD

**Issue by ursbraem** [lochmueller/staticfilecache#44]
The footer on my page says:

Does that mean the statically cached file will only be kept for 10 minutes, or do I get that wrong?
If so, where can I modify that expiry?

**Comment by lochmueller** [comment]
Hey @ursbraem ,
please use TYPO3 Slack for general questions in the future and the issue tracker only for issues.

The expiry of the page is based on the TSFE object (the page, TS and also the CE rendering is evaluated). If it is 10 minutes and you want more, check the page settings, the content elements, the TS. StaticFileCache has no expiry settings and use the expiry of the TSFE.
Regards,
Tim

**Comment by ursbraem** [comment]
Sorry! Which channel is best? 

And big thanks!  I had a typo in TS, config.cache_period was set to a bad value (`86'000` with a high comma) – so it probably fell back to the shortest interval.

**Comment by lochmueller** [comment]
General channel... or I created a #ext-staticfilecache a few seconds ago.
