### ISSUE TITLE
Boost mode documentation

### ISSUE THREAD

**Issue by glucka** [lochmueller/staticfilecache#45]
hi @lochmueller, thank you for the great boost mode method!
Unfortunately i cannot setup the boost mode. This command should recreate the static files after expire, right?
```
/typo3/sysext/core/bin/typo3 staticfilecache:cache:runcacheboostqueue
```
But it does not work and i can not find anything about it in the documentation.
Just an info: in 'tx_staticfilecache_queue' table every page_uid is 0.

**Comment by lochmueller** [comment]
This is right: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/QueueService.php#L137
Only the identifier should be the right URL of the page, that is updated with the "runcacheboostqueue" task.

Regards,
Tim

**Comment by glucka** [comment]
Thanks for the explanation. I keep testing it because it does not always work.

**Comment by lochmueller** [comment]
Ok. I will close this issue. Please create a new one with more information...
Note: The URIs are called with a special Guzzle configuration. If the page is not callable (.htacess configuration, missing routing fpor your webserver), the boost mode will not work.

**Comment by glucka** [comment]
hi Tim, sorry dass ich auf deutsch schreibe aber ich kann viel besser auf deutsch wie auf english.
Also ich habe es tiefer angeschaut. Guzzle lauft normal ab, Serverantwort 200, trozdem wird aber kein neue index.html generiert. Ich denke darum, weil Typo3 Frontend Cache existiert für die url. Die Frage ist wieso, wenn es nie direkt aufgerufen wird dank der .htaccess Rule. Ich suche weiter :) Gruss Attila

**Comment by glucka** [comment]
Langsam kapiere ich es :) Das command ```staticfilecache:cache:runcacheboostqueue``` generiert nur bei eine Änderung die filecache neu. Also ich muss vorher ```staticfilecache:cache:flushcache``` aufrufen wenn ich eine dynamische seite neu generieren will stimmt?

**Comment by glucka** [comment]
Eine Sache verstehe ich noch nicht. Wenn das typo3 frontend cache ablauft von eine seite dann müsste ```runcacheboostqueue``` es trozdem neu generieren oder? Das ist der fehler denke ich.

**Comment by glucka** [comment]
Hi Tim @lochmueller  Mein problem lag daran dass ich immer nur das befehl ```runcacheboostqueue``` ausgeführ habe. Es muss davor aber ```flushcache``` unbedingt ausgeführ werden sonnst das quene wird nicht gefüllt mit abgelaufene seiten. Sollte es nicht eine funktion werden? Gruss Attila

**Comment by lochmueller** [comment]
Das ist falsch. runcacheboostqueue sollte Seiten neu aufnehmen, wenn diese noch einen 200er liefern und automatisch Seiten entfernen, welche keinen 200 Status Code liedern. Wenn vorher der Cache "geflusht" wird, dann muss TYPO3 diesen intern ja auch neu aufbauen, was aber nicht nötig sein sollte...

Grüße,
Tim

**Comment by glucka** [comment]
Danke Tim für die erklärung. Es funktioniert definitiv nicht so bei mir. Ich debugge mal wenn ich etwas Zeit finde und berichte darüber. Gruss Attila

**Comment by glucka** [comment]
Hi Tim, hier https://github.com/lochmueller/staticfilecache/blob/0ed7b7f7644635bbe1ef61802d6c41629dcd65e7/Classes/Service/QueueService.php#L129 werden nur die db einträge gelöscht welche nicht 200 antworten aber welche richtig antworten werden nicht neu aufgenommen. Aufnemen kann ich nur wenn ich manuell ```flushcache``` aufrufe.

**Comment by lochmueller** [comment]
Jein... das aufnehmen selbst macht ja die Seite, welche gerade aufgerufen wird (mit dem separaten Request). An dieser stelle geht es nur darum, die Adressen aufzurufen. Diese aktualiseren selbständig (mit den normalen Hooks) den Cache... nur wenn die Seite nicht mehr gerendert werden kann (Code != 200), dann muss reagiert werden und der Cache-Eintrag komplett entfernt werden.

**Comment by glucka** [comment]
Danke für die ausführliche Erklärung Tim! Jetzt ist alles klar. ;)

**Comment by glucka** [comment]
"das aufnehmen selbst macht ja die Seite, welche gerade aufgerufen wird (mit dem separaten Request)"
Das Request erreicht aber der Typo3 nie, wenn ein File Cach eintrag existiert oder?
Das könnte die erklärung sein warum muss ich immer das cache leeren vor dem ```runcacheboostqueue```

**Comment by lochmueller** [comment]
Doch. Deshalb wird ja das Cookie gesetzt und in der htaccess-Datei geprüft, sodass der Request NICHT die statische Seite ausgeliefert bekommt.

**Comment by glucka** [comment]
Ja aber wenn die Seite garnicht in der ```tx_staticfilecache_queue``` tabelle existiert?
Z.b wenn ```cleanupcacheboostqueue``` es gelöscht hat?

**Comment by lochmueller** [comment]
"cleanupcacheboostqueue" löscht bereits abgearbeitet Seiten aus der Queue (keine, welche noch nicht vom Worker erfasst wurden). Wenn für die Seite erneut ein "clear Cache" durchgeführt wird, dann gibt es auch wieder einen neuen Eintrag in der Queue. "runcacheboostqueue" ist der Worker, welcher die Queue abarbeitet.

**Comment by glucka** [comment]
Danke Tim! Verstehe ich! Also sobald ich im Backend etwas geändert habe oder Seiten Cache gelert habe landet der Seite in der queue. Mein problem betrifft nur die "Dynamisch-Statische" Seiten welche in backend nicht bearbeitet werden trozdem eine andere Frontend erzeugen. Da bleibt mir nur die möglich keit das cache zu leeren.

**Comment by lochmueller** [comment]
nein... dann fehlt bei dir z.B. ein clearCacheCmd: https://docs.typo3.org/typo3cms/TSconfigReference/PageTsconfig/TCEmain/Index.html#clearcachecmd

Deine Cache Strategie von deiner TYPO3 Instanz sollte so ausgelegt sein, dass wenn du z.B. eine News Meldung bearbeitest automatisch Seiten mit der Newsmeldung "geleert" werden (clearCacheCmd). Wenn das alles passend konfiguriert ist, dann werden auch die passenden Seiten in die Queue aufgenommen. Ohne "clearCacheCmd"-Strategie gebe ich dir recht, dann geht nur ein komplett "flushcache", was aber nicht zu empfehlen ist.

**Comment by glucka** [comment]
Ja das funktioniert zB. bei News Plugin wunderbar aber bei Random Inhalt nicht. :) Danke trozdem für deine Einsatz. Gruss Attila

**Comment by lochmueller** [comment]
Was ist den "Random Inhalt". Sobald du einen Inhalt auf eine Seite änderst, welcher auf anderen Seiten dargestellt wird, sollte es ein clearCacheCmd geben. Ob das eine News oder ein tt_content oder etwas anderes ist, sollte eigentlich egal sein. Nungut.... hier im Issue bereich am besten keine Diskussion. Fragen am besten via Slack #ext-staticfilecache. Hier bitte nur Bugs besprechen.

Danke & Grüße,
Tim
