### ISSUE TITLE
staticfilecache:cache:runcacheboostqueue work for max. 30sec

### ISSUE THREAD

**Issue by glucka** [lochmueller/staticfilecache#47]
The guzzle client set the ```staticfilecache``` cookie with 30 sec expire time.
After 30 sec is the cookie expired and the file cache response with 200 code.
Result: The command do not recreate the file cache after 30 sec run-time.

**Comment by lochmueller** [comment]
Patch merged... Thanks 👍

**Comment by glucka** [comment]
Hi Tim, es kann momentan max. 999 Seitenabrufe sein pro command.
https://github.com/lochmueller/staticfilecache/blob/e4bac16780da0af7268edebc37e42ad062b7d47d/Classes/Service/QueueService.php#L35
Ich habe durchnittlich 5 sec pro Seitenabruf gemessen, es ist aber stark systemabhängig.
Mit 999 Seitenabrufe würde es mind. 83 minuten dauern.
Also könnte man evtl. die cookie zeit frisch auf 2-3 Stunden erhöhen damit es sicher nie mehr vorkommt. :) Oder gleich auf ein Tag, es hat ja keine negative auswirkung. Gruss Attila

**Comment by lochmueller** [comment]
Können wir eigentlich beliebig hoch setzen. Genre noch ein pull-request wenn es noch zu niedrig ist...
