### ISSUE TITLE
TYPO3 is broken after click "Force the static cache generation (!!!)"

### ISSUE THREAD

**Issue by drblitzweblab** [lochmueller/staticfilecache#49]
Short description
-----------------
When I try to open page and I choose "Force the static cache generation (!!!)" I have this error 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: array_diff_assoc(): Argument #1 is not an array in /home/users/website/public_html/doamin.com/vendor/typo3/cms/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php line 3489 | TYPO3\CMS\Core\Error\Exception thrown in file /home/users/website/public_html/doamin.coml/vendor/typo3/cms/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 107. Requested URL: https://domain.com/test
...

Steps to reproduce the problem
------------------------------
Edit page and choose "Force the static cache generation (!!!)" open the page and I see "Oops, an error occurred!"

More Details
------------
TYPO3 Version : 8.7.9 - 8.7.12
PHP Versin : 7.1.8

**Comment by lochmueller** [comment]
Thanks for the bug report. Fixed in the current master and will be part of the next version. Bugfix:
https://github.com/lochmueller/staticfilecache/commit/34b0a014bbad45d2cd0275a18fc1361f0a4416f7

Regards, Tim
