### ISSUE TITLE
Encoding already punycoded domains will throw an exception

### ISSUE THREAD

**Issue by foobar13373** [lochmueller/staticfilecache#51]
I falsely submitted this bug report to the TYPO3 Core tracker, but moved it to the old static file cache bug tracker on forge.typo3.org already, but actually it belongs here.... (found this out later, after I found out that staticfilecache is the casue for this). There's the forge ticket:

https://forge.typo3.org/issues/84527

**Comment by foobar13373** [comment]
Additional info: this happens after clearing the cache on the first visit of a punycoded domain.

**Comment by lochmueller** [comment]
Thanks for the report. The exception is catched in the next release:
https://github.com/lochmueller/staticfilecache/commit/cea0524c456071b4c7b750e52c781b24d94f5ba7

**Comment by lochmueller** [comment]
5.3.2 is released 👍
