### ISSUE TITLE
[FEATURE] Create options for cache warmup

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/staticfilecache#53]
e.g. Implement backend 'context menu' item to 'cache this branch now'. or EXT:crawler?

**Comment by lochmueller** [comment]
Idea:
- Add a crawler conifguration with realurl enable to get the right urls
- Add this URLs to QueueService->addIdentifier
- Add some documentation that the crawler extension could use the fetch the URLs and the Boost Mode Command can rebuild this URLs

**Comment by hendrikreimers** [comment]
Great Idea,... i'd currently done this by an own simple scheduler. Maybe i can help you! I'm contacting you by mail.

**Comment by lochmueller** [comment]
I close this issue, because it is to tricky in TYPO3 itself... I use this tool in the deployment to warmup the FE caches: https://github.com/lochmueller/seocli

I close this issue....

**Comment by Patta** [comment]
> I close this issue, because it is to tricky in TYPO3 itself... I use this tool in the deployment to warmup the FE caches: https://github.com/lochmueller/seocli
> 
> I close this issue....

@lochmueller maybe with [crawler v9](https://github.com/AOEpeople/crawler/blob/master/CHANGELOG.md) this feature would be possible?

**Comment by lochmueller** [comment]
Hey @Patta 
I added this rule yesterday: https://github.com/lochmueller/staticfilecache/commit/d925be8e47da0355c9ffa3ca85ac9a7dd47d8705
The problem is, that the crawler is a middleware no, that call the TSFE rendering, but replace the output with JSON meta information. SFC is in front of the crawler middlewares, so the JSON was stored in the cache. Currently I have no good solution for that. A better approch for crawler would be, to store the meta information in Response headern instead of the body :-/ 
Regards,
Tim
