### ISSUE TITLE
htacess - cache control

### ISSUE THREAD

**Issue by infabo** [lochmueller/staticfilecache#56]
Short description
-----------------
sendCacheControlHeader in .htaccess is different from `"<!-- expires on: dd-mm-yy hh:mm -->"` comment in cached html files

Steps to reproduce the problem
------------------------------
2. set typo3 cache-period to e.g. 14 days
1. Place an element on a page, which has a start-stop time in near future, e.g. in 2 hours.

What is the expected behaviour?
-------------------------------
.htaccess `"ExpiresByType text/html M..."` to match `<!-- expires on: ... -->`

What is observed behaviour?
---------------------------
`ExpiresByType text/html M...` is always set to the deault-cacheperiod of typo3.

**Comment by glucka** [comment]
Maybe because .htacces use always UTC Timezone?

**Comment by lochmueller** [comment]
Hey @infabo 
I streamline the lifetime variable with the last commit: https://github.com/lochmueller/staticfilecache/commit/f78196ed09c71bf2ddcf7918e5aa8ef005b5a77f
But i cannot confirm your behavior. Do you use the "processContent" Slot of SFC and modify the "timeOutSeconds" variable? It is a timezone problem (like @glucka described)?
Regards,
Tim

**Comment by infabo** [comment]
need to check latest commit. 

2hours was just a bad example from me. in fact it happened with elements scheduled for 3 days in future. but expiration-time comment in html file was correct, but a very high expirebytype value was written to .htaccess (matching default page.cache_period value).

**Comment by lochmueller** [comment]
Hey @infabo
I double checked the current master on my test-system. I cannot rebuild this problem. 
```
<!-- cached statically on: 16-04-18 21:24 -->
<!-- expires on: 17-04-18 00:22 -->
```

```
ExpiresByType text/html M10681
```

With a page cache of 14 days and a content element, that should be online at "17-04-18 00:22". htaccess and page comment are in sync

Regards,
Tim

**Comment by infabo** [comment]
Hi Tim,

I'm going to setup some test-cases on the TYPO3-system where I have observed the described issue.
As soon I can reproduce it i will open another issue.
