### ISSUE TITLE
Cache for one page is not cleared if the cache entry has expired (relevant when not using sendCacheControlHeaderRedirectAfterCacheTimeout)

### ISSUE THREAD

**Issue by AndreasA** [lochmueller/staticfilecache#6]
TYPO3 clears a page cache by using the tags pageId_{UID}
Now staticfilecache does this correctly IF the entry hasn't expired.

However, if the entry has expired then retrieving the cache identifiers by tag name doesn't work as the method looks like this:

```
   /**
     * Finds and returns all cache entries which are tagged by the specified tag.
     *
     * @param string $tag The tag to search for
     * @return array An array with identifiers of all matching entries. An empty array if no entries matched
     */
    public function findIdentifiersByTag($tag)
    {
        $this->throwExceptionIfFrontendDoesNotExist();
        $cacheEntryIdentifiers = [];
        $cacheEntryIdentifierRows = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows(
            $this->identifierField,
            $this->tableList,
            $this->tagsTable . '.tag = ' . $GLOBALS['TYPO3_DB']->fullQuoteStr($tag, $this->tagsTable) . ' AND ' . $this->tableJoin . ' AND ' . $this->notExpiredStatement,
            $this->identifierField
        );
        foreach ($cacheEntryIdentifierRows as $cacheEntryIdentifierRow) {
            $cacheEntryIdentifiers[$cacheEntryIdentifierRow['identifier']] = $cacheEntryIdentifierRow['identifier'];
        }
        return $cacheEntryIdentifiers;
    }
```

does not find entries that are expired.
However, as the files have to be removed even in that case - especially if they don't expire - the notExpiredStatement has to be ignored in this case.
WHICH means ONLY when we are exeucting this method during flushing of the cache.

This is especially relevant if one doesn't use sendCacheControlHeaderRedirectAfterCacheTimeout (which is the default setting) because then the file will still be used instead of the new content.

**Comment by lochmueller** [comment]
Hey @AndreasA 

thanks for the hint. What is you suggest solution?
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/StaticFileBackend.php#L250
Set the entries "expired" in front of the function call? Or override the findIdentifiersByTag completly? Or set and reset just "$this->notExpiredStatement" in front of the call?

Regards,
Tim

**Comment by AndreasA** [comment]
The findIdentifiersByTag method might be used in other places as well, so I wouldn't override this method.
It is a public method even.

If I just want to find the active Identifiers it produces the correct output.

Btw. the same issue is probably with https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/StaticFileBackend.php#L265

collectGarbate.

I think creating a second method findIdentifiersByTagIncludingExpired or something like that would be the best solution. 
The same regarding getIdentifiers.

That method could then unset $this->notExpiredStatement and call the parent method and reset that statement after the call.

**Comment by lochmueller** [comment]
Hey Andreas,

I commit https://github.com/lochmueller/staticfilecache/commit/2476ff5a89a8e1d25fcbaeb1e8367c50c35cb4f6 and move the problem to a single line:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/StaticFileBackend.php#L306

I checked the code of TPO3 CMS 8. There is no "notExpiredStatement" anymore. They directly check "expires" on "$GLOBALS['EXEC_TIME']" (with 'gte'). So one (but a little bit hacky) solution is to set "$GLOBALS['EXEC_TIME'] = 0" before the call and after this back to the original value? Any better ideas?

Like this:
https://github.com/lochmueller/staticfilecache/commit/794d1f24a2602a4fd8ada3cb2a66529686e4da32

Do you use "7.6.x". Then I will also add the "$this->notExpiredStatement" part incl. a version check?!?

Regards,
Tim

**Comment by AndreasA** [comment]
collectGarbate would also need to take care of it:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/StaticFileBackend.php#L283

To support 7.6 and 8.x and maybe other versions, maybe the best idea would be to create a function:
findIdentifiersByTagIncludingExpired

and manually implement that method.
