### ISSUE TITLE
config.no_cache is true

### ISSUE THREAD

**Issue by glucka** [lochmueller/staticfilecache#60]
![screenshot from 2018-05-03 07-51-15](https://user-images.githubusercontent.com/6602365/39561613-03556f12-4ea7-11e8-9756-1fecda94940c.png)

![screenshot from 2018-05-03 07-51-43](https://user-images.githubusercontent.com/6602365/39561614-0378c958-4ea7-11e8-924d-04e60deaed9c.png)

Boost mode is on
Latest realurl (2.3.2)
linkVars = L(0-1)
'FE' => [
        'disableNoCacheParameter' => '1',
        'loginSecurityLevel' => 'rsa',
    ],

The question is, how can i debug this?

**Comment by lochmueller** [comment]
Hmm.... this is hard to debug, because many places can change the "->no_cache" property of the TSFE. I suggest to enable xdebug, watch the no_cache property and check which code change the value...
Possible reasons:
- invalid cHash calculation
- TS no_cache=1

**Comment by glucka** [comment]
Thanks, the problem is that sometimes works 1-3 days. Than after 1-3 days does not. I continue to investigate.
