### ISSUE TITLE
[BUG] Filecache wird nicht generiert nach Typo3 logout 

### ISSUE THREAD

**Issue by glucka** [lochmueller/staticfilecache#61]
Folgende scenario: 
- ich bin im typo3 backend angemeldet
- leere ich das frontendcache
- ich logge aus
- lade die seite neu

Ergebniss:
- typo3 frontend cache wird generiert aber file cache nicht!
- bis zum nächste cache ablauf wird der filecache garnicht verwendet

Wenn ich in browser aber im privat modus das erste mal die seite aufrufe dann ist alles ok, beide cache wird generiert. Ich denke das ist darum weil nach abmeldung aktuell wird die cookie be_typo_user nicht gelsöcht. Kann sein dass es ein typo3 fehler ist weil das typo3 fronteend cache wird aufgebaut, nur ein bestimmte hook lauft nicht ab welche staticfilecache benutzt?

**Comment by lochmueller** [comment]
Fixed in https://github.com/lochmueller/staticfilecache/pull/62
