### ISSUE TITLE
[BUG] cache file only generated once if page available under multiple URLs

### ISSUE THREAD

**Issue by AndreasA** [lochmueller/staticfilecache#7]
Hi,

if one has a page reachable under multiple URLs - for SEO the corresponding canonical tag exists - then only the first call to that page will be cached.
The reason: TYPO3 has the page in the cache and doesn't call insertPageIncache again.
Maybe one should check at the end of content processing, if the page was cachable:
meaning not INT script and not set as no_cache and if so, create the entry if it doesn't exist.

**Comment by AndreasA** [comment]
An example is to use language 0 and add it to linkVars.
That means all links in the page go to:
https://domain.org/default-lang/

But the first call to the page will most likely only be:
https://domain.org/

**Comment by lochmueller** [comment]
``Maybe one should check at the end of content processing, if the page was cachable:
meaning not INT script and not set as no_cache and if so, create the entry if it doesn't exist.``

This is already part of the rule set. Perhaps it is a realurl/cooluri problem? If TYPO3 calculate the cHash and result in an error it will disable the caching of the page. Do you check if the cHash calculation is right for your given page? So I think this is not a EXT:staticfilecache problem?!

Regards,
Tim

**Comment by AndreasA** [comment]
Sorry, maybe I haven't made the issue clear.
The issue isn't that there is an error.
The issue is that staticfilecache only generates ONE entry for the page but it actually should create two (or more) even though the content is the same the page is reachable under different paths.
Which means that only one of those paths will use the statically cached file.

Example configuration:
```
config.linkVars = L
config.defaultGetVars {
    L = 0
}
```
And in realurl I configure a language code for L=0

Now if I go the the homepage of the site it will be:
http://www.domain.org/
However, if I have links to the homepage it will be:
http://www.domain.org/en/

Both those URLs are for the same page and language.

The reason is that insertPageIncache will not be called a second time as TYPO3 finds the page in the page cache.

A workaround is to create a TypoScript condition
```
[globalVar = GP:L = 0]

```

which means that TYPO3 will handle an existing L parameter as a new page cache entry.

The other part was more a suggestion on how to enable adding the same page with different URLs.

However, after thinking about it a bit I am not sure if "fixing" this is actually a god idea because it might result in a lot of created cache files by someone just randomly accessing URLs, especially if realurl is configured to e.g. ignore invalid values in a valueMap (like nomatch => null)
which probably wouldn't be a good idea either.

So maybe not a good idea to fix it anyway, although this can be an issue.
Maybe just add according documentation like adding a "dummy" typoscript condition or ensuring that the URL can only be reached with one path, otherwise one of them won't be cached.

On the other hand TYPO3 should result any wrong URLs to 404 (cHash etc.) so...

**Comment by lochmueller** [comment]
Hmm.... I suggest to add this "note" to the documentation. ok?

**Comment by AndreasA** [comment]
Probably good enough for most cases :)
