### ISSUE TITLE
unserializing configuration fails while installing 

### ISSUE THREAD

**Issue by julianhofmann** [lochmueller/staticfilecache#72]
unserializing configuration fails while installing 
-----------------

Due to PHP strict_mode unserializing extension configuration fails while installing extension.

Steps to reproduce the problem
------------------------------

1. Take a TYPO3 instance where staticfileacache has never been installed
2. Activate staticfilecache in Extension Manager

What is the expected behaviour?
-------------------------------

Activated extension.

What is observed behaviour?
---------------------------

 > Oops, an error occurred!
 > unserialize() expects parameter 1 to be string, null given

unserialize is called twice with (yet) missing Ext-Configuration (\SFC\Staticfilecache\Configuration::registerHooks(), \SFC\Staticfilecache\Configuration::registerCachingFramework()).
Thus, $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['staticfilecache'] is NULL, but strict_mode forces unserialize to accept only a string.

**Comment by lochmueller** [comment]
Hey @julianhofmann 
Could you try the current master. If this works great, I will publish a bugfix release...
Regards,
Tim

**Comment by julianhofmann** [comment]
Hi Tim.
Just checked the master. Now it's working in fresh instances well.
Thanks.

**Comment by lochmueller** [comment]
Done. Version 5.4.1 korrigiert das Problem.
