### ISSUE TITLE
Example .htaccess configuration

### ISSUE THREAD

**Issue by LimeUwe** [lochmueller/staticfilecache#75]
Hi Tim,

on t3cb I asked you for a possible reason, why the .htaccess rule set is not working on certain hosting providers, which do not expose server variables like %{DOCUMENT_ROOT}. (e.g. DomainFactory, 1&1)
In your talk you mentioned that you have successful created a configuration which works also there.
Could you please provide an example? It would be very appreciated. (I got to get it running there with older versions already... but not with the new version of the extension).

Alongside two other questions:

1. Is there a good way to test/debug the variables that are used in the .htaccess config?
2. In the documentation you only mention the location where to put the staticfilecache block for the 
"oldschool .htaccess rewrite rules". But which location is the the correct one, for the .htaccess rules which come with recent TYPO3 releases starting 7 LTS up to 9?

Best regards,
Uwe

**Comment by lochmueller** [comment]
Hey Uwe,

if "DOCUMENT_ROOT" do not exist, you have to set "SFC_ROOT" to the absolute root path by yourself.
Hmm... and the best way for testing in htaccess is to drop some parts and call the URL. I think this is the quickest way....
Related to "2". There is still the "RewriteCond %{REQUEST_FILENAME} !-f / RewriteCond %{REQUEST_FILENAME} !-d / RewriteCond %{REQUEST_FILENAME} !-l" check also in the current version. You put the ruls in front of the RewriteCond-statments.

Regards,
Tim

**Comment by lochmueller** [comment]
Note: Please use slack for geenral questions. The issue-tracker is for errors and features. Slack is much better for questions.... I close this issue here...

**Comment by LimeUwe** [comment]
Thanks for the quick reply. 
OK - I feel like slack is not a very persistent place. I'm always thankful for finding solutions in github issues for problems other people had before. (For my defence: i chose the isse type "Support Question" ;-) )
