### ISSUE TITLE
Static file for page is not flushed when clearing page cache

### ISSUE THREAD

**Issue by chesio** [lochmueller/staticfilecache#84]
## Bug Report

**Current Behavior**
I **don't** have boost mode enabled and when I click "Clear cache for this page", static files for the page are not flushed.

**Expected behavior/output**
Click on "Clear cache for this page" should flush static files for the page.

**Environment**
- TYPO3 version(s): 8.7.17
- staticfilecache version: 6.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**
Sorry, no idea :-)

**Additional context**
Flushing front-end caches flushes static files for the page (but also for all other pages).

**Comment by lochmueller** [comment]
Thanks for the bug report... it was a regression in Version 6.0.0 that is fixed in this bugfix: https://github.com/lochmueller/staticfilecache/commit/991e63a0ac03fbd9f0ce305d6a536c26c702bb0a

Will be part of the next version....

Regards,
Tim
