### ISSUE TITLE
PHP Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Patta** [lochmueller/staticfilecache#88]
## Bug Report

**Current Behavior**
The error
`Core: Error handler (FE): PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/[REMOVED]/web/typo3conf/ext/staticfilecache/Classes/StaticFileCache.php line 260 `
is shown in backend log.

**Expected behavior/output**
no warning in backend log

**Environment**
- TYPO3 version(s): 8.7.18
- PHP version: 7.2.8
- staticfilecache version: 6.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
http://php.net/manual/de/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

**Additional context**
none

**Comment by lochmueller** [comment]
Hey @Patta 
thanks for the bug report. I fixed the problems a few seconds ago in the current master. All "count"s are useless (because the count is not needed) and was replaced by "empty" calls. "Empty" to not throw warnings if the variable do not exist.
Regards,
Tim
