### ISSUE TITLE
[minor BUG] htaccess expire time isn't the same as tag cache

### ISSUE THREAD

**Issue by AndreasA** [lochmueller/staticfilecache#9]
The expire time in writeHtAccessFile uses time() + lifetime
instead of EXEC_TIME as is used when setting the cache entry information.

However, it might make sense to have it a few seconds later so that the page cache expires before the htaccess rule expires. However, probably still better to use EXEC_TIME and manually add a second or so.

**Comment by lochmueller** [comment]
Thanks for the hint... introduce utility function that get the current time and also respect the EXEC_TIME.

Thanks for your detailed reports...
