### ISSUE TITLE
Staticfilecache not generated in Typo3 v9.4.0

### ISSUE THREAD

**Issue by M4rt1n17** [lochmueller/staticfilecache#92]
## Bug Report

**Current Behavior**
Not generating static files and telling "static cache disabled on domain" for every single page

**Expected behavior/output**
After installation the Extension should be able to cache all pages which do not have login forms.

**Environment**
- TYPO3 version(s): 9.4.0
- PHP: 7.2.9
- Webserver Setup: nGinx v1.11.10 (proxy) + Apache v2.4.10
- staticfilecache version: 6.0.2
- Composer Mode: No
- OS: Linux (Debian 8.11)

**Comment by M4rt1n17** [comment]
Finaly managed it to work.

At **List** > **[rootPage]** > **Domain**
I had to replace "domain.tld" with "subdomain.domain.tld"
So [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) is required!
My FQDN was "www.domain.tld" maybe this can be avoided in future as www is standard subdomain?

Thanks

**Comment by lochmueller** [comment]
The domain should always be a FQDN. If you have the domain incl. www and excl. www point to TYPO3 create onw Domain as redirect to another. "www is standard subdomain" -> "www" is no standard-subdomain it is only common usage. But www.domain.tld and domain.tld are two different domains in many cases (Cookie handling, SSL cert etc.). So the best case is, to create the domain records for all domains in your TYPO3 installation to handle all this cases...

**Comment by lochmueller** [comment]
"Finaly managed it to work." -> So I close this issue...

**Comment by lochmueller** [comment]
If you have some hints for the documentation (e.g. find the domain record and create the records etc.) or external links to this point, feel free to fork the repo and add some lines to the documentation. 👍
