### ISSUE TITLE
In Typo3 v9.4.0 no subpage gets delivered cached

### ISSUE THREAD

**Issue by M4rt1n17** [lochmueller/staticfilecache#93]
## Bug Report

**Current Behavior**
rootPage (if not in subdirectory) gets cached. All subpages does not get cached.

**Expected behavior/output**
As Typo3 v9.4.0 got its own "realURL" ending Slashes are not given!
Example:

1.) www.domain.tld/contact (it looks like this in 9.4.0) **No trailing Slash!**
2.) www.domain.tld/contact/ (in 8.7.x with realURL it looks like this) **trailing Slash**

I also attached 2 screenshots which show the difference
With trailing SLash
![trailing Slash](https://user-images.githubusercontent.com/17692860/45273356-a201b780-b4b2-11e8-938d-cc18beb10ddd.PNG)
Without trailing Slash
![kein Trailing Slash](https://user-images.githubusercontent.com/17692860/45273369-b6de4b00-b4b2-11e8-948f-974dc894fa58.PNG)

I think I could just edit the .htaccess and manage it to rewrite a ending slash but would be cool if this Extension is able to do it out of box.

Another Problem of this constellation is, that with the trailing Slash the .html File itself can be cached (offline) with a unlimited Cache Time. I dont want that, therefor we have a blazing fast site, so that we can edit things and have it immediately updated for everyone.
The .html should be  "private, no-store" all the time.

**Environment**
- TYPO3 version(s): 9.4.0
- PHP: 7.2.9
- Webserver Setup: nGinx v1.11.10 (proxy) + Apache v2.4.10
- staticfilecache version: 6.0.2
- Composer Mode: No
- OS: Linux (Debian 8.11)

**Comment by lochmueller** [comment]
Please do NOT test your website performance with a single request in your web console (it will not work in the expected way). Check the content first (is it really the cached version? Check if you get the timestamp signiture in the output) and than use e.g. Apache Benchmark for testing the performance.

Related to the slash. Please check the documentation ("Note: https://github.com/lochmueller/staticfilecache/pull/90 (Please check the realurl configuration related to "appendMissingSlash". Perhaps your need a additional "/" in the rule above)"):
https://github.com/lochmueller/staticfilecache/blob/master/Documentation/Configuration/Htaccess.rst

Regards,
Tim
