### ISSUE TITLE
Backend-Login Problem 

### ISSUE THREAD

**Issue by hoezaykut** [lochmueller/staticfilecache#98]
## Bug Report

**Current Behavior**
After install the extension an clear the caches in Backend - im make a reload of the backend and become
this message:

Oops, an error occurred!
Call to a member function getPackagePath() on null

**Expected behavior/output**
i want to see what happens after install in the backend - a new module or whatever
later, 
 --- **i want to login in the backend** --- but its not possible.

**Environment**
- TYPO3 version(s): [8.7.19]
- staticfilecache version: [6.1.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- PHP Version 7.2.4 - Linux ( PHP 7.2-latest FPM )
- OPcache 64MB
- APCu 16MB
- APCu cache backend [Active] (...and in specific Server-Details because APCu and OPcache i have datas in the AdditionalConfiguration.php

**Possible Solution**

i have cleared all database caches, droped ols database caches and in the typo3temp -Folder
and the OPcache and APCu in additional
---- without success -----

**Additional context**
... they want the getPackagePath() i searched by [BE][lockRootPath]  in install tool, but i didnt make entries of a path ...

**Comment by hoezaykut** [comment]
Hi, 

now, i go to the info-module in the backend (without reload th page) an see this: 

Uncaught TYPO3 Exception
Call to a member function getPackagePath() on null

Error thrown in file
/html/typo3/typo3_src-8.7.19/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php in line 136.

**Comment by hoezaykut** [comment]
Core: Error handler (BE): PHP Warning: Use of undefined constant TYPO3_cliMode - assumed 'TYPO3_cliMode' (this will throw an Error in a future version of PHP) in /html/typo3/typo3conf/ext/dyncss/Classes/Service/DyncssService.php line 47

**Comment by hoezaykut** [comment]
Problem solved 

Oh my God i forget to rename thr main extension-Folder from Staticfilecache-master to Staticfilecache

... bit good to handle the other bug.

**Comment by lochmueller** [comment]
OK. I will close this issue. One more hint: Since TYPO3 7.x composer is recommended to manage the TYPO3 installations. I suggest to switch to composer... ;)
