### ISSUE TITLE
Staticfilecache is not generated / indexed

### ISSUE THREAD

**Issue by hoezaykut** [lochmueller/staticfilecache#99]
## Bug Report

**Current Behavior**
Staticfilecache is not generated - "No entries on this level of the page tree."

Please see attachment of a picture and the htaccess

**Expected behavior/output**
issues of a pages is expected

**Environment**
- TYPO3 version(s): [e8.7.19,]
- staticfilecache version: [e.g. 6.1.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [ no]
- Unix/Linux

**Possible Solution**
my htacess have any bug, i think.

![backend-info-statischer datei cache](https://user-images.githubusercontent.com/12664793/46559022-4844af80-c8ef-11e8-8408-a1281ba853cb.jpg)
[htaccess.txt](https://github.com/lochmueller/staticfilecache/files/2452180/htaccess.txt)

**Comment by lochmueller** [comment]
Hey @hoezaykut 
Do you check the documentation and also the extension configuration. Your are in the current mode: https://github.com/lochmueller/staticfilecache/blob/master/ext_conf_template.txt#L23 That mean you have to select the right page (and not the parent in the backend). Do you call the page without a TYPO3 cookie (session)? Notice: Just logout is not enough...

Regards,
Tim

**Comment by lochmueller** [comment]
PS: The htaccess is just for the request after the page is stored. If you do not get any cache entries you can ignore the htaccess for now. Check one step after another...

**Comment by hoezaykut** [comment]
Hello Tim, 

now it works, i didnt see the tree without the forest. 
Yesterday i create a new frontend with a realy real cookie accept-Handler - it means you must realy real aknowledge ...

The cookie in the frontend is set.

.after them i click every link (...)

**Comment by lochmueller** [comment]
ok. Great... so I close this issue, right?

Regards,
Tim

**Comment by hoezaykut** [comment]
yess

**Comment by hoezaykut** [comment]
one Question again -

ist es normal, "von aussen auf" auf die Links, einzeln zu klicken damit es in einem anderen Browser im Backend gelistet wird ?

**Comment by lochmueller** [comment]
Yes... staticfilecache is not geenrated with backend sessions to avoid cache entries with backend stuff.

**Comment by hoezaykut** [comment]
is startet a cron job, and ... maybee i have luck a/the Crawler (Extension: crawler) comes from "outside" in the night and handle the problem of "click the frontend every day" ...

**Comment by lochmueller** [comment]
@hoezaykut I suggest to run tools like this: https://github.com/lochmueller/seocli in You CI server instead of using the crawler extension. Otherwise... there is the Boost-Mode in the StaticFIleCache that take care, that the user always gat a fast page...

**Comment by hoezaykut** [comment]
okay ... the boostmode is active my configurations 4 page was this: 

config {
  no_cache = 0
# 2 Days-Test
   cache_period = 172800
  }

After 2 days the Cache View was empty again, but in between time i change to the boost-mode.

Mittwald have an additional cron job with "browser-based crawling" but i can only test, by switching the domain from other account...

... now i will try the extension seocli.

**Comment by lochmueller** [comment]
Note: Please create new issues for "new problems"
Note 2: seocli is no TYPO3 extension. It is a standalone CLI crawler for websites
Note 3: If the boostmode is active, only TYPO3 can recrawl the pages. External crawler get only the Static File version.
